### ISSUE TITLE
Allow parameters to be added to startPasswordless call for phone number

### ISSUE THREAD

**Issue by caitlin615** [auth0/Auth0.swift#100]
I want to be able to add `scope` to a `startPasswordless(phoneNumber)` authParams call, similarly to how you have it setup in `startPasswordless(email)`. It's an optional request parameter for the API call:  https://auth0.com/docs/api/authentication#get-code-or-link and should be allowed in both phone number and email calls. Can this please be added?

**Comment by cocojoe** [comment]
Hi @caitlin615, looking at the API documentation you linked it states:

authParams	
Use this to append or override the link parameters (like scope, redirect_uri, protocol, response_type), when you **send a link using email.**

I do not believe this functionality is available in the API so therefore not available in this library.

**Comment by andreyrd** [comment]
I have been including a `scope` override for SMS connections using Lock v1 for a long time, and it has always worked. The functionality is there in the API. I've decided to just stick to Lock v1.

I am in general frustrated in how much functionality has been taken out of or deprecated in Auth0 over the last year or so. ID tokens have been almost completely broken (and yes, I am only using them between clients/servers I control, not external services), and the new libraries are missing a lot of SMS and profile functionality.
