### ISSUE TITLE
Facebook login returns nil refreshToken

### ISSUE THREAD

**Issue by codyaweber** [auth0/Auth0.swift#114]
After logging in with facebook webAuth, I get credentials, but the refreshToken property is nil. Is this expected behavior?

(Sorry for the poor formatting - couldn't figure out the spacing.)

```swift
Auth0.webAuth()
            .connection("facebook")
            .start{ result in
                switch result {
                case .success(let credentials):
                // credentials.refreshToken is nil here
                case .failure(let error):
                    print(error)
                }
        }
```

**Comment by codyaweber** [comment]
After logging in with facebook webAuth, I get credentials, but the refreshToken property is nil. Is this expected behavior?

(Sorry for the poor formatting - couldn't figure out the spacing.)

`Auth0.webAuth()`
`.connection("facebook")`
`.start{ result in`
`switch result {`
`	case .success(let credentials):`
`		// credentials.refreshToken is nil here`
`	case .failure(let error):`
`		print(error)`
`	}`
`}`

**Comment by cocojoe** [comment]
You have not set any scope in your request, in particular you need to specify the `offline_access` scope to obtain a `refreshToken` in your `Credentials` instance.

```swift
.scope("openid profile offline_access")
```

You can find some general information regarding this here: [Refresh Tokens](https://auth0.com/docs/tokens/preview/refresh-token)
