### ISSUE TITLE
"Grant type 'http://auth0.com/oauth/legacy/grant-type/ro' not allowed for the client."

### ISSUE THREAD

**Issue by krispyk84** [auth0/Auth0.swift#121]
Using the Authentication API for login with database connection, I now get the following error on failure:

 "Grant type 'http://auth0.com/oauth/legacy/grant-type/ro' not allowed for the client."

It once worked, but no longer does. How can I modify this code to work:

Auth0
   .authentication()
   .login(
       usernameOrEmail: "support@auth0.com", 
       password: "a secret password", 
       connection: "Username-Password-Authentication"
       )
   .start { result in
       switch result {
       case .success(let credentials):
           print("access_token: \(credentials.accessToken)")
       case .failure(let error):
           print(error)
       }
   }

**Comment by cocojoe** [comment]
Hi @krispyk84 

If this is for an existing client (which it sounds like it is), please take a look at the following document https://auth0.com/docs/clients/client-grant-types

I recommend going forward you also take a look at our [OIDC Conformant Authentication](https://auth0.com/docs/api-auth/intro) documentation.

**Comment by hzalaz** [comment]
@krispyk84 sorry for that but for new clients (starting June 5th)  you need to enable them to use some endpoints. The info in [this doc](https://auth0.com/docs/clients/client-grant-types) might help to understand the reasons and how to enable those endpoints back
