### ISSUE TITLE
Xcode 9 and Swift 4

### ISSUE THREAD

**Issue by portellaa** [auth0/Auth0.swift#123]
Hello 👋, 

I didn't saw a guide on how to contribute or something like that, so sorry in advance if the issue description is not in the best.

# Problem
I'm using your framework in a new app that in be released in a near future and i tried to use with the new Xcode 9, which avoid my rage to go up anytime it crashes, but i found that it didn't compile.

# What i found
Mostly, it doesn't compiles due to:
## Dependencies
Nimble and OHHTPStubs, they are in old versions or specific language versions. 
Updating those to the latest released versions fix the compile issue of the dependencies.

## SilentSafariViewController
The subclass of `SFSafariViewController` is using an deprecated `convenience init`.
Adding a conditional availability on the `required init` fixes the problem.

```swift
if #available(iOS 11.0, *) {
    let configuration: SFSafariViewController.Configuration = {
       $0.entersReaderIfAvailable = false
       return $0
    }(SFSafariViewController.Configuration())
    super.init(url: URL, configuration: configuration)
} else {
    super.init(url: URL, entersReaderIfAvailable: false)
}
```

I will open a PR with this, feel free to reject it.
It would be really nice if we could use the beta version of xcode 9 to develop, since it brings a few stability improvements, but is a beta tool which you may not want to support until it is released.

🍻

**Comment by hzalaz** [comment]
@portellaa there is a PR that updates those dependencies, unless you need to use beta dependencies which I won't be so sure about. The rest looks good so we will merge

**Comment by portellaa** [comment]
sorry, i didn't saw the content of the PRs and none of them refer that in the name 🙂

fine then, no need for PR 😉

can you close the issue when the PR is merged? 🍻

**Comment by hzalaz** [comment]
@portellaa the only thing missing is 

```swift
if #available(iOS 11.0, *) {
    let configuration: SFSafariViewController.Configuration = {
       $0.entersReaderIfAvailable = false
       return $0
    }(SFSafariViewController.Configuration())
    super.init(url: URL, configuration: configuration)
} else {
    super.init(url: URL, entersReaderIfAvailable: false)
}
```

if you want to make the PR otherwise we will do it next week

**Comment by portellaa** [comment]
yes, i will :) thanks

**Comment by cocojoe** [comment]
@portellaa 

You should check out the existing [swift-4.0-beta branch](https://github.com/auth0/Auth0.swift/tree/swift-4.0.beta) if you want to have a play in Xcode 9 :)
It already includes your code and also has latest dependencies. I found a few other bugs in Nimble 7.0.1 but commented out those tests for now, so everything will pass.

Have fun.

**Comment by portellaa** [comment]
Awesome @cocojoe 😃 working like a charm.
