### ISSUE TITLE
Grant type 'http://auth0.com/oauth/legacy/grant-type/ro' not allowed for the client. after creating a new client id

### ISSUE THREAD

**Issue by thierrybucco** [auth0/Auth0.swift#124]
Hi,

we created a new client id, unfortunately I am no more able to login. I get this error:

Grant type 'http://auth0.com/oauth/legacy/grant-type/ro' not allowed for the client.

What must I do?

Thanks

**Comment by hzalaz** [comment]
Use the following method https://github.com/auth0/Auth0.swift#login-with-database-connection or follow instructions in this guide https://auth0.com/docs/clients/client-grant-types to enable the grant type

**Comment by thierrybucco** [comment]
I am using login method with parameters:

.login(usernameOrEmail: username, password: password,
			       connection: connection,
			       scope: scope,
			       parameters: parameters)

is the only way is to PATCH new client?

**Comment by hzalaz** [comment]
That is not the method I suggested you should use so if you dont want to change you need to patch the client
