### ISSUE TITLE
UserInfo class should show User ID

### ISSUE THREAD

**Issue by marco1981** [auth0/Auth0.swift#137]
**Version:**
1.7.1

**Description:**
UserInfo class does not contain information about user id. I know we can retrieve it by "sub" property, but I think it is more clear if UserInfo object can show "userId" property. 
Json object retrieved calling UserInfo API already contains this property: "user_id". It's just matter to parse json object properly

**Expectation:**
Have userId field available in UserInfo class

**Comment by cocojoe** [comment]
UserInfo class reflects the standard claims http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims and should be used with [OIDC Flow](https://auth0.com/docs/api-auth/tutorials/adoption/oidc-conformant)

If you are using the older flow, you can use https://github.com/auth0/Auth0.swift/blob/master/Auth0/Auth0Authentication.swift#L133
