### ISSUE TITLE
Switch to SFAuthenticationSession for iOS 11

### ISSUE THREAD

**Issue by x-cray** [auth0/Auth0.swift#142]
`SFSafariViewController` will no longer share cookies with Safari starting from iOS 11. This makes it hard to sign user out from social identity provider. Alternative approach is to use [SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) for authentication/authorisation. It was discussed in https://github.com/openid/AppAuth-iOS/issues/120 and there's a proposed pull request https://github.com/openid/AppAuth-iOS/pull/129
Is there any ongoing development to support iOS 11?

**Comment by hzalaz** [comment]
Once it's released as stable yes

**Comment by x-cray** [comment]
Do you mean GM release?

**Comment by hzalaz** [comment]
I mean stable one, GM could be fine

**Comment by cocojoe** [comment]
I am going to close as we are aware and monitoring the situation internally, thanks for discussion links.
