### ISSUE TITLE
Unauthorized Username/Password Login

### ISSUE THREAD

**Issue by ryuichis** [auth0/Auth0.swift#143]
I was able to login with this method

```
auth0.login(usernameOrEmail: email,
                    password: password,
                    multifactorCode: nil,
                    connection: "connection-name",
                    scope: "openid profile",
                    parameters: [:])
```

And I noticed `/ro` is now deprecated, and new method is favored https://github.com/auth0/Auth0.swift/blob/swift-4/Auth0/Authentication.swift#L85

So I switch to use the new one as

```
 auth0.login(usernameOrEmail: email,
                   password: password,
                   realm: "realm-name",
                   audience: "audience-name",
                   scope: "openid profile")
```

But this one gives me 401 unauthorized error.

By looking at the doc https://auth0.com/docs/api/authentication#authorization-code, I realized the `client_secret` is marked as required. So I hardcoded my client_secret, and managed to get it to work.

But this made me wonder if it is an issue to the `Auth0Authentication.swift` implementation, or did I miss any configurations which could allow me to login without hardcoding the `client_secret` on iOS side? Thanks.

**Comment by lbalmaceda** [comment]
Definitely, the `client_secret` _should not_ be used on any untrusted client like a mobile app. I'd check that the client you're using has that database connection enabled, and that an API with that audience exists. Does the error response include any more data like an error description?

**Comment by ryuichis** [comment]
Yeah, just double checked the database connection is enabled, and the audience exists. I am including the logs of the request and response below:

Request:

```
POST https://foobar.auth0.com/oauth/token HTTP/1.1
Auth0-Client: eyxxxxxxxxxxxxx
Content-Type: application/json

{"realm":"xxxxxx-user-db","audience":"com.xxxx.xxxxx-api","client_id":"xxxxxxxxx","password":"xxxxxx","grant_type":"http:\/\/auth0.com\/oauth\/grant-type\/password-realm","scope":"openid profile","username":"xxxxxx@gmail.com"}
```

Response:

```
HTTP/1.1 401
Content-Type: application/json
Www-Authenticate: Basic realm="Users"
Content-Length: 60
x-ratelimit-reset: 1503609224
x-auth0-requestid: ...............
x-ratelimit-limit: 1000000
x-ratelimit-remaining: 999999
Date: Thu, 24 Aug 2017 21:13:43 GMT
Cache-Control: no-cache

{"error":"access_denied","error_description":"Unauthorized"}
```

**Comment by lbalmaceda** [comment]
The other thing it may be happening is that your client doesn't have that grant enabled. I think by default, `native` type clients don't have it. Check [this](https://auth0.com/docs/clients/client-grant-types#edit-available-grant_types) doc on how to enable/disable client grants and try enabling the **Password** one.

**Comment by ryuichis** [comment]
![screen shot 2017-08-25 at 5 05 36 pm](https://user-images.githubusercontent.com/4386920/29734402-aec43bea-89b7-11e7-886d-7ac74b1ce48d.png)

I believe I turned on everything...

**Comment by hzalaz** [comment]
Is your application type not Native  @ryuichis ?

**Comment by ryuichis** [comment]
@hzalaz it is not, we use this client for both our web app and mobile app. Do we have to use a separate native client? If so, could you elaborate more on that? Thanks.

**Comment by hzalaz** [comment]
Yes, you need different clients for mobile and web app, sharing a single client is not recommended.

**Comment by hzalaz** [comment]
Each client is mean to represent the one asking for Auth so you should be able to tell them apart, also mobile apps and web app uses slightly different Auth flows if you go into detail on OAuth.

**Comment by ryuichis** [comment]
Switching to a mobile client made it work. Thanks for the discussions.
