### ISSUE TITLE
Refresh token is lost after refresh

### ISSUE THREAD

**Issue by danielphillips** [auth0/Auth0.swift#144]
Note that logging in to retrieve credentials with Auth0 returns: `access_token`, `expires_in`, `id_token`, `refresh_token`, `scope` and `token_type`; however when refreshing the credentials, `refresh_token` is not returned in the response.

---

If using the `CredentialsManager`, after logging in one would call `store(credentials:)` to persist the credentials for later use.

When credentials are needed, one would call `credentials(withScope:callback:)` on a `CredentialsManager` instance, and if the access token is expired the credentials manager is kind enough to renew the token on our behalf, transparently returning brand new credentials, which we then save again using `store(credentials:)` again.

However, since the credentials are stored onto one key in the keychain, and given the fact that `refresh_token` is not returned in the response when refreshing the token, the new credentials have no refresh token. 

Inside `retrieveCredentials(withScope:callback:)` of `CredentialsManager` there is a check to make sure the credentials have a refresh token, if it isn't there then the credentials manager returns a `.noRefreshToken` error.

At this point in time I must log out and login again. 

We think this is an oversight on the `CredentialsManager`.

I did however want to raise this issue on the chance that I'm not using the SDK as intended. I would greatly appreciate any advice or information on this. 

Thank you

**Comment by gscalzo** [comment]
Even if not ideal, a quick solution is in https://github.com/auth0/Auth0.swift/pull/145

**Comment by cocojoe** [comment]
Thanks, I've tested this now and can confirm. I am also going to propose auto saving the new credentials as a convenience as I feel it's the most common scenario for the intended audience of this utility.

**Comment by cocojoe** [comment]
Merged
