### ISSUE TITLE
Can't compile in Xcode 9 any longer, where is the swift-4 branch gone?

### ISSUE THREAD

**Issue by helloniklas** [auth0/Auth0.swift#155]
I'm pretty sure yesterday I was using a swift-4 branch and things were fine. Today I can't compile the project and the swift 4 branch seems to be gone?

The error I'm getting is:

/Users/niklas/Documents/development/iOS-b2b/Pods/Lock/Lock/DatabaseChangePasswordInteractor.swift:72:14: Value of type 'Authentication' has no member 'changePassword'

**Comment by helloniklas** [comment]
So, I now can't use the swift 4 branch I used yesterday, which all worked fine.

Pre-downloading: `Auth0` from `https://github.com/auth0/Auth0.swift.git`, branch `swift-4`

[!] Error installing Auth0
[!] Failed to download 'Auth0'.

**Comment by cocojoe** [comment]
The `swift-4` branch was a WIP and never official, only `releases` are official.  If you are using Auth0.swift I suggest you set the version to `~> 1.8` which is compatible in both Xcode8/9.  I see you are using `Lock.swift` there is a new version to be released soon.  However, if you set your branch to "master" until that is released you should be all good. 

I'll keep this issue open and I'll update it when Lock 2.4.0 is released.

Thx

**Comment by helloniklas** [comment]
ah right, as it turns out I don't actually use Lock, so removed the pod and it works fine now. thanks.

**Comment by jeco1996** [comment]
@helloniklas what did you do in order for it to work? I moved my project from swift 3 to swift 4 and all I get are errors of these 2 frameworks(lock and auth0)?

**Comment by helloniklas** [comment]
@jeco1996 I removed lock as I don't use it. The latest auth0 works fine with swift4 for me. Try and clean the project and recompile. As for lock, you might have to wait and they sort it out...

**Comment by cocojoe** [comment]
@helloniklas So Lock 2.4.0 was released which is compatible with Xcode 9.  However, it appears there is an issue if you are using Cocoapods although the solution is thankfully straightfoward.

https://github.com/auth0/Lock.swift/issues/470
