### ISSUE TITLE
No such module 'Auth0'

### ISSUE THREAD

**Issue by Scottdgibbard** [auth0/Auth0.swift#157]
In Xcode 9, Swift, I'm getting the error, "No such module 'Auth0.'"

**Comment by cocojoe** [comment]
Hi @Scottdgibbard if you would like some help you will need to expand upon this with more detail please.
 
What are you doing? How did you add Auth0 to your project? What version of the lib, how did you import to your project etc etc Thx

Also try cleaning the project then rebuilding.

**Comment by Scottdgibbard** [comment]
I'm trying to integrate Auth0 into my Xcode 9, Swift application. The Auth0 version is 1.8. I tried using Cocoa pods, but that didn't work so I tried using Carthage and it didn't work, so right now, I'm using Carthage.
I tried cleaning and rebuilding
Thanks!

**Comment by cocojoe** [comment]
This was probably your issue in Cocoapods (there is a simple fix provided). So I suggest you try that.
https://github.com/auth0/Lock.swift/issues/470

Carthage is a bit more involved so the issue is most likely configuration https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

**Comment by Saifu786** [comment]
Hi, am getting same error and am unable build my project because of no module Auth0. Please help me with this issue and am using xcode 10.1

**Comment by cocojoe** [comment]
@Saifu786 please raise a new issue and include the information requested and steps to reproduce. Thanks
