### ISSUE TITLE
Can't implement login via Office365

### ISSUE THREAD

**Issue by chyrta** [auth0/Auth0.swift#161]
Can't implement login via Office 365 when I use purchased connection for my project.

**Comment by cocojoe** [comment]
Hi @chyrta How are you launching authentication for this connection? Is this something that used to work and if so what has changed. Thanks

**Comment by chyrta** [comment]
@cocojoe I use the latest version of Auth0 for implementing web-based authentication. Android version of our project does the job great, but iOS does not, so I'm still trying to find out what is the problem with Auth0 for iOS.

**Comment by cocojoe** [comment]
@chyrta hi it would if you could add some details, what doesn't work exactly? How are you using WebAuth? Is it an issue during WebAuth, if so what is the error, is there a screenshot?

The WebAuth for both iOS and Android work in the same way, they launch the browser and both point to the same Hosted Login Page. So if Android works and iOS doesn't then there is a strong change it is a configuration issue.  However, hard to say without any real information.

Thanks

**Comment by chyrta** [comment]
@cocojoe I have updated again Auth0 to the latest version and now I don't have this problem, thanks.
