### ISSUE TITLE
Federated flag is "still" not taken into consideration

### ISSUE THREAD

**Issue by sohayb** [auth0/Auth0.swift#178]
I try to logout using the below code:
```swift
var auth0 = Auth0.webAuth()
auth0.clearSession(federated: true) { outcome in
    DispatchQueue.main.async {
        let credentialsManager = CredentialsManager(authentication: Auth0.authentication())
        _ = credentialsManager.clear()
        CredentialsHelper.resetCredentials()
    }
}
```
After that is executed successfully, I try to login again, I tap on `Google` authentication, `Auth0` won't ask me for credentials and just logs me in.
Another part of the issue (related tho), is that if I deleted the app, and then re-installed it again, how can I clear the IdP values so `Google` login would ask for credentials again, without using the above method? As that would trigger a `webView` to appear  (on **iOS 11** at least) and disappear suddenly for the user after he launches the app for the first time, which is a bad UX.

**Comment by cocojoe** [comment]
@sohayb During federated the flow of redirects causes the browser to callback the app (to close the browser). However, the browser will then try to redirect in this case to Google and may not have enough time to complete before the browser is dismissed. 

I would recommend trying to force the login using the value `login` for `prompt` in your WebAuth instance. 

```swift
.parameters(["prompt": "login"])
```

**Comment by sohayb** [comment]
it seems this is working, thanks! Will close this for now.
