### ISSUE TITLE
credentials.expiresIn empty

### ISSUE THREAD

**Issue by mpycio** [auth0/Auth0.swift#179]
I'm using _Auth0.authentication().login_ method to log-in user into my app but response returns credentials with _expiresIn_ property empty. Now when I try to renew idToken with _CredentialsManager.credentials_ it checks for expiresIn being set and being a future date and always returns .noRefreshToken. Can someone please point me in the right direction for solving this, should expiresIn be set or am I using wrong method?

**Comment by cocojoe** [comment]
@mpycio Please show me the login snippet you are using. Thx

btw I wouldn't expect this to work if you are using a non OIDC client.

**Comment by mpycio** [comment]
Yes, client doesn't have OIDC enabled as it was used with previous versions of Lock/Auth0, I decided to upgrade but enabling OIDC breaks existing app so I guess I'll have to add new client. Code snippet below.

```
Auth0
            .authentication()
            .login(
                usernameOrEmail: email,
                password: password,
                connection: “Username-Password-Authentication”,
                scope: “offline_access openid email”,
                parameters: [“device”: UIDevice.current.identifierForVendor!.uuidString]
            )
            .start { (result) in
                switch result {
                case .success(let credentials):
                     // here credentials.expiresIn are empty
                case .failure(let error):
                    debugPrint(error)
                    resultHandler(.error(.serverError))
                }
            }
```

**Comment by cocojoe** [comment]
Yes this will not work with Credentials Manager, I would recommend upgrading.  You just need to use `https://github.com/auth0/Auth0.swift/blob/master/Auth0/Authentication.swift#L126`
There is no need to use the `device` param either for OIDC.
