### ISSUE TITLE
Require User to Re-enter Password

### ISSUE THREAD

**Issue by ahmattox** [auth0/Auth0.swift#183]
We need to require a user to confirm their identity to access part of an application.

Re-invoking the web auth: `Auth0.webAuth(). ... .start(...)` presents the log in view, but gives the option to continue with the same user without re-entering a password with the message, "Last time you logged in with".

There appears to be an option `rememberLastLogin` to disable this, but it's unclear if that's supported by the Swift SDK.

**Comment by cocojoe** [comment]
It sounds like you are possibly using the wrong tool for the job here, `re-enter` implies they have already been authenticated but are perhaps accessing a secure screen which requires additional validation.

In that case I would look perhaps at something like Touch ID / Face ID to quickly perform this validation inside the app.  https://github.com/auth0/auth0.swift#biometric-authentication

**Comment by ahmattox** [comment]
@cocojoe Makes sense. It is what you're describing, but in this case I don't think that would be appropriate. Verifying with a password is preferred. Happy to give more details if that context is helpful.

**Comment by ahmattox** [comment]
@cocojoe If this not currently possible, is it something that could be considered? Or can I provide any more details? We were pretty set on Auth0 for a new app, but this is a critical need.

**Comment by cocojoe** [comment]
@ahmattox as you mentioned you could disable `rememberLastLogin`  [Lock options](https://auth0.com/docs/libraries/lock/v10/configuration) in your Hosted Login Page in the [Auth0 Dashboard](https://manage.auth0.com/#/login_page).

**Comment by ahmattox** [comment]
That could work. Is the hosted login a feature that will be supported in the future? According to the documentation hosted pages are not supported by Lock v11 and Auth0.js v9.

**Comment by cocojoe** [comment]
Yes, Lock 11 was released to address a different issue. The hosted login page doesn't need to use it.

```
Lock v11 is a version of Lock tailored for embedded login in your applications. If you use Auth0's Hosted Login Page, do not upgrade to Lock v11. Instead, keep using the latest version of Lock 10. The Hosted Login Page remains the simplest and most secure method by which to authenticate users for your applications. Lock v11 is designed to make cross-origin authentication work smoothly for when you cannot use the Hosted Login Page and need to embed a login in your application.
```

**Comment by ahmattox** [comment]
Great! We'll give that a try, and let you know.

For what it's worth I feel this could still be a useful (albeit rare) feature, and seems like something the page already nearly supported. Also the versioning is a little strange if 10 and 11 are both simultaneously supported, but that's no problem.

**Comment by cocojoe** [comment]
11 is now the default for the HLP 😄
