### ISSUE TITLE
Token expiry issue.

### ISSUE THREAD

**Issue by mpycio** [auth0/Auth0.swift#185]
I'm not sure this is issue of the swift library but there seems to be a problem with response to a login method, my client is set to expire token in 36000 seconds (10h) and this value is set correctly in JWT token payload but the response to the login method returns expires_in value as 86400 (1day).

Client settings:
![screen shot 2018-02-08 at 21 14 24](https://user-images.githubusercontent.com/932592/35998808-985cb29c-0d15-11e8-98f8-a95665b490ae.png)

Response.swift return value in line 57:
![screen shot 2018-02-08 at 21 19 17](https://user-images.githubusercontent.com/932592/35998850-c063f674-0d15-11e8-9f2f-0124f388bc37.png)

And token itself:
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1UWXpSVEZFTVVZM09VRkRRelF3UlRCQk16TTNRVGhGTkRZMVFUZ3lPRFZETXpaRlJqazFNUSJ9.eyJlbWFpbCI6Im1weWNpb0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9wb2xpc2Fzc2lzdC5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NTg4YmQ2ZTkxZGQ4NGUwNjEzZjNmNmM0IiwiYXVkIjoidmg5U2VHRVo0T0lROTVjbHJZenIxRGlLVUJ2a2dFMm4iLCJpYXQiOjE1MTgxMjMxOTIsImV4cCI6MTUxODE1OTE5Mn0.Qzc1FS_3La825Qn_dVtCuZGPjC7Xo4BT6xpo-ad7qtg8qf7ltnMJhP0M4jBRA1AjaPR1xAEdcp5J2u3jyE8UGzeqrgAvC5m7v0nLHrOdBAjPe254AAYIWsB-3WR6sE6niSL0EVpuSmevG4MLqqIth2miwITIDL5yYVv2MAqiTw3H7DSTQ3pw1Uxg99STLz6tka3DiI1N772hUyu_YiITf-s02KBI3bxnPgVZs6-T_5D3PKrXG79tqU9o3MDwuA_BgXCd8rWHtY024t6Okz4bbFBj6MtqjgVZ6baN5rUColIPSkyVDqQ_ZglyLX_OO19c1eiuLR-MuhvULCeNtY0YPQ

So the problem now I have is that NodeJs library uses token paylod to validate token but Swift client uses expires_in response value and after 10h there's a mismatch and ios client keeps sending expired token that is being rejected by backend system until 24h pass and it tries to renew a token only after 24h passes?.

Ams I missing some settings on Auth0 client or is this a bug somewhere in auth0 system?

**Comment by SeanLintern** [comment]
I have also just experienced this, I set the expiration in the dashboard to 60 seconds, then check login to get a new token, check token expireIn and its 1 day from login time, but backend rejects token as its no longer valid.

I am using the `Auth0.authentication().login`

**Comment by cocojoe** [comment]
In the server response the `expires_in` refers to the expiry of the `access_token`.

**Comment by mpycio** [comment]
Thanks for the info, but I'm not sure how that helps me. So swift library checks access_token expiry date and sends potentially expired JWT token or refreshes before it expires depending on JWT Expiration value in auth0 client settings?
Other end uses https://github.com/auth0/express-jwt maintained by Auth0 team so I'm not sure what can I do to fix this.
Maybe I don't understand your response correctly so please let me know if there's something I can do to make both ends work same way?

**Comment by SeanLintern** [comment]
This also causes an issue with Credentials manager with automatically expires the credentials after 24 hours ....

**Comment by cocojoe** [comment]
@mpycio In the authentication response you posted, the `expires_in` value refers to the expiry of the `access_token` value not the `id_token`. This is my understanding as the backend option does say _control the expiration of the **id token**_ It doesn't say **access token**

**Comment by SeanLintern** [comment]
Is the credentials manager class for storing Auth0 access credentials only? Obviously I can just take the idToken and keychain it myself, I was just under the understanding that Credentials Manager was a helper for this, but the credentials store access the hasValid() before returning credentials and returns nil if the accessToken is expired.

**Comment by cocojoe** [comment]
The credentials manager is designed to look after your AT (access_token) which grants you access to Auth0. [hasValid()](https://github.com/auth0/Auth0.swift/blob/master/Auth0/CredentialsManager.swift#L82) returns a `bool`.
It is designed to be used with refresh token, so the credentials manager will automatically renew your AT when it expires (e.g. 24 hours)

**Comment by cocojoe** [comment]
One thing I should have mentioned, for majority case you shouldn't use the id_token for validation in a backend.  https://auth0.com/docs/quickstart/native/ios-swift/04-calling-apis

You can obtain a JWT access_token by specifying your Auth0 API identifier as the audience in your auth. https://manage.auth0.com/#/apis
