### ISSUE TITLE
Passwordless without Hosted Login

### ISSUE THREAD

**Issue by andreyrd** [auth0/Auth0.swift#186]
The Auth0 [documentation](https://auth0.com/docs/hosted-pages/login#why-use-the-hosted-login-page) states two things as facts:

> Why use the Hosted Login Page rather than embedding your login functionality within your application?
>
> Security is the primary reason, followed by ease of setup. Cross-origin authentication is inherently more dangerous, and more likely to be vulnerable to man-in-the-middle attacks. Using the Hosted Login Page for the authentication process with Auth0 prevents that from ever being a concern. Additionally, the Hosted Login Page is very easy to implement, especially if a custom UI is not required.

> Currently, the Hosted Login Page is the only way to use Passwordless authentication on Native platforms. So if your use case is a native iOS or Android application, for example, and you intend to implement Passwordless, you will need to use the Hosted Login Page.

On a native platform, does the first even apply? What's the difference between having a browser open up to execute the authentication code, or just executing the code natively?

As for the second point, is this simply because the new passwordless flow has not been implemented in Auth0.swift? I see that there's a `startPasswordless` method [already implemented](https://github.com/auth0/Auth0.swift/blob/master/Auth0/Authentication.swift#L290) but it appears to be the old flow that will soon be removed. (I can't find documentation on the deprecations/removals, I just have an email from Auth0 about it.)

The new passwordless flow is implemented in Auth0.js v8, which is open source. If someone (potentially us) were to implement the flow in Swift basing it off of the JS implementation, would it be helpful if we opened a PR against this repository with the implementation?

**Comment by cocojoe** [comment]
@andreyrd The method show in Auth0.js 8 uses cross-origin auth and is not available for mobile browsers.

I can assure you when an appropriate endpoint is available I will add it. I do not have a hard ETA for this though, other than soon.

**Comment by andreyrd** [comment]
Thanks for the response!

Maybe I'm misunderstanding, but HTTP requests made from native code don't have any CORS restrictions?

I was able to manually authenticate via HTTP requests using the same endpoints Auth0.js 8 uses. From a high level:
1) `POST /passwordless/start`
2) `POST /co/authenticate`
3) `Get /authorize`
I'm guessing there are security issues with this approach since it isn't used, though?

If it helps, I can maybe work on an actual working example in a Swift Playground.

I successfully got a 302 redirect on step 3, with the access_token URL parameter, which the native HTTP code could then parse out and return?

I did this using [Paw](paw.cloud), no browser involved other than to discover the necessary endpoints and parameters.

**Comment by luisrudge** [comment]
@andreyrd Isn't paw just using a browser underneath? That's why you can parse the access_token that we send in the url fragment. Basically, the server never receives anything after the hash (`#`), that's why we send `https://your-redirect-url.com/#access_token=foobar`. In this case, if you hit any server, the browser doesn't send the hash at all.

If you access `https://requestb.in/1it3wmj1#access_token=foobar`, you'll see that the inspection page doesn't know anything about the hash itself: https://requestb.in/1it3wmj1?inspect

So, your third  request will have a 302 response, but you won't be able to see the hash if you're calling from a server. I'm not sure how mobile works in that regard, but I'm pretty sure it's the same.

**Comment by andreyrd** [comment]
@luisrudge the requests done mobile side will work exactly like the requests done in Paw. They're both just using standard HTTP clients underneath. I'll start working on a Swift playground to confirm though, and maybe help explain it better :)

The client will never actually visit the redirect, it'll just pull out the URL given in response #3. So there's no server involved at this point. RequestBin doesn't see the hash fragment because the browser doing the request strips out the hash fragment before sending it.

**Comment by luisrudge** [comment]
Right, so it's a browser thing then? Good to know 😝 I'm not sure if there are any security implications of doing this. I think you should ping our amazing support team at https://support.auth0.com and ask them to do a security check in your implementation. I'm pretty sure this scenario is totally not supported, even if it works. Our native SDKs will implement this feature once we have a proper solution for this in the server.

**Comment by andreyrd** [comment]
Couldn't find any way to read input in Swift Playgrounds so I created a simple demo app instead!
https://github.com/andreyrd/Auth0-iOS-Native-Demo

I'll send it to my support ticket as well so the team can do a security check! Thanks!

**Comment by cocojoe** [comment]
You can use at your own risk. However, this is not an officially supported use case.
