### ISSUE TITLE
refreshToken is nil :((

### ISSUE THREAD

**Issue by ADevelopStudio** [auth0/Auth0.swift#193]
- I have activated Refresh Token in grand types,
- I use scope: "openid profile offline_access" 
however, I recieve  refreshToken: nil and somehow my scope in server responce is "openid profile"
Why?
<img width="841" alt="screen shot 2018-04-11 at 10 25 31 am" src="https://user-images.githubusercontent.com/5238454/38590171-f626509e-3d72-11e8-8048-4b63d393f3c6.png">
<img width="280" alt="screen shot 2018-04-11 at 10 27 51 am" src="https://user-images.githubusercontent.com/5238454/38590192-069a8094-3d73-11e8-886c-7c7923517d79.png">

**Comment by cocojoe** [comment]
Enable logging and please post your request and response.  Thx
https://github.com/auth0/Auth0.swift#logging

**Comment by ADevelopStudio** [comment]
POST https://medapps.au.auth0.com/oauth/token HTTP/1.1
Auth0-Client: eyJuYW1lIjoiQXV0aDAuc3dpZnQiLCJ2ZXJzaW9uIjoiMS4xMC4xIiwic3dpZnQtdmVyc2lvbiI6IjMuMCJ9
Content-Type: application/json

{"realm":"rg3-dev","audience":"rg3_api-amazon-endpoint","client_id":"iFZsi6Acms16WjHxOB42FsCerW9cpxzF","password":"_REMOVED__","grant_type":"http:\/\/auth0.com\/oauth\/grant-type\/password-realm","scope":"openid profile offline_access","username":"_REMOVED__"}

HTTP/1.1 200
Content-Type: application/json
Content-Length: 1907
x-ratelimit-reset: 1523490813
x-auth0-requestid: 7de8c4e9716492cafe61
Pragma: no-cache
Strict-Transport-Security: max-age=15724800
x-ratelimit-limit: 100
x-ratelimit-remaining: 99
x-robots-tag: noindex, nofollow, nosnippet, noarchive
Date: Wed, 11 Apr 2018 23:39:08 GMT
Cache-Control: private, no-store, no-cache, must-revalidate, post-check=0, pre-check=0

{"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik9ERkVRMFF5TVVNeFFVVTJPVVZHUVVZd05rRkZOekl4TWpnNU4wVkJOakE1TnpoR1FqRTNOUSJ9.eyJpc3MiOiJodHRwczovL21lZGFwcHMuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDU5ZjAwNjE3ZDQ0MTI2NWIzNTMwMjg1MyIsImF1ZCI6WyJyZzNfYXBpLWFtYXpvbi1lbmRwb2ludCIsImh0dHBzOi8vbWVkYXBwcy5hdS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNTIzNDg5OTQ4LCJleHAiOjE1MzIxMjk5NDgsImF6cCI6ImlGWnNpNkFjbXMxNldqSHhPQjQyRnNDZXJXOWNweHpGIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSIsImd0eSI6InBhc3N3b3JkIn0.M-fcPy7EWjlqfPi_6p63eU09yymfeXN8VEuhnM5vRg-SOJm6ra11tc9QzWfnt7mvyT9cUjAwyNzXkdIFIyfqcCtdLH_1fi171L9h1rZlh3mDrcEvyJ6KTr6xnVbGLtUn7psw6tQm-ydCQs7zNQ8ZSGlTTT7-9Aao05sEYfiE1qULLwG4-NHBiGkhG2LKDDmz0eTNPpfEH1rQsG1KimAAGK-RAZUsdbMf2SKslbx3wtorb2qJSzERvSYCWm-4b59XanY2EZ2IZxCtAmMoVAP2Jr_6p-LJsUDG6ECw_lsSDRE8qUeKj36ai0vuKRB_UorrfpYnqQ0SKDHjqxCTSoT5RQ","id_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik9ERkVRMFF5TVVNeFFVVTJPVVZHUVVZd05rRkZOekl4TWpnNU4wVkJOakE1TnpoR1FqRTNOUSJ9.eyJuaWNrbmFtZSI6ImRldityZzAyZGV2IiwibmFtZSI6ImRldityZzAyZGV2QG1lZGFwcHMuY29tLmF1IiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzI5NGMyYjE1ZjdiMjE5MjlhYTJkODEwM2RjZDQ5YWY5P3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGZGUucG5nIiwidXBkYXRlZF9hdCI6IjIwMTgtMDQtMTFUMjM6Mzk6MDguNzQzWiIsImlzcyI6Imh0dHBzOi8vbWVkYXBwcy5hdS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NTlmMDA2MTdkNDQxMjY1YjM1MzAyODUzIiwiYXVkIjoiaUZac2k2QWNtczE2V2pIeE9CNDJGc0Nlclc5Y3B4ekYiLCJpYXQiOjE1MjM0ODk5NDgsImV4cCI6MTUyNzA4OTk0OH0.nqL_0syfjUScSpqFXHsnltXE9YeIAD7GDKheI9qNmVJh0IDFfADR9bIJWhKlJuNcdI9PfLqxLZfZTc-nyWumVlOB49zdlSzqumlvFka1UwU9SeFhAm-Fm_2wbh1Otm3vd_FbHrDKO6tyCHKXJdJLz1H8wonBTIwcO1B5m9vdvbI8THBZR3EmJCNZ-Sbo1HRLwD8rbdL9n56AHumUNF5PFZYSMgXtNpMXwfyxxrur9XcdJ0BZkUms5qqeVaSn6LSgnvJox4NQeC3jvMhs27G8IcwNy6Jf06ULJYHQsDbt0oJLIcSydi6XFnutjllZHmDajuNhpZ39nWUq_9oNyo3x0Q","scope":"openid profile","expires_in":8640000,"token_type":"Bearer"}

**Comment by cocojoe** [comment]
In the [Auth0 Dashboard](https://manage.auth0.com/#/apis) under APIs, did you enable `Allow Offline Access`?
I redacted some of the info in your post, I removed the `audience` value. However, I think it was an audience other than `https://medapps.au.auth0.com/userinfo`.

**Comment by ADevelopStudio** [comment]
thanks, @cocojoe 
problem solved!
