### ISSUE TITLE
Path configure in universal links path 

### ISSUE THREAD

**Issue by SiddharthPromact** [auth0/Auth0.swift#197]
Hello Here i want to perform universal deep linking to my iOS app but due to the path not as per we want we can’t able to perform universal deep linking in my iOS app. I also refer [link](https://community.auth0.com/t/path-configure-in-universal-links-path/11218) but we are not getting solution for this.

also ask on Stackoverflow: [https://stackoverflow.com/questions/50207213/universal-links-with-auth0-ios](url)

**Comment by cocojoe** [comment]
So you want to add links to the Auth0 hosted apple-app-site-association ?

**Comment by SiddharthPromact** [comment]
@cocojoe Yes, i want to add my path in it

**Comment by cocojoe** [comment]
Then no this is not possible, I suggest you reach out to our excellent support team and request this.
https://support.auth0.com/
