### ISSUE TITLE
Disable the superfluous_disable_command in SwiftLint

### ISSUE THREAD

**Issue by chrisjf** [auth0/Auth0.swift#200]
Hey Auth0 Devs,

### Bug Description

I have the following error in Xcode:

`MyProject-iOS/Carthage/Checkouts/Auth0.swift/Auth0/_ObjectiveManagementAPI.swift:73: error: Superfluous Disable Command Violation: SwiftLint rule 'function_parameter_count' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)`

Could [this issue](https://github.com/realm/SwiftLint/issues/1855) be fixed? I'm stuck on SwiftLint 0.19.0 and would like to upgrade but can't until this issue is fixed. My original plan was to submit a pull request but I haven't had time (obviously considering the original submitted issue is from Sept. 2017.) :/

If you read through the comments, the correct fix would be to **disable the `superfluous_disable_command` from Auth0's SwiftLint configuration file**.

Thanks for being awesome! 

Chris

**Comment by cocojoe** [comment]
What stops you updating your SwiftLint? 0.19 is a 12 month old version now. If there is an easy way to check if carthage is doing the compiling I may just remove it from the build  all together when it's carthage.

**Comment by chrisjf** [comment]
Hi @cocojoe If you read the [linked issue](https://github.com/realm/SwiftLint/issues/1855), you see that when I build my project in Xcode and have installed a version of SwiftLint greater than 0.19.0, I get the error (pasted above, and screenshot below):

![swiftlint-error](https://user-images.githubusercontent.com/105042/30925795-17d84e36-a381-11e7-9542-7a3f619ea320.JPG)

So that's why I'm "stuck" on SwiftLint, because the error doesn't appear in 0.19.0.

And actually, I am not using Carthage anymore because my team ran into problems. So we now have added Auth0 to the project workspace manually (added Auth0 to the Build targets list in the Scheme,  added it to Link Binary with Libraries build phase, as well as added a "Copy Files" phase to the Build Phases with the Destination set to Frameworks). If you would like to provide a more detailed step-by-step guide of how we manually build Auth0 as part of our workspace, please just let me know and I'll paste the instructions in a comment.

So according to the SwiftLint devs (as commented on the linked ticket) the solution should be to **disable the `superfluous_disable_command` in Auth0's SwiftLint config file**.

**Comment by cocojoe** [comment]
Adding manually is not something we can support as there are so many potential configurations and manual adding is seen as more of an advanced use case as you're taking responsibility for all of the setup.

I did notice that you added the `//swiftlint:disable` to the code as it is not there on master?
https://github.com/auth0/Auth0.swift/blob/master/Auth0/_ObjectiveManagementAPI.swift#L72
So looks like you are using an older version of Auth0.swift as well, you should definitely upgrade.

From our perspective, the current release using latest swiftlint `0.25.1` has no errors.
