### ISSUE TITLE
Adding request header using new method

### ISSUE THREAD

**Issue by vinamelody** [auth0/Auth0.swift#212]
Hi, How can I add request headers (as parameters?) when using non-deprecating method such as:

- `public func login(usernameOrEmail username: String, password: String, realm: String, audience: String?, scope: String?) -> Auth0.Request<Auth0.Credentials, Auth0.AuthenticationError>`
- `public func createUser(email: String, username: String?, password: String, connection: String, userMetadata: [String : Any]?) -> Auth0.Request<Auth0.DatabaseUser, Auth0.AuthenticationError>`
- `public func renew(withRefreshToken refreshToken: String, scope: String?) -> Auth0.Request<Auth0.Credentials, Auth0.AuthenticationError>`
- `authentication().userInfo(token)`
- `resetPasswrd(email:, connection:)

Thanks in advance!

**Comment by cocojoe** [comment]
For the first one, you should check you are on the latest version as it can already do this.
https://github.com/auth0/Auth0.swift/blob/master/Auth0/Authentication.swift#L129

For the rest of them I can't see a use case. What problem are you trying to solve?

**Comment by vinamelody** [comment]
Thanks @cocojoe ! yeah indeed! 
I'm just trying to add request header items :)
