### ISSUE TITLE
podspec declares iOS 9 deployment target but sdk uses iOS 10 APIs

### ISSUE THREAD

**Issue by kdawgwilk** [auth0/Auth0.swift#216]
This line uses a Type that was introduced in iOS 10 (see https://developer.apple.com/documentation/uikit/uiapplication/openurloptionskey) https://github.com/auth0/Auth0.swift/blob/9b9c194dda81386a6e773fae365229ca5e2c0a39/Auth0/_ObjectiveWebAuth.swift#L131
but the podspec declares iOS 9 as deployment target 
https://github.com/auth0/Auth0.swift/blob/9b9c194dda81386a6e773fae365229ca5e2c0a39/Auth0.podspec#L56

**Comment by kdawgwilk** [comment]
Workaround for those that are having the same issue, add this post_install hook at the bottom of your `Podfile`:
```rb
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target == 'Auth0'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            end
        end
    end
end
```

**Comment by cocojoe** [comment]
Good catch, it should match. Although I imagine we will becoming to the end of iOS 9 as the minimum soon, once 12 is released.

**Comment by cocojoe** [comment]
So just checked this in Xcode. The min deployment target in Auth0.iOS project settings is iOS 9.0 and no problems are reported during the build and the cocoapod is correct in matching the projects settings.

**Comment by cocojoe** [comment]
@kdawgwilk is this still an issue?

**Comment by cocojoe** [comment]
Closing stale
