### ISSUE TITLE
Custom Domains

### ISSUE THREAD

**Issue by itjunkii83** [auth0/Auth0.swift#217]
I have setup and verified my custom domain and it says _ready_. I am using webAuth and the auth0.swift in iOS. If set login.trifectanutrition.com in my Auth0.plist I get this error:

Error: Service not found: https://login.trifectanutrition.com/userinfo

I am trying to avoid the pop-up prior to the Universal login which mentions the auth0.com domain, I need our customers to believe they are dealing directly with us which was my whole goal with this custom domain. Can you let me know what steps I am missing to make this work?

```
Auth0
.webAuth()
.scope("openid profile offline_access")
.audience("https://" + custom_domain + "/userinfo")
.parameters(["__token_issuer" : "https://login.customdomain.com"])
.start {
		switch $0 {
		case .failure(let error):
		  print("Error: \(error)")
		case .success(let credentials):
                   //
}
```

**Comment by itjunkii83** [comment]
Auth0 support instructed me how to fix this. Just comment out the .audience line. Wish that was documented somewhere, I have to assume most companies don't want Auth0's branding on their login pages.

**Comment by cocojoe** [comment]
Thanks for the information, ah so you're talking about the iOS SFAuthenticationSession popup that informs the user of the server they are connecting to for authentication. Yes this should be documented better. Let me add this to the backlog.

**Comment by cocojoe** [comment]
Had a chance to check on this, you ca set the `audience` to use the original Auth0 domain for your tenant when it comes to grabbing the user profile, this URL is not something visible to the user.

The pop-up name is the domain of the URL used to call authorize, an Apple *trust* feature vs any kind or branding exercise. 

I will add a note regarding the correct use of `audience` when you are using the Custom Domains feature. 👍
