### ISSUE TITLE
Compiler Issue in Xcode 10 Discussion

### ISSUE THREAD

**Issue by cocojoe** [auth0/Auth0.swift#220]
There is a known issue when compiling in Xcode 10, the Swift 4.2 compiler introduced a bug (which has been recently patched but did not make it into Xcode 10 GM). 
This is a problem today but will be fixed in a later Xcode 10 release. Awkward...

The issue results in a **Segmentation Fault: 11** caused by when a `mutating function` returns `Self`.

Reference: 
https://github.com/apple/swift/pull/18937
https://github.com/apple/swift/pull/19038

Affected Code:
https://github.com/auth0/Auth0.swift/blob/master/Auth0/Loggable.swift#L40
```
mutating func using(logger: Logger) -> Self {...}
```

https://github.com/auth0/Auth0.swift/blob/master/Auth0/Loggable.swift#L52
```
 mutating func logging(enabled: Bool) -> Self {...}
```

Suggested `workarounds` include:

1. Changing _Self_ to _Loggable_, this breaks method chaining.

It is a Breaking Change as any chaining use is now broken (but it's easy to fix). However, the BC is really in the compiler so perhaps just clear notes would be okay in the release?

2. Can't remove mutating as inherited in protocols & structs.

**Comment by cocojoe** [comment]
Have taken a deep breath now.  
Will roll out with creating a new instance, which may be an improvement for immutability. No BC either.

```
func using(logger: Logger) -> Self {
        var loggable = self
        loggable.logger = logger
        return loggable
    }
```

```
func logging(enabled: Bool) -> Self {
        var loggable = self
        if enabled {
            loggable.logger = DefaultLogger()
        } else {
            loggable.logger = nil
        }
        return loggable
    }
```

**Comment by cocojoe** [comment]
I'll raise a PR for this tomorrow and update Lock.

**Comment by OrestNazarewycz** [comment]
Thanks for being so responsive on this one, really appreciate it @cocojoe !!

**Comment by cocojoe** [comment]
PR In Progress: https://github.com/auth0/Auth0.swift/pull/221

**Comment by cocojoe** [comment]
Released
