### ISSUE TITLE
Unable to login after updating to latest version of Pod

### ISSUE THREAD

**Issue by leopic** [auth0/Auth0.swift#224]
I recently updated from version 1.9.2 to 1.13.0 of the library and I'm now unable to complete the profile fetching process.

Any calls to `Authentication.start` always return a `401` error, which looking from the internals of the library, its a parsing error?

<img width="345" alt="screen shot 2018-09-19 at 3 05 16 pm" src="https://user-images.githubusercontent.com/117184/45781712-042e8b00-bc1e-11e8-823f-60d5954db897.png">

Our flow is very similar to the one in this example https://github.com/auth0-samples/auth0-ios-swift-sample/blob/44df131f90c22992885804b09a493ae7c987145e/04-Calling-APIs/Auth0Sample/HomeViewController.swift#L44

Any help would be greatly appreciated.

**Comment by cocojoe** [comment]
Is the *only* change to the SDK?

Please provide the actual code you are executing to perform the authentication and the subsequent call to the profile. Please enable logging so we can see the raw request made to the server and the response.  

Be sure to redact any sensitive information.

**Comment by leopic** [comment]
Hi @cocojoe 

I re-tested this change this morning and its working alright, I manually went through all the releases we had missed to find the breaking point, to no avail.

Thank you very much for your reply, I'll be closing this issue.
