### ISSUE TITLE
"We're sorry, something went wrong when attempting to log in." error 403 Invalid State

### ISSUE THREAD

**Issue by nerocristallo** [auth0/Auth0.swift#241]
I see this error trying to authenticate the user.
"We're sorry, something went wrong when attempting to log in." 

The application is asking the authentication in the following way
```
        Auth0
            .webAuth()
            .scope("openid profile email offline_access")
            .audience("https://api.xxx.xxx")
            .start
```

Debugging the Safary login page when the request is performed 

`Request
:method: POST
:scheme: https
:authority: XXX.eu.auth0.com
:path: /usernamepassword/login
Content-Type: application/json
Accept: /
Host: XXX.eu.auth0.com
Accept-Language: en-us
Accept-Encoding: br, gzip, deflate
Origin: https://XXX.eu.auth0.com
Referer: https://XXX.eu.auth0.com/login?state=IqUcaKz8oL43BPVflsm84gUET1cDrnaN&client=XXXmyclientIDXXX&protocol=oauth2&response_type=code&redirect_uri=xxx.XXX%3A%2F%2FXXX.eu.auth0.com%2Fios%2Fxxx.XXX%2Fcallback&audience=https%3A%2F%2Fapi.XXX.xxx&code_challenge=U89LGQB5BSIi5ilLyQqSTVqjrqYDwn9O700SrC-70tk&code_challenge_method=S256&scope=openid%20profile%20email%20offline_access&auth0Client=xxx
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1
DNT: 1
Connection: keep-alive
Content-Length: 722
Auth0-Client: xxx`

I see the following error response

`{
    "statusCode": 403,
    "description": "Invalid state",
    "name": "AnomalyDetected",
    "code": "access_denied"
}`

Unfortunately I am not able to reproduce it anymore in my debug environment but the problem is still present in the field for some users.
I suspect that it could be related to the iOS 12 updated.

**Comment by nerocristallo** [comment]
The audience is correct but it is not "https://api.xxx.xxx" I prefer to keep it hidden :-)
The Anomaly Detection is on (we are using brute-force protection but not the breached-password protection) and it is set in this way since long time ago but the issue starts to happen just from a week.
We do not see any issue notified on the users account involved this login problem.

**Comment by cocojoe** [comment]
OK then I suggest you get in touch with our great support team who can investigate this further. https://support.auth0.com/

I don't see it as an issue with the Auth0.swift library itself.

**Comment by nerocristallo** [comment]
Could it be related to a wrong "state" value or encoding?

I see that it is randomically generated and then base64 encoded, but I have no idea about how it is used by auth0 during the authentication process. 

Can it be wrong in any way?

**Comment by cocojoe** [comment]
I mean the error does mention `invalid state`, I would say strip it back to basics, create a new application and try one of the sample apps https://auth0.com/docs/quickstart/native/ios-swift

**Comment by cocojoe** [comment]
Closed due to lack of activity
