### ISSUE TITLE
Xamarin equivalent of PKCE authentication 

### ISSUE THREAD

**Issue by cosminonea** [auth0/Auth0.swift#252]
Not really an issue but a question.

I just spent an hour trying to do the PCKE auth flow from a Xamarin app on iOS but can't find a full solution. Is there an equivalent library for Xamarin that can do what this swift library does?

Thanks!

**Comment by cosminonea** [comment]
found my answer

**Comment by cocojoe** [comment]
Care to share your answer? It may help others in the future. Thanks
