### ISSUE TITLE
Contradiction in .gitignore

### ISSUE THREAD

**Issue by kdbertel** [auth0/Auth0.swift#257]
### Description

The `.gitignore` file contains the following lines:

```
Carthage/Checkouts
!Carthage/Build
Carthage/Build
```

This is a contradiction, and I think either `!Carthage/Build` or `Carthage/Build` should be removed to eliminate it, and clarify what's intended.

Also, if the intention is indeed to not check in `Carthage/Checkouts` or `Carthage/Build`, wouldn't it be better to just have the line `Carthage/`?

**Comment by cocojoe** [comment]
Interestingly https://github.com/github/gitignore/blob/master/Swift.gitignore default only excludes Build. However, explicitly this should be:

```
Carthage/Build
Carthage/Checkouts
```

Which could be 

```
Carthage/
```

Certainly not a priority. However, please feel free to raise a PR in the mean time.
