### ISSUE TITLE
Usage of v2 users search engine

### ISSUE THREAD

**Issue by hoang-ei** [auth0/Auth0.swift#258]
Usage of api/v2/users instead of v3 in Pods/Auth0/Users.swift. Please update to v3

It gives me warning in admin web saying:

The User Search v2 engine is deprecated, please use v3 (search_engine=v3) instead.

### Environment

Please provide the following:

- Lock version 2.9
- Podfile
- Xcode version 10.1

**Comment by cocojoe** [comment]
This library is not opinionated about the search engine version used, it will use the Auth0 default.
