### ISSUE TITLE
MFA Challenge 

### ISSUE THREAD

**Issue by Drewpom** [auth0/Auth0.swift#261]
I am trying to implement MFA into my app but there is no API in the current library to initiate a challenge request via the `/challenge` endpoint.

**Comment by cocojoe** [comment]
If you have configured MFA for your `Application` in the [Auth0 Dashboard](https://manage.auth0.com/dashboard/eu/fcauth/applications#) the challenge should automatically happen and you will get an error relating to MFA required and then you need to use the `loginOTP`. 

See https://github.com/auth0/Auth0.swift/pull/189

**Comment by cocojoe** [comment]
Do you still require help with this? Thanks
