### ISSUE TITLE
Expose UserInfo properties to objective-C with Swift 4.X

### ISSUE THREAD

**Issue by mtrip** [auth0/Auth0.swift#262]
### Description

With Xcode 10.2, minimum Swift version is 4.0. When integrating Auth0 in a Objective-C project with Swift 3.0 we used to get access to UserInfo properties but with Swift 4.X we do not anymore. 
Can you add the @objc attribute to the UserInfo properties?

https://auth0.com/docs/quickstart/native/ios-objc/03-user-sessions#default-information

### Environment

- Auth0.swift version: 4.2
- iOS version: 12.2
- Xcode version: 10.2

**Comment by cocojoe** [comment]
ObjC is less of a focus for us now.  However, if you would like to submit a PR I would be able to review this for you. Thanks

**Comment by cocojoe** [comment]
Was added in https://github.com/auth0/Auth0.swift/releases/tag/1.16.1
