### ISSUE TITLE
Xcode 10.2: 'public' modifier is redundant for instance method declared in a public extension

### ISSUE THREAD

**Issue by JARinteractive** [auth0/Auth0.swift#263]
### Description

Xcode 10 and the new Swift compiler version produce new warnings, including:  'public' modifier is redundant for instance method declared in a public extension

### Prerequisites

* [x] Did you check the documentation? [Add a link]
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate Issues or PRs for this issue?

### Environment

- Auth0.swift version: master
- iOS version: N/A
- Xcode version: 10.2

**Comment by cocojoe** [comment]
Warnings fixed in Xcode 10.2 update PR.

**Comment by danchokobo** [comment]
> Warnings fixed in Xcode 10.2 update PR.

what is means  update PR?
