### ISSUE TITLE
Support manual and Carthage --no-build dependency management

### ISSUE THREAD

**Issue by JARinteractive** [auth0/Auth0.swift#266]
### Description

A common method of pulling dependencies into a project is to use `carthage update --no-build` to checkout the dependencies, then letting Xcode manage the building of dependencies. Auth0 fails to build in this scenario due to SimpleKeychain not being built prior to the linker build phase.

See: https://www.mokacoding.com/blog/carthage-no-build/

### Prerequisites

* [x] Did you check the documentation? [Add a link]
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- Auth0.swift version: 1.14.2
- iOS version: N/A
- If using Carthage or CocoaPods, please include your Cartfile or Podfile
```
github "RxSugar/RxSugar" "master"
github "auth0/Auth0.swift"
```
- Xcode version 
10.x

**Comment by cocojoe** [comment]
Sorry, this method is not something we are considering supporting at this stage.
