### ISSUE TITLE
CredentialsManager.hasValid() returns true even if access token has expired and refresh token has been revoked

### ISSUE THREAD

**Issue by rfdearborn** [auth0/Auth0.swift#268]
### Description

I'm using Auth0 on a default database connection (i.e., no social or other connections configured). 

When a user's access token has expired and refresh token has been revoked, `hasValid()` in `CredentialsManager` continues to return `true`. It seems like this comes down to:

`return expiresIn > Date() || credentials.refreshToken != nil`

when there is no `refreshToken` validity check in

```
guard
            let data = self.storage.data(forKey: self.storeKey),
            let credentials = NSKeyedUnarchiver.unarchiveObject(with: data) as? Credentials,
            credentials.accessToken != nil,
            let expiresIn = credentials.expiresIn
            else { return false }
```

I.e., a `refreshToken` can exist but be invalid.

Is this intended behavior? It's not documented and came as a surprise to me.

### Prerequisites

* [x ] Did you check the documentation? (https://github.com/auth0/Auth0.swift/blob/master/Auth0/CredentialsManager.swift)
* [x ] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x ] Are you reporting this to the correct repository?
* [x ] Are there any related or duplicate Issues or PRs for this issue? No

### Environment

Please provide the following:

- Auth0.swift version 1.13
- iOS version 12.1
- If using Carthage or CocoaPods, please include your Cartfile or Podfile
```
target 'Challe'
use_frameworks!
pod 'Auth0', '~> 1.13'
...
```
- Xcode version 10.1

### Reproduction

1. Authenticate user to a native iOS application with refresh tokens enabled
2. Revoke that user's refresh token (either via dashboard or programatically)
3. Wait for access token to expire
4. call `CredentialsManager.hasValid()` and it returns True

**Comment by lbalmaceda** [comment]
@rfdearborn hello! There's no way to check if a refresh token is valid or not other than trying to use it to get a new pair of credentials. So the `hasValid()` logic is still correct. It will be considered valid if access_token is present and not expired OR if the refresh token is present.

**Comment by rfdearborn** [comment]
Fair! I do still think this is worth calling out in the documentation.
