### ISSUE TITLE
Support for Accio/ SwiftPM

### ISSUE THREAD

**Issue by rocklyve** [auth0/Auth0.swift#270]
### Description

Support for [Accio](https://github.com/JamitLabs/Accio)
Since **Accio** supports SwiftPM for iOS, it would be great to support this!

### Prerequisites

* [ ] Remove Objective-C code
* [ ] Support SwiftPM/ Accio with **Package.swift**

### Environment

Please provide the following:

- Auth0.swift version = 5.0
- iOS version = 12
- Xcode version = 10.2

**Comment by rocklyve** [comment]
#271 is the PR for this issue, 

Before granting this PR, please grant the PR [SimpleKeychain/65](https://github.com/auth0/SimpleKeychain/pull/65)

**Comment by cocojoe** [comment]
Not sure why we should support this? I've not heard any demand for this.

**Comment by JackoPlane** [comment]
Xcode 11 now has direct integration with SwiftPM and Github will offer extended support for SwiftPM as of now. I think the direction Apple is pushing people is towards SwiftPM.

**Comment by rocklyve** [comment]
Yeah and accio is made for this time, cause it can handle a Package.swift till SwiftPM is not fully integrated :)

**Comment by cocojoe** [comment]
I agree with @JackoPlane I'm not seeing any demand right now for an interim solution such Accio for this lib. I'm going to close for now.
