### ISSUE TITLE
Request: custom modalPresentationStyle for SFSafariViewController

### ISSUE THREAD

**Issue by colin-chan** [auth0/Auth0.swift#274]
### Description

For UI/UX reasons, we wish to change the default presentation style of the SFSafariViewController. By default it is pushed from the right side, we want it to be presented vertically from the bottom.

Specifically, can you allow custom modification of the 'modalPresentationStyle' property in the created SFSafariViewController in file SafariWebAuth.swift . I would like to change this property to '.overFullScreen' for our use cases.

### Prerequisites

* [x] Did you check the documentation? [Add a link]
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- Auth0.swift version (1.14.2)
- iOS version (11.0)
- If using Carthage or CocoaPods, please include your Cartfile or Podfile
- Xcode version (10.2)

### Reproduction
I'm using the legacy authentication, not the newer SafariAuthenticationSession.
```
 Auth0.webAuth(...).useLegacyAuthentication()....start {...}
```

**Comment by cocojoe** [comment]
Hi @colin-chan this is not something we have any plans to work on. However, if you wish to submit a PR to expose this I would be happy to have a look at it for you.

**Comment by colin-chan** [comment]
Hello, and thanks. I've added a pull request with my changes to allow this.
