### ISSUE TITLE
Can't logout

### ISSUE THREAD

**Issue by dms90** [auth0/Auth0.swift#282]
Can't log out using:

```
        self.credentials = nil
        return self.credentialsManager.clear()
```

As it appears in the official documentation: https://auth0.com/docs/quickstart/native/ios-swift/03-user-sessions#on-logout-clear-the-keychain 

I downloaded the example app and logout is not working. 

It seems that the user is still logged in since login is not asking for user/pwd again.

I tried 

```
        Auth0
            .webAuth()
            .clearSession(federated: true) { [weak self] (sucess) in
                if sucess {
                    self?.credentials = nil
                    self?.credentialsManager.clear()
                }
        }
```

but it shows an alert asking for sign in.

Calling 

```
        if let url = URL(string: "https://myapp.auth0.com/v2/logout") {
            UIApplication.shared.open(url)
        }
```

works but is not the flow I want.

• I'm using Auth0 (1.15.0) via CocoaPods. 
• iOS 12.2 
• Universal Login.

**Comment by cocojoe** [comment]
I agree, the language in that QS is a little unclear. As that is only clearing the credentials. Calling the Logout URL basically clears out the Auth0 session cookie. Also unfortunately as iOS works today it's not the most beautiful experience.

Another option is passing the `prompt=none` as a parameter next time you call WebAuth to force a new login.

**Comment by OrestNazarewycz** [comment]
@cocojoe  I tried forcing prompt the next time i tried to login, but I am still getting logged in as the previous user automatically. 

        webAuth
            .scope("openid offline_token offline_access")
            .parameters(["responseType": "token id_token", "prompt":"none"])
            .start {
                switch $0 {
                case .failure(let error):
                case .success(let credentials):
                }
        }

Is this what you meant or am I not putting the param in the correct spot?

**Comment by dantonyblanco** [comment]
This is happening to us as well and opening safari to do the logout just doesn't work for our flow. 
If this is not in the roadmap to get fixed we will need to swap Auth0 for another Identity Provider.
@cocojoe Did you close this because its something Auth0 will never support?

**Comment by saltukalakus** [comment]
Hi , the parameter would be **prompt=login** instead of **prompt=none** to force the login widget.

**Comment by wildseansy** [comment]
@saltukalakus' answer worked for me
```swift
    Auth0
      .webAuth()
      .scope("openid profile offline_access")
      .parameters(["responseType": "token id_token", "prompt":"login"])
```
