### ISSUE TITLE
Ability to change Dismiss Button Style in SFSafariViewController

### ISSUE THREAD

**Issue by ccannell** [auth0/Auth0.swift#283]
Is it possible to change the [dismissButtonStyle](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/2875838-dismissbuttonstyle) of the [SFSafariViewController](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/) that is being used by [Auth0.webAuth()](https://github.com/auth0/Auth0.swift/blob/master/Auth0/WebAuth.swift)?

**Comment by cocojoe** [comment]
There are no plans to add styling for this at present. However, I'll leave this open to see if more interested in generated.
