### ISSUE TITLE
Sign In With Apple

### ISSUE THREAD

**Issue by ljesus** [auth0/Auth0.swift#285]
### Description

The new Sign In With Apple feature implemented by Auth0, when used on Apple phones, should use the native authentication of iPhone. When using the Auth0.swift sdk with the "apple" connection, the login works as expected however the authentication process takes place in the SafariWebViewController instead of natively. Are there plans to include a native Sign In With Apple?

I use Auth0.swift instead of Lock because I have a customized login page, where I then call methods from the Auth0 SDK.

**Comment by cocojoe** [comment]
Hi @ljesus, yes there will be. We tend to let the betas settle down first.

**Comment by ljesus** [comment]
Hi, are there any updates on this? I noticed you closed the issue. Thanks.

**Comment by cocojoe** [comment]
Will keep this open for visibility, I couldn't give out much detail at the time. So the solution will be inline with previous solutions for Native IdP. You should integrate Sign In With Apple as per Apple's guidance and then you will be able to call an endpoint exchanging the Apple token/code for an Auth0 one.

**Comment by cocojoe** [comment]
You can find the new endpoint in https://github.com/auth0/Auth0.swift/pull/304
This will be released soon. Thanks

**Comment by cocojoe** [comment]
Was released :)
