### ISSUE TITLE
Memory leak once `Auth0.authentication` method is called

### ISSUE THREAD

**Issue by MarcoFilosi** [auth0/Auth0.swift#290]
### Description

There is a memory leak every time we create and keep a new `Authentication` object by calling `Auth0.authentication` static method. 

### Environment

- Auth0.swift version: 1.16.0
- iOS version: 12.4
- CocoaPods version: 1.7.5
- Xcode version: 10.3 (10G8)

### Reproduction

* Create a new Single View App project on XCode
* Add Podfile to the project and install `Auth0` pod (version 1.16.0)
* In the ViewController write this simple code:
```
import UIKit
import Auth0

class ViewController: UIViewController {   
    var authentication: Authentication?

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        authentication = Auth0.authentication(clientId: "****************", domain: "**********")
    }
}
```

* Build project and Profile it (Product -> Profile). 
* You will see a memory leak triggered by calling `Auth0.authentication` method (see screenshot attached here below)

![Screenshot 2019-07-26 at 16 38 43](https://user-images.githubusercontent.com/1218291/61959590-055de080-afc4-11e9-8df9-4c7c27476081.png)

**Comment by cocojoe** [comment]
Thanks for reporting.

**Comment by MarcoFilosi** [comment]
@cocojoe There is a pull request to fix it: #291 
Please review it. Thanks

**Comment by cocojoe** [comment]
Thanks for the PR, this change would be a Breaking Change as it changes the type of Public API object.  In general `structs` are preferred in Swift. 

I'll need to allocate some time to have a look at the instrumentation here. If genuine and not a false positive, 128 Bytes is on the trivial side. However, we should explore further.

**Comment by cocojoe** [comment]
I've been looking into this, isolating down. It doesn't look like we are retaining anything. The call to read the plist is pretty standard stuff.

![Screenshot 2019-08-15 at 12 27 01](https://user-images.githubusercontent.com/928115/63110874-54c07c80-bf84-11e9-942e-34c973d71dcf.png)

**Comment by Widcket** [comment]
Hi @MarcoFilosi, apologies for the delay. I was not able to reproduce this on iOS 13.4.1.

Test environment:
- Xcode 11.5
- iPhone 11 Pro with iOS 13.4.1

<img width="671" alt="Screen Shot 2020-05-26 at 09 11 57" src="https://user-images.githubusercontent.com/5055789/82899383-4353ca00-9f31-11ea-9f60-9324f4ac42e4.png">
