### ISSUE TITLE
Option to have WkWebView for login/registration journey instead of SFSafariViewController

### ISSUE THREAD

**Issue by ck1125** [auth0/Auth0.swift#294]
### Description

I would like the option to kick off the login/registration journey within a WkWebView instead of the SFSafariViewController so that  I can trigger end-to-end automation tests that include my app and Auth0 within Appium.

**Comment by cocojoe** [comment]
`WKWebView` was deprecated in 2017 by OAuth providers. This is not something we will be adding. Thanks.
