### ISSUE TITLE
iOS 13 Beta changes, Xcode 11 Beta and Auth0 Swift SDK.

### ISSUE THREAD

**Issue by CapeFurSeal** [auth0/Auth0.swift#295]
### Description

When calling the webAuth function in iOS 13 nothing happens as the new delegate has not been implemented. Will this be fixed before the iOS 13 release?

```txt
Error:
Failed with Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.}
```

<img width="305" alt="Screenshot 2019-08-17 at 09 21 38" src="https://user-images.githubusercontent.com/928115/63210078-594e7780-c0e1-11e9-9a61-6eddf81104a0.png">

```swift
Auth0
        .authentication(clientId:"", domain:"")
        .webAuth(withConnection:"")
        .start { result in
          switch result {
          case .success(let credentials):
            print("credentials: \(credentials)")
          case .failure(let error):
            print("Failed with \(error)")
          }
      }
```

### Prerequisites

* [x] Did you check the documentation? [Add a link]
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate Issues or PRs for this issue?

**Comment by cocojoe** [comment]
Support will be made for iOS 13. You can have a play with the beta branch in #297 and feedback if you like.

**Comment by CapeFurSeal** [comment]
Thanks @cocojoe . Much appreciated.

**Comment by CapeFurSeal** [comment]
This worked perfectly on iOS 13.1 Public beta 2 with branch #297 .

**Comment by wolfspy** [comment]
We are still experiencing this issue on v1.17.1 using the GM seed of iOS 13.

**Comment by cocojoe** [comment]
All of this is addressed in 17.1 release.

**Comment by Tirth21896** [comment]
I have updated my pods with all new pod release 1.18.0 and it's still giving me "`Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.}`" error.

**Comment by cocojoe** [comment]
I would guess it relates to https://github.com/auth0/Auth0.swift#important-notice

**Comment by Tirth21896** [comment]
My bad when I cleared my build folder and then build it again it worked

**Comment by leojkwan** [comment]
don't know what I did wrong, on iOS 13, Swift 5.0  Xcode 11.1. ran into same issue. reverted back to 1.17.1 and fixed the problem.
