### ISSUE TITLE
Apple sign In

### ISSUE THREAD

**Issue by DostankoHeadspace** [auth0/Auth0.swift#299]
### Description

We want to support sign in with Apple ID for Watch application. While public release is pretty soon and iOS sdk still doesn't support, can you suggest how we can do this now (e.g. using native createUser). May be we can contribute here? 
Is the case that loginSocial method will be updated to support Apple login? 
identityToken/userID generated by Apple instead token and correspondent connection name?

     Auth0
        .authentication(clientId: clientId, domain: "samples.auth0.com")
        .loginSocial(token: identityToken, connection: "apple")
        .start { print($0) }

### Prerequisites

* [ ] Did you check the documentation? [Add a link]
* [ ] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [ ] Are you reporting this to the correct repository?
* [ ] Are there any related or duplicate Issues or PRs for this issue?

### Environment

- Auth0.swift version
- iOS 13, watchOS 6
- Xcode 11

**Comment by ljesus** [comment]
Also interested in this. Opened this issue: https://github.com/auth0/Auth0.swift/issues/285 but they closed it without any real updates.

**Comment by cocojoe** [comment]
See #285 as the original thread.
