### ISSUE TITLE
WebAuth clear session AlertController title uses Sign In instead of Sign Out

### ISSUE THREAD

**Issue by matt** [auth0/Auth0.swift#302]
### Description

When calling `Auth0.webAuth().clearSession(federated: false) { isSuccess in ... }`, the following dialog is presented.

<img width="351" alt="Screen Shot 2019-08-27 at 8 55 11 PM" src="https://user-images.githubusercontent.com/2709/63818053-14121d00-c90d-11e9-9565-25e68f9f4c4f.png">

It would be a preferred user experience if the AlertController title read `"Example App" Wants to Use "example.com" to Sign Out`.

### Prerequisites

* [*] Did you check the documentation? [Add a link]
* [*] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [*] Are you reporting this to the correct repository?
* [*] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

CocoaPods 1.6.1
Auth0 1.17
iOS 13 beta 8 (17A5572a)
Xcode 11.0 beta 6 (11M392r)

### Reproduction

`Auth0.webAuth().clearSession(federated: false) { isSuccess in ... }`

**Comment by cocojoe** [comment]
I would also prefer this. However, the alert is non configurable as far as I am aware.

**Comment by MaxHasADHD** [comment]
Add `.useLegacyAuthentication` to skip the alert. The alert comes from `ASWebAuthenticationSession`
