### ISSUE TITLE
Swift package manager support

### ISSUE THREAD

**Issue by jessemx109** [auth0/Auth0.swift#306]
### Description

Description of the bug or feature request and why it's a problem. Consider including:

Can you please add support for including the framework through swift package manager

**Comment by cocojoe** [comment]
Hi @jessemx109 it's in our backlog to add 👍

**Comment by piercifani** [comment]
Thanks, we also need this!

**Comment by jeffc-dev** [comment]
Also looking forward to SwiftPM support, hopefully sooner rather than later (as Xcode 11 is now out and SwiftPM is the "officially supported" way of handling dependencies).

Thanks!

**Comment by rynecheow** [comment]
Hi @jeffc-dev - Do we have plans to work on this? I can help if there's a plan. Currently I am stuck as SPM is unable to build Objective-C code (SimpleKeychain).

**Comment by jeffc-dev** [comment]
I have no near-term plans (a bit swamped with other work at the moment), but would be interested in testing if someone comes up with something.

**Comment by pedrorgr** [comment]
+1 on looking forward to this

**Comment by ryangittings** [comment]
+1

**Comment by amkomatz** [comment]
+1 We really could use this

**Comment by El-Fitz** [comment]
+1 Really looking forward to this!

**Comment by Widcket** [comment]
Thanks everyone for the input, but we won’t be moving forward with this ATM. SPM still does not support a way to exclude files by platform, and we have some Objective-C files we’d have to create a new target for (or migrate them to Swift and drop support for Swift < 4.2).
We’ll be happy to revisit this once SPM supports excluding files by platform.

**Comment by piercifani** [comment]
I'm sorry @Widcket , but you can exclude files per platform easily on ObjC+SPM like this:

```objc
#if TARGET_OS_IOS
/// Your platform specific classes
#endif
```

You can check it out here https://github.com/theleftbit/BSWInterfaceKit/blob/develop/Sources/BSWInterfaceKitObjC/include/BSWZoomTransition.h#L8

Would this change your mind?

**Comment by Widcket** [comment]
We've considered workarounds for every issue, but we'd need to gate 25+ files, and that's not viable for us.

**Comment by sam-w** [comment]
@Widcket @cocojoe that's a real shame to hear. I'd like to see this reconsidered at some point.

**Comment by CypherPoet** [comment]
Just an idea, but perhaps an issue with some kind of "Help Wanted" tag can be created for this. 

I anticipate that demand for SPM support is only going to grow, and that seems like some nice low-hanging fruit for an aspiring contributor.

**Comment by CypherPoet** [comment]
@Widcket @cocojoe Just an idea, but perhaps an issue with some kind of "Help Wanted" tag can be created for this. 

I anticipate that demand for SPM support is only going to grow, and that seems like some nice low-hanging fruit for an aspiring contributor.

**Comment by powerje** [comment]
> Thanks everyone for the input, but we won’t be moving forward with this ATM. SPM still does not support a way to exclude files by platform, and we have some Objective-C files we’d have to create a new target for (or migrate them to Swift and drop support for Swift < 4.2).

I believe Xcode 11 is now required when submitting apps, so based on the notice in the readme I believe support for Swift < 4.2 is effectively dropped at this point:

```
Behaviour changes in iOS 13 related to Web Authentication require that developers using Xcode 11 with this library must compile using Swift 5.x. This should be the default setting applied when updating, unless it has been manually set. However, we recommend checking that this value is set correctly.
```

I only see 3 ObjC files here now:
https://github.com/auth0/Auth0.swift/tree/master/Auth0

I assume the other files have been migrated from ObjC to Swift since this issue was created.

It looks like both dependencies required by Auth0.swift support SPM now:

https://github.com/auth0/JWTDecode.swift
https://github.com/auth0/SimpleKeychain

So it looks like work is being done to make this happen, but it isn't super clear because this issue is closed. @Widcket is the team looking for contributions to take this over the finish line?

**Comment by Widcket** [comment]
@CypherPoet we'll be happy to review a PR if somebody finds a way to get it done. Just keep in mind we won't accept a PR that uses `#if TARGET_OS_IOS` to gate files.

**Comment by powerje** [comment]
Would changing the file structure work? I think adding subfolders for specific platforms might do the trick?

**Comment by maxchuquimia** [comment]
Currently in the podspec it seems that lists of files are (manually?) maintained and then used as  exclude lists - from memory SPM also supports exclude lists, so couldn't the logic be the same? Just have arrays of files at the top of Package.swift and then exclude them where necessary? _Might look into it if I get the chance..._

**Comment by maxchuquimia** [comment]
Alright, so I have something working: https://github.com/maxchuquimia/Auth0.swift
Essentially what I've built is a script that migrates this repo into an SPM compatible repo - there's a few issues that I've detailed in the ReadMe but I'm sure with a bit of collaboration they can be solved... 

I added it into my project as a test and ran the iOS target - it seems to work!

I see this as a _possible_ temporary solution until Auth0 officially supports the SPM

**Comment by mackoj** [comment]
Hi,

RevenutCat did a great job for working with their ObjC code [RevenueCat/Package.swift](https://github.com/RevenueCat/purchases-ios/blob/develop/Package.swift).

Swift 5.3 will add a lot of feature regarding SPM maybe it's time to revisit this issue.

https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md
https://github.com/apple/swift-evolution/blob/master/proposals/0278-package-manager-localized-resources.md
https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md
https://github.com/apple/swift-evolution/blob/master/proposals/0273-swiftpm-conditional-target-dependencies.md

**Comment by jeremygrenier** [comment]
I couldn't agree more with @mackoj. More and more people are probably going to move to SPM with Swift 5.3.

Do you think it would be appropriate to reopen this issue?

**Comment by daniloc** [comment]
Just wanted to add a +1 to this issue. Adding Cocoapods or Carthage to a new project that's otherwise working great with SPM adds some serious overhead. They're just such clunky solutions by comparison.

**Comment by jasdev** [comment]
+1 here too, SPM support would help us a ton

**Comment by Widcket** [comment]
We'll keep this open and pinned for future reference.

**Comment by CapeFurSeal** [comment]
I am migrating my code base from pods to package manager and this is the only repo that does not have support...

**Comment by yanniks** [comment]
I would not consider binary distribution a good option, especially considering this: https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/20
I understand that guarding all files might not be the best option. However, Auth0.swift is also for us the last library that does not support SPM. Also, scoping is at least partially possible using
```
.when(platforms: .some([.iOS, .tvOS]))
```
as seen in [Firebase](https://github.com/firebase/firebase-ios-sdk).

**Comment by scottyelvington** [comment]
I have to second @CapeFurSeal, SPM plays much more nicely with LLDB and the toolchain than Carthage which is why we're fully moving away from Carthage to SPM as our official dependency manager. To me this seems inevitable. SPM is already industry grade and will also be industry standard in the near-term future. It can't be ignored forever. Exclude lists in the Package description should get the job done with some project restructuring. When are we going to see support for SPM?

**Comment by scottyelvington** [comment]
Also, not to pile on or belabor the point or anything. But this particular dependency doesn't compile in Carthage in Xcode 12. I don't know how long I can hold off upgrading to Xcode 12 just to support a single dependency. We have iOS 14 related updates we absolutely need to get into production asap.

**Comment by Widcket** [comment]
@scottyelvington https://github.com/auth0/Auth0.swift/issues/397#issuecomment-695053734

<img width="905" alt="Screen Shot 2020-10-01 at 16 34 13" src="https://user-images.githubusercontent.com/5055789/94854868-f95d8200-0403-11eb-8cbd-c84d243328c7.png">

**Comment by Widcket** [comment]
Also check out https://github.com/auth0/JWTDecode.swift/issues/113.

**Comment by scottyelvington** [comment]
@Widcket Carthage is pretty clear that they're not addressing the problem in 0.36.0. Supporting SPM seems like the way forward.
<img width="653" alt="Screen Shot 2020-10-01 at 4 22 49 PM" src="https://user-images.githubusercontent.com/9815381/94872803-6cfe8f80-0402-11eb-9dc2-f0429ca4c755.png">

**Comment by cocojoe** [comment]
A little update, SPM is something we will be working on this quarter.  One challenge with these libraries is they are not minimal latest Swift only libs so there isn't a quick happy path to SPM support. Not an excuse, just an observation.  It has taken a while for the maturity of SPM to improve. I agree that with Xcode 12 and improvements to SPM this is the right time. 

However, we also want to ensure Pods and Carthage are still supported. As pointed out that relies on 3rd party tooling also updating. In the case of Carthage, it will run tests and if 3rd party test library dependencies are not yet ready for Xcode 12 then the tests will fail and the Carthage process will fail.

Would be great if a few of you would like to help us test the SPM compatibility? Once we're at that stage. 

Thanks

**Comment by scottyelvington** [comment]
Thank you for the update @cocojoe, I'm happy to help you test SPM if that helps move the ball down the field so to speak.

> Would be great if a few of you would like to help us test the SPM compatibility? Once we're at that stage.

**Comment by heyzooi** [comment]
+1

**Comment by Widcket** [comment]
Hi everyone, we now have an implementation up in the `feature/spm-support` branch. Please try it out, any feedback is appreciated. The goal is to have a new release out by the end of the week.
Please check out [the PR](https://github.com/auth0/Auth0.swift/tree/feature/spm-support) for more details.

**Comment by Widcket** [comment]
This is now out in [1.30.0](https://github.com/auth0/Auth0.swift/releases/tag/1.30.0)!
