### ISSUE TITLE
Include reason why removing Auth0 session did not succeed to improve client-side error handling.

### ISSUE THREAD

**Issue by LinkAndreas** [auth0/Auth0.swift#314]
## Improve client-side error handling when removing Auth0 session

Affected method in `WebAuth.swift`:

`func clearSession(federated: Bool, callback: @escaping (Bool) -> Void)`

### Problem:

Currently, when removing the Auth0- and/or Identity Provider session, a boolean is used to inform the client whether the operation succeeded or failed. Hence, client-wise error handling capabilities are limited, since the client only knows if an error occurred, but not what type of error occurred. Being able to distinguish the types of errors that may occur during an **ASWebAuthenticationSession** or **SFAuthenticationSession** allows deciding whether an alert should be shown to the user or not. For instance, during an ASWebAuthentication- or SFAuthenticationSession users can share existing login information. Hence, the system requests the user's consent to access his login information. If the user decides to not grant permission, an the authentication session returns with either an **ASWebAuthenticationSessionError.canceledLogin** or **SFAuthenticationError.canceledLogin** error. In this case, it may be desired to handle the error silently client-wise.

### Proposed Solution:
Instead of only returning a boolean, a result (`Result<Void>`) is returned including the error if one occurred:

`func clearSession(federated: Bool, callback: @escaping (Result<Void>) -> Void)`

This allows clients to identify the reason why the operation did not succeed and to include dedicated error handling.

![dialog](https://user-images.githubusercontent.com/2820215/66543936-07512d80-eb37-11e9-9c63-248670572ad3.png)

**Comment by cocojoe** [comment]
I believe when this was added it was only Safari based Auth available at the time. As you pointed out there is the additional outcome of cancellation during the permission dialog. 

The BOOL result is based upon the URL being loaded in the browser, so failure around this scenario should only be an issue if Auth0 itself is down or internet connectivity issues.

Any change to the Public API is breaking and would require a new major release of the library to support it, I don't think it would be justified in this case.
