### ISSUE TITLE
Auth0.Result masks Swift 5 Result type

### ISSUE THREAD

**Issue by spr** [auth0/Auth0.swift#317]
### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

If you `import Auth0` and try to use the [Result](https://developer.apple.com/documentation/swift/result) type, the Auth0.Result enum wins out. Since these have different type definitions, they aren't perfectly swappable. This requires you to explicitly specify the Swift version.

For example:
```
func performRequest(completion: @escaping (Result<String,CustomNetworkError>))
```

Generates a compiler error of "Generic type 'Result' specialized with too many type parameters (got 2, but expected 1)" and "1. Generic type 'Result' declared here (Auth0.Result)".

Instead you have to:
```
func performRequest(completion: @escaping (Swift.Result<String,CustomNetworkError>))
```

Certainly easy to workaround, but I expect many devs will not realize how to call out to the default Swift version.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

Any code using `Result` and the Auth0 module:
```
import Auth0

var test: Result<String,Error>?
```

Will fail.

### Environment

> Please provide the following:

- **Version of this library used:**
"auth0/Auth0.swift" "1.17.1"
- **Version of the platform or framework used, if applicable:**
Xcode 11, Swift 5.1, iOS 12.4 as minimum target.
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by joshcanhelp** [comment]
@spr - We appreciate the thorough report here! It sounds like this might need to be renamed, which sounds like it might be a breaking change. Can you think of something we could do to remedy this without breakage?

In the meantime, I've assigned this to the maintainers here to take a look.

**Comment by spr** [comment]
I can't think of a way to make it work that doesn't contain some chance of breaking something downstream. If people are only using the data type from the Auth0 call, and never specifying the type, the type inference system will handle a name change automatically. But you never know what people are doing, so that's not safe.

The one nice thing is since it is a type, it'll break on compile, and not at runtime.

It might just be a situation where adding something in the help docs or on here will get people by until there's a reason to make a breaking change.

**Comment by cocojoe** [comment]
@Widcket can you evaluate this please for adding to docs. Thx

**Comment by Widcket** [comment]
@spr thanks for your contribution.
