### ISSUE TITLE
EXC_BAD_ACCESS on [NSError description] from returned error

### ISSUE THREAD

**Issue by Ethan-VisualVocal** [auth0/Auth0.swift#329]
### Description

When requesting `[NSError description]` using Obj-C on an NSError returned from the WebAuth start method, it crashes the app with EXC_BAD_ACCESS.  

Looking at the call-stack... It seems like `[NSError description]` ultimately leads to Swift's "_SwiftDeferredNSDictionary.enumerateKeysAndObjects" is being called in an infinite loop.

### Reproduction

1. Run the sample: https://github.com/auth0-samples/auth0-ios-objc-sample (Optionally update the podfile to use Auth0 library 1.19.3)
2. Press "Sign In"
3. Press "Cancel"
4. EXC_BAD_ACCESS crash: 
![image](https://user-images.githubusercontent.com/18012510/70083883-1cd85600-15c2-11ea-9fc1-da97ce18bbae.png)

- Does not repro when using Swift to retrieve the description.
- Does not repro when using `[NSError localizedDescription]` 

### Environment

- Auth0.swift library 1.19.3 and 1.18
- macOS 10.14.6 (18G1012)
- Xcode 11.2.1 (11B500)
- Simulator: iOS 13.2.2 (17B102)
- iPhone 6: iOS 12.4.2 (16G114)
- iPhone 8: iOS 13.2.3 (17B111)

**Comment by cocojoe** [comment]
Thanks for reporting cc @Widcket

**Comment by Widcket** [comment]
@Ethan-VisualVocal, please see https://github.com/auth0-samples/auth0-ios-objc-sample/commit/0d9b19e77f2936890636b2479e64c6afe29c883e for a workaround. Thanks for reporting.
