### ISSUE TITLE
Auth0 1.20.0

### ISSUE THREAD

**Issue by CapeFurSeal** [auth0/Auth0.swift#332]
### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Prerequisites

* [x] Did you check the documentation? Yes
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)? Yes
* [x] Are you reporting this to the correct repository? Yes
* [x] Are there any related or duplicate Issues or PRs for this issue? No

### Environment

Please provide the following:

- Auth0.swift version - Auth0 1.20.0
- iOS version - iOS 13.2
- Xcode version 11.2.1

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Start Authentication for Auth0 and app crashes using this code:
```
Auth0
    .authentication(clientId:Auth0Constants.Credentials.clientId,
                    domain:Auth0Constants.Credentials.domain)
      .webAuth(withConnection:connection)
      .audience(Auth0Constants.UserInfo.userInfo)
      .start { result in
        switch result {
        case .success(let credentials):
          self.credentials = credentials
          if self.credentialsManager.store(credentials: credentials) == true {
            success(credentials)
          }
        case .failure(let error):
          failure(error)
        }
    }
```

**Comment by Widcket** [comment]
Hi @CapeFurSeal, what is the connection you're using? And what is the message that shows up in Xcode when the app crashes?

**Comment by CapeFurSeal** [comment]
> Hi @CapeFurSeal, what is the connection you're using? And what is the message that shows up in Xcode when the app crashes?

@Widcket  Here is my connection code. I will get the crash information and post it here.

` internal func signInWithSso(connection:String,
                              success: @escaping (Credentials?) -> (),
                              failure: @escaping (Error?) -> ()) {
    self.setAuth0Authentication()
      .webAuth(withConnection:connection)
      .audience(Auth0Constants.UserInfo.userInfo)
      .start { result in
        switch result {
        case .success(let credentials):
          self.credentials = credentials
          if self.credentialsManager.store(credentials: credentials) == true {
            success(credentials)
          }
        case .failure(let error):
          failure(error)
        }
    }
  }`

**Comment by CapeFurSeal** [comment]
@Widcket  It seems to be a memory issue... 
`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`

**Comment by Widcket** [comment]
@CapeFurSeal can you tell by the stack trace if the crash is happening in the result callback or before (SDK code)?

**Comment by CapeFurSeal** [comment]
> @CapeFurSeal can you tell by the stack trace if the crash is happening in the result callback or before (SDK code)?

@Widcket 

The crash is happening in the SDK, but I cannot see where exactly... I am pretty sure it's not my app because not matter where I place the code in the screenshot, it gives the same crash. I removed the whole connection id from the code in the screenshot.

<img width="1030" alt="Screen Shot 2020-01-15 at 9 25 17 PM" src="https://user-images.githubusercontent.com/2445057/72464336-bc9e1c00-37dd-11ea-80c2-d94087174e9b.png">

**Comment by cocojoe** [comment]
@CapeFurSeal you mentioned it only crashes on the latest version of the library, what version didn't present an issue for you?

I stripped this back and performed a similar test with no problems, would advise you to test with literal values and not constants to ensure there are no internal access issues.

```swift
Auth0.authentication()
            .webAuth(withConnection: "google-oauth2")
            .audience("https://test-api.com/api")
            .logging(enabled: true)
            .start { print($0) }
```

**Comment by CapeFurSeal** [comment]
@cocojoe  I never had any issues with '1.19.3'.

**Comment by CapeFurSeal** [comment]
@cocojoe I tried exactly this code and it crashes no matter where I place it inside of my app.

```
Auth0.authentication()
    .webAuth(withConnection: "google-oauth2")
    .audience("https://test-api.com/api")
    .logging(enabled: true)
    .start { print($0) }
```
<img width="1046" alt="Screen Shot 2020-01-17 at 8 56 04 PM" src="https://user-images.githubusercontent.com/2445057/72638274-ca81a780-396b-11ea-8b01-559df9490e7c.png">

**Comment by cocojoe** [comment]
@CapeFurSeal we are unable to reproduce, please can you provide a bare-bones minimal sample project that reproduces the error using the latest release.

Thanks

**Comment by CapeFurSeal** [comment]
@cocojoe  Thanks. I made a sample project and the code worked. I am not sure what the issue was. I have the new version working now. I removed the Auth0 pod completely from the project and installed it again and everything seems to work now. Thank you for the assistance and apologies for the inconvenience caused.
