### ISSUE TITLE
Carthage: watchOS missing shared scheme.

### ISSUE THREAD

**Issue by cswelin** [auth0/Auth0.swift#334]
### Description

According to the main README.md Auth0 supports watchOS 2.0+, however, Carthage is missing the shared build scheme, which produces the following output when trying to target watchOS:

> Dependency "Auth0.swift" has no shared framework schemes for any of the platforms: watchOS

As seen at the following link the shared schema isn't present: https://github.com/auth0/Auth0.swift/tree/master/Auth0.xcodeproj/xcshareddata/xcschemes 

### Reproduction

> carthage bootstrap Auth0.swift --use-ssh --platform watchOS

### Environment

- **Version of this library used:** 1.20.0
- **Version of the platform or framework used, if applicable:** watchOS 6
- **Other modules/plugins/libraries that might be involved:**  Carthage 0.34.0

**Comment by Widcket** [comment]
@cswelin thanks for the report.
