### ISSUE TITLE
Refresh flow should allow parameters like Auth0.webAuth()

### ISSUE THREAD

**Issue by xparabolax** [auth0/Auth0.swift#335]
### Describe the problem you'd like to have solved

My current flow for authentication includes using Auth0 to generate tokens with WebAuth. I am able to attach parameters to the call so that our Auth0 custom rules can run (appending some information that is based on the parameters to the tokens). This works fine. However, when the refresh flow is called due to token expiry, I receive an error since the Auth0 custom rules are expecting that information.

### Describe the ideal solution

It would be fantastic if `CredentialsManager.credentials` had a way to store parameters to be used on any refresh flows like: 
```
import Auth0

let credentialsManager = CredentialsManager(authentication: Auth0.authentication())
credentialsManager.refreshParameters = ["some_custom_stuff": "some_custom_value"]

# when the request is generated for refresh tokens, the payload body should include the parameters
```

## Alternatives and current work-arounds

We have explored modifying the Auth0 rules to pass through these custom claims from the old tokens to the new ones, but they will take some effort. Right now, I have hacked some code to make this work temporarily on the Auth0 pod, but it needs to be much cleaner.

If there is an easier way to do what I'm attempting or I should be using a different method, I am all ears.

**Comment by Widcket** [comment]
cc @cocojoe

**Comment by Widcket** [comment]
@xparabolax thanks for the report. Can you provide us with more details so we can better understand your use case?

**Comment by xparabolax** [comment]
Hi @Widcket!

In our Auth0 Custom Rules, we are modifying the token and adding a custom claim that the backend needs. This custom claim is based off of a parameter that we send from the client side (essentially, it's an environment selection so that the tokens are further enriched with user ID info). This works fine on the first authentication when we use `Auth0.webAuth()` as we are able to call it with `.parameters` and add them to the query string.

However, when we attempt to trade in the refresh token, we cannot supply other parameters across in the same way. We are locked into the payload 
```
var payload: [String: Any] = [
    "refresh_token": refreshToken,
    "grant_type": "refresh_token",
    "client_id": self.clientId
]
payload["scope"] = scope
```

and cannot supplement it or the querystring. We should be able to provide the same types of information to the refresh call as the initial authorization call.

**Comment by Widcket** [comment]
@xparabolax thanks for the additional details. Looks like [storing the parameter](https://auth0.com/docs/users/concepts/overview-user-metadata) in `app_metadata` may solve your problem. Please check out the [related QuickStart sections](https://auth0.com/docs/quickstart/native/ios-swift/03-user-sessions#managing-metadata) as well.

**Comment by Widcket** [comment]
Going to close this one. If you need further guidance, please ping.
