### ISSUE TITLE
Provide ability to inject headers onto auth service requests

### ISSUE THREAD

**Issue by danielphillips** [auth0/Auth0.swift#339]
### Describe the problem you'd like to have solved

We need to be able to send a mandatory header to our proxy API for Auth0 via Auth0 SDK.

### Describe the ideal solution

The ideal solution we came up with was to provide the Auth0 an optional headers provider dependancy. The app can provide one or not, but if it does provide one then the SDK would take the headers defined in that header providers implementation and add them to any requests created in the SDK.

I have already implemented this in my own way on a fork of your repository, but I would be very interested to hear of a better solution. 

## Alternatives and current work-arounds

Apps could intercept traffic via the url session protocols and append headers from outside of the SDK. But it would be unfortunate to need to intercept all traffic and sniff out the requests we cared about.

**Comment by Widcket** [comment]
Hi @danielphillips can you please provide more details on your use case?

**Comment by Widcket** [comment]
Going to close this issue. Please ping if this is still something you need.

**Comment by MoridinBG** [comment]
Hi
We have a similar requirement. In our case we need to provide a x-device-id header in the renew call.
Ideally, we would be able to add headers to the Request entity. Right now the only publicly exposed property or function is start.

**Comment by cocojoe** [comment]
@danielphillips did you try passing in your own configured instance of `URLSession`

see https://github.com/auth0/Auth0.swift/blob/master/Auth0/Auth0.swift#L38
