### ISSUE TITLE
Better use of iPad screen for login

### ISSUE THREAD

**Issue by mahboud** [auth0/Auth0.swift#356]
### Description

I’m using the Auth0.swift library. My app is iPad only. How do I show the login window in a more suitably sized manner, rather than the iPhone sized version? Since the app is often used in landscape mode, the login screen has elements below the scroll. My users get confused when they can’t see the buttons at the bottom of the page, and they don’t realize that they can scroll.

I'd prefer to show a screen sized for the iPad's larger real-estate than be confined within the smalleriPhone sized screen.

### Reproduction

Put up the Auth0 login screen on an iPad, using the HybridAuth.swift and Auth0.swift library.

### Environment

iPad iOS12 and 13
Auth0 1.19.3

**Comment by Widcket** [comment]
Hi @mahboud, can you please share a screenshot?

**Comment by mahboud** [comment]
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/1689095/75586582-99e06380-5a29-11ea-87f9-7ecdfba3434c.png">

**Comment by Widcket** [comment]
Hi @mahboud, unfortunately there's nothing we can do about the popup size as that popup is created and handled by [AuthenticationServices](https://developer.apple.com/documentation/authenticationservices). But we're discussing internally adding [tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) to the buttons, so the keyboard arrows signal that are further elements down the page. Will update when we reach a decision.

**Comment by mahboud** [comment]
Thank you.

**Comment by Widcket** [comment]
@mahboud, we added this to our backlog. Thanks for your report!

**Comment by natelaff** [comment]
Has this been addressed yet? I'm still using the universal login instead of the new because of this issue.
