### ISSUE TITLE
swift server side compatibility

### ISSUE THREAD

**Issue by gurugeek** [auth0/Auth0.swift#359]
It would be nice to be able to use Auth0 on Swift Server side too!
May be is just a matter of creating the package (spm)

https://github.com/auth0/Auth0.swift.git @ 1.22.1: error: https://github.com/auth0/Auth0.swift.git has no Package.swift manifest for version 1.22.1`

**Comment by Widcket** [comment]
Hi @gurugeek, [we've considered](https://github.com/auth0/Auth0.swift/issues/306#issuecomment-588203889) adding support for SPM but won't be doing it until it supports excluding files by platform.
