### ISSUE TITLE
Stack changing is not working [ very difficult ]

### ISSUE THREAD

**Issue by ijknm** [auth0/Auth0.swift#363]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by ijknm** [comment]
We have multiple stack For Example:
Dev-Stack  
QA-Stack
SQA-Stack
Production-Stack

I want switch each one of stack in the application dropdown, But Auth0.plist file is not supporting:
Run time change configuration not allowed ,
Can we have any solution for this:

Now we are releasing each stack each build, But it's very hard do that.
We want change the stack depends on user select at run time.
 
Note : each stack has different YOUR_CLIENT_ID and YOUR_DOMAIN

**Comment by Widcket** [comment]
Hi @ijknm! You can use the SDK in different environments by passing the Client ID and Domain programmatically, like so:
```swift
Auth0.webAuth(clientId: "client-id", domain: "some-tenant.auth0.com")
```
