### ISSUE TITLE
iOS Simulator - Storage saving is cleared every time

### ISSUE THREAD

**Issue by JMCPH** [auth0/Auth0.swift#368]
#145 **Auth0Storage - Access Token is cleared on every run.**

The access token is cleared every time the app is run on the iOS simulator using Xcode 11.4
It is working perfectly on device, but quite annoying bug to encounter all the time while developing. 

### Reproduction
Run the app
Login using e-mail
Run the app using Xcode
Storage is empty.

### Environment
- **Version of this library used: 1.22.1 **
- **Other relevant versions (language, server software, OS, browser): iOS **

**Comment by Widcket** [comment]
Hi @JMCPH thanks for the report. We're tracking this issue here: https://github.com/auth0/SimpleKeychain/issues/90
