### ISSUE TITLE
Credentials.expiresIn is nil even when present in token

### ISSUE THREAD

**Issue by waterskier2007** [auth0/Auth0.swift#374]
### Description

The initializer for Credentials is failing to parse the `expires_in` value properly, resulting in a nil value.

### Reproduction

I am running on the simulator with webAuth

```
Auth0
            .webAuth()
            .redirectURL(<redacted>)
            .audience(SessionStore.audience)
            .scope("openid profile offline_access read:media")
            .start {
                switch $0 {
                case .failure(let error):
                    // Handle the error
                    print("Error: \(error)")
                case .success(let credentials):
                    // Do something with credentials e.g.: save them.
                    // Auth0 will automatically dismiss the login page
                    self.completeLogin(withCredentials: credentials)
                }
        }
```

I have stepped through the initializer in the Auth0 code and included a series of screen captures showing the odd behavior. The expires_in key is set and is being decoded as an int, but for some reason the creating of the date value is resulting in nil. I cannot for the life of me figure out why.
![Screen Shot 2020-03-31 at 10 42 28 PM](https://user-images.githubusercontent.com/2089840/78094064-9bdb7080-73a1-11ea-8e85-2fb1a4bf7dc8.png)

![Screen Shot 2020-03-31 at 10 42 46 PM](https://user-images.githubusercontent.com/2089840/78093922-4606c880-73a1-11ea-83b3-da878aeed378.png)
![Screen Shot 2020-03-31 at 10 44 55 PM](https://user-images.githubusercontent.com/2089840/78093923-469f5f00-73a1-11ea-9728-6592d912b98c.png)
### Environment

library version 1.23
iOS simulator on iOS 13.4
swift 5.2
Xcode 11.4

**Comment by Widcket** [comment]
Hi @waterskier2007, I wasn't able to reproduce:

<img width="433" alt="Screen Shot 2020-04-01 at 05 42 47" src="https://user-images.githubusercontent.com/5055789/78117142-a87cba80-73db-11ea-8efd-0cf20f6f47f4.png">

Also, there are [unit tests](https://github.com/auth0/Auth0.swift/blob/be7d820ae41715f1e392739ec67aa54f5badc94a/Auth0Tests/CredentialsSpec.swift#L70-L98) covering that.

**Comment by waterskier2007** [comment]
Ok, thank you for checking. It was driving me crazy, but I guess I have some more digging to do.
