### ISSUE TITLE
Feature request: Universal Login for MacOS

### ISSUE THREAD

**Issue by MichaelHudgins** [auth0/Auth0.swift#375]
### Describe the problem you'd like to have solved

> The ability to use universal login with MacOS applications

### Describe the ideal solution

> The offical cocoa pod located at [https://cocoapods.org/pods/Auth0] to support universal login for MacOS

### Additional context

> As a developer implementing Auth0 into my web, windows, macos, and ios applications it would be most desireable if universal login could be used for all logins.  After looking through documentation it appears MacOS is not a supported platform for universal login.

**Comment by cocojoe** [comment]
@darkyen could be your time to shine 😄

**Comment by Widcket** [comment]
Hi @MichaelHudgins, the implementation is now up in the `macos-web-auth/implementation` branch. Can you please try it out?

**Comment by MichaelHudgins** [comment]
Thanks for the feature, I’ll have a good chance to integrate and test this out on Monday.

**Comment by MichaelHudgins** [comment]
@Widcket I got a chance to test out the branch this morning and everything is looking good.  I was able to get the test app working with my credentials returning back all tokens as expected.  Thanks for the hard work!  I saw the unit tests are targeting 10.12, is this the version that the webauth flow is expected to target?

**Comment by Widcket** [comment]
@MichaelHudgins great! The webauth flow targets [macOS 10.15+](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) (Catalina).

**Comment by MichaelHudgins** [comment]
@Widcket a question on handling older operating systems, would a custom app scheme be a viable alternative `ASWebAuthenticationSession` ?  I realize there is the possibility that a malicious actor could attempt to register the same scheme but in that case I believe PKCE should prevent a compromised redirect from being used.  

I have the option of splitting the ui for old users and new users but unfortunately 10.15 has not had as rapid adoption in our industry and older macOS needs support.

**Comment by Widcket** [comment]
@MichaelHudgins unfortunately we do not have plans for supporting older versions of macOS.
