### ISSUE TITLE
Unable to build since xcode 11.3.1 release

### ISSUE THREAD

**Issue by DrLuthor** [auth0/Auth0.swift#380]
### Description
Unable to build Auth0 using Carthage since update to Xcode 11.3.1

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Environment
- Auth0.swift version : 1.23.0
- iOS version : 11.0

Cartfile
```
github "LeoNatan/LNPopupController"
github "auth0/SimpleKeychain" "0.9.0"
github "kishikawakatsumi/KeychainAccess"
github "auth0/Lock.iOS-OSX" ~> 2.0
github "auth0/Auth0.swift" ~> 1.22
github "auth0/JWTDecode.swift" ~> 2.1
```

- Xcode version : 11.4.1

### Reproduction
Tried: 
>carthage update --platform iOS
> carthage update --platform iOS --no-use-binaries
> rm -rf ~/Library/Caches/org.carthage.CarthageKit
> switch iOS version to current last one
> switch to legacy buil system

![Capture d’écran 2020-04-27 à 21 09 40](https://user-images.githubusercontent.com/1106909/80411323-4e80ef00-88cc-11ea-9e49-800478dacbcb.jpg)

**Comment by Widcket** [comment]
Hi @DrLuthor, there's no need for explicit entries in the `Cartfile` for `SimpleKeychain` and `JWTDecode.swift`, as they're dependencies of `Auth0.swift`. Can you please try removing them or just updating them to the latest versions?

**Comment by DrLuthor** [comment]
I did work. Thanks for the fast reply!
