### ISSUE TITLE
v1.24.0 regressions - methods missing - WEB_AUTH_PLATFORM not defined

### ISSUE THREAD

**Issue by ejensen** [auth0/Auth0.swift#383]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

v1.24.0 (in PR #381) introduced a number `#if WEB_AUTH_PLATFORM` conditions around existing API. The value of `WEB_AUTH_PLATFORM` isn't defined in the Podspec. So all the code the `#if WEB_AUTH_PLATFORM` condition wraps is not available.

This is causing compile errors in integrations with the v1.24.0 SDK. Including https://github.com/auth0/Lock.swift:

> Auth0OAuth2Interactor.swift:49:14: Value of type 'Authentication' has no member 'webAuth'

### Reproduction

1. Use the v1.24.0 SDK using CocoaPods
2. Attempt to reference `Auth0.webAuth()`

### Environment

- **Version of this library used:** v1.24.0

**Comment by cocojoe** [comment]
Thanks for reporting @ejensen can you supply a little more information. Want to check what version of CocoaPods you're using and also which platform you're building for.

**Comment by Widcket** [comment]
Hi @ejensen, I've just reproduced this and created [a PR](https://github.com/auth0/Auth0.swift/pull/384) with the fix. Strangely this doesn't got caught by `pod lib lint` nor by manual testing with an app that has `Auth0` as a direct dependency instead of `Lock`.

**Comment by Widcket** [comment]
In fact, in a `Podfile` with the line `pod 'Auth0', '~> 1.24'` it compiles fine, but if you replace it with `pod 'Lock', '~> 2.17'` you get the error described. Will investigate more to find out why.

**Comment by Widcket** [comment]
The fix is out in [v1.24.1](https://github.com/auth0/Auth0.swift/releases/tag/1.24.1). Thanks @ejensen!

**Comment by dilames** [comment]
This issue is reproducible again with CocoaPods and lib version 1.36.1 or 1.36.0.
While using 1.24.1 resolves this issue. Please, @Widcket have a look.

- Xcode: 13.0
- Deployment Target: iOS 13.0
- macOS BigSur: 11.6

**Comment by Widcket** [comment]
@dilames I just tried building the latest releases of Auth0.swift and Lock.swift with Cocoapods in Xcode 13, and it succeeds:

<img width="1041" alt="Screen Shot 2021-09-30 at 22 25 20" src="https://user-images.githubusercontent.com/5055789/135551685-d936d8b1-5a69-40eb-8c63-23fe81690d46.png">
