### ISSUE TITLE
[Question] Login with social connection and mfa required, why it is not returning code ?

### ISSUE THREAD

**Issue by amadeu01** [auth0/Auth0.swift#387]
https://github.com/auth0/Auth0.swift/blob/9b3eb5206f62721e3ecd45837e2c7a46e57e9cd4/Auth0/OAuth2Grant.swift#L131-L134

I'm doing basically a web auth flow. 

```
self.authClient
            .webAuth(withConnection: social.rawValue)
            .parameters(authParameters)
            .scope(authScope)
            .start { [weak self] in self?.handleAuthentication(result: $0) }
```

**Obs:** `social` is basically an enum with the name of the connection.

It shows and goes through the social login, normally! However, when it comes back with the response, we got this error:

```
▿ 3 elements
  ▿ 0 : 2 elements
    - key : "description"
    - value : "No code found in parameters [\"scope\": \"openid offline_access\", \"token_type\": \"Bearer\", \"access_token\": \"....\", \"expires_in\": \"7200\", \"state\": \"-...-\"]"
  ▿ 1 : 2 elements
    - key : "statusCode"
    - value : 0
  ▿ 2 : 2 elements
    - key : "code"
    - value : "a0.sdk.internal_error.plain"
```

Any idea of what I might be doing wrong?

**Comment by Widcket** [comment]
Hi @amadeu01, what are you putting on `authParameters `? Also, are you running any [Rule](https://auth0.com/docs/rules)?

**Comment by amadeu01** [comment]
@Widcket I'm using some rules, I was passing a value to be used in the rules. I found that some cache issue was blocking me from the behaviour I was expecting.

What is the right way of cleaning the web flow cache after the auth0 social login has ended? Is it possible to use the ephemeral session-like behaviour for iOS 11+ ? I know that we could use that for 13+. But, is any recommended way of using an ephemeral session with auth0 SDK?

**Comment by Widcket** [comment]
@amadeu01 when you use SSO, Auth0 places a cookie in the system browser's shared cookie jar. To avoid that (and disable SSO), you can use `SFSafariViewController` via the `useLegacyAuthentication()` method (which we do not recommend, as it does not follow current Apple guidance). Also, we're [implementing an option](https://github.com/auth0/Auth0.swift/pull/388) to allow the use of `prefersEphemeralWebBrowserSession` with [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession), which is the Apple-recommended way of performing Web Authentication.
