### ISSUE TITLE
Incorrect argument labels in call (have 'appleAuthorizationCode:fullName:'

### ISSUE THREAD

**Issue by user1man** [auth0/Auth0.swift#393]
Bug with Sign in with apple, can't use your guide. Don't work save data to credentials
[https://auth0.com/docs/quickstart/native/ios-swift-siwa](https://auth0.com/docs/quickstart/native/ios-swift-siwa)
I tried using other versions of the library, but it didn't help
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
131:23: Incorrect argument labels in call (have 'appleAuthorizationCode:fullName:', expected 'withOTP:mfaToken:')
> - Application settings (redact/remove sensitive information)
> - Screenshot
[Error screen](https://prnt.sc/sttvwc)
### Environment

> Please provide the following:

- **Version of this library used: >Using Auth0 (1.21.0)**
- **Version of the platform or framework used, if applicable: Version 11.3.1 (11C504) iOS 13+**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by Widcket** [comment]
Hi @user1man apologies for the delay. Can you please add reproduction steps?

**Comment by ejensen** [comment]
@user1man the native login methods were renamed in [v1.23.0](https://github.com/auth0/Auth0.swift/releases/tag/1.23.0) and above. In the older v1.21.0 version you are using, the Sign in with Apple method was named `tokenExchange(withAppleAuthorizationCode:fullName:)`

**Comment by Widcket** [comment]
Thanks @ejensen!

**Comment by user1man** [comment]
It works on 1.25 too. So you also need to fix docs on docs.auth0.com
