### ISSUE TITLE
macCatalyst support

### ISSUE THREAD

**Issue by piercifani** [auth0/Auth0.swift#396]
### Describe the problem you'd like to have solved

We're building a macCatalyst version of our application, but some of the symbols used inside Auth0 are not available for macCatalyst. Specifically, `SFAuthenticationError` symbols are deprecated since iOS 13 and they should be migrated to `ASWebAuthenticationSessionErrorCode`.
 
### Describe the ideal solution

macCatalyst should be a supported platform, specially since Apple Silicon based Macs are right around the corner and run iOS apps as is. Intel based Macs should also get this treatment with Catalyst.

## Alternatives and current work-arounds

Remove Auth0 from our codebase and build login manually.

### Additional context

Auth0 is integrated with CocoaPods

**Comment by cocojoe** [comment]
Thanks @piercifani we are evaluating this internally 👍  I'll leave this open for now.

**Comment by Widcket** [comment]
Hi @piercifani, I tested with a sample app and it compiles successfully with Xcode Version 11.6 (11E708). [SimpleKeychain](https://github.com/auth0/SimpleKeychain) compiles with a couple of warnings, though, and those will be addressed.

**Comment by Widcket** [comment]
Auth0.swift also produces a few Catalyst-related compiler warnings, and we'll be addressing these as well.

<img width="1012" alt="Screen Shot 2020-08-11 at 21 30 50" src="https://user-images.githubusercontent.com/5055789/89962064-03d87800-dc1a-11ea-8865-86061f002242.png">

**Comment by piercifani** [comment]
Hey! 

I just updated to Auth0 version 1.27.0 and I'm still getting this error when compiling:

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/869981/90002180-d7584680-dc81-11ea-8ae7-fe08281ddeeb.png">

**Comment by Widcket** [comment]
@piercifani are you using Xcode 12 and/or macOS Big Sur?

**Comment by piercifani** [comment]
Yes, latest beta 5 in Big Sur

**Comment by Widcket** [comment]
Thanks, we'll dig more into this.

**Comment by piercifani** [comment]
The issue is that `SFAuthenticationSession` is not available on Catalyst, so you have to use `ASWebAuthenticationSession`. Thankfully it's just a rename

**Comment by Widcket** [comment]
This is now fixed in [1.30.0](https://github.com/auth0/Auth0.swift/releases/tag/1.30.0).
