### ISSUE TITLE
Authentication web view blank on iOS 14b3

### ISSUE THREAD

**Issue by jshier** [auth0/Auth0.swift#400]
### Description

Using iOS 14b3, the `ASWebAuthenticationSession` presented for login is blank. This is presented within a navigation context as a push, using `webAuth.start`.

### Reproduction

We simply use `webAuth.start`, which presents the authentication view itself.

### Environment

- **Version of this library used:** 1.26.0
- **Version of the platform or framework used, if applicable:** iOS 14b3, simulator.
- **Other relevant versions (language, server software, OS, browser):** Xcode 12b3
- **Other modules/plugins/libraries that might be involved:** None.

**Comment by jshier** [comment]
With further testing:

* Initial load of the authentication controller loads no web content. There is no progress showing and nothing appears to load.
* After 10 seconds the title of the controller flashes and it appears to reload.
* After another 20 seconds, the content properly loads.

So this may just be an issue with the Safari view controller having delayed loading, as we also see issues on logout, where the `SilentSafariViewController` is on screen for 10 seconds before processing the logout, despite the same call being very fast on 13.5.

**Comment by Widcket** [comment]
Hi @jshier, can you reproduce this with the [sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/00-Login)?

**Comment by jshier** [comment]
Looks like this was a beta issue which is largely fixed in beta 4. I still see the `SilentSafariViewController` for a few seconds longer than usual, but the login Safari controller loads immediately now.
