### ISSUE TITLE
How to setup Environment?

### ISSUE THREAD

**Issue by muzammil-triffort** [auth0/Auth0.swift#402]
For iOS I have integrated the Auth0.plist in my app. Everything is working perfect but now I have added different environments like: Staging, Development and Production. Providing correct client_id is not working. I am trying to add the client id like this:

```
func plistValues(bundle: Bundle) -> (clientId: String, domain: String)? {

var domain = ""
var clientId = ""

 #if DEBUG //Development
      clientId  = "dev-client-id"

  #elseif STAGING
      clientId  = "stage-client-id"

  #elseif PRODUCTION
      clientId  = "prod-client-id"
  
  #endif

  return (clientId: clientId, domain: domain)
}
```

I am not sure this the correct way or not. As I don't find any other method to setup the client id on run time. I am using version 1.18 for Swift project.

**Comment by Widcket** [comment]
Hi @muzammil-triffort, you can pass the `clientId` and `domain` programmatically like this:
```swift
Auth0.webAuth(clientId: "YOUR_CLIENT_ID", domain: "YOUR_DOMAIN")
    .start { result in // ... 
}
```

**Comment by muzammil-triffort** [comment]
I am not using WebAuth. I am using native method for login and signup.

**Comment by Widcket** [comment]
@muzammil-triffort it's the same:
```swift
Auth0.authentication(clientId: "YOUR_CLIENT_ID", domain: "YOUR_DOMAIN")
```
