### ISSUE TITLE
CredentialsManager for WatchOS

### ISSUE THREAD

**Issue by JMCPH** [auth0/Auth0.swift#403]
### CredentialsManager on WatchOS
I'm always frustrated that I'm not able to use the credentials manager in the WatchOS extension.

Is this on the roadmap?

**Comment by JMCPH** [comment]
@Widcket can I assign this to you?

**Comment by JMCPH** [comment]
Would be really great to get some feedback and support as we are a paying customer of your product.

**Comment by Widcket** [comment]
Hi @JMCPH, we're evaluating this internally and will update when we reach a decision.

**Comment by JMCPH** [comment]
@Widcket thank you very much. Looking forward to your decision.

**Comment by JMCPH** [comment]
@Widcket when can we expect a decision on this?

**Comment by Widcket** [comment]
@JMCPH we'll be adding this in the next release, which will be out tomorrow.

**Comment by JMCPH** [comment]
Thank you so much!!

**Comment by Widcket** [comment]
@JMCPH the feature [has been merged](https://github.com/auth0/Auth0.swift/pull/409), but the release was delayed for tomorrow.
