### ISSUE TITLE
Cannot clear session with ephemeral session

### ISSUE THREAD

**Issue by fiix-haewon** [auth0/Auth0.swift#404]
### Description
Auth 1.25.0 add `useEphemeralSession()` for iOS 13. It makes to start without content popup, but we cannot log out with ephemeral session. 

### Reproduction

```
Auth0
    .webAuth()
    .audience("https://{YOUR_AUTH0_DOMAIN}/userinfo")
    .useEphemeralSession()
    .start { result in
        switch result {
        case .success(let credentials):
            print("Obtained credentials: \(credentials)")
        case .failure(let error):
            print("Failed with \(error)")
        }
    }
```

```
Auth0
    .webAuth()
    .clearSession(federated: isFederated) { isSuccess in
        if isSuccess {
            print("Success clear session")
        } else {
            print("Failed to clear session")
        }
    }
```

Suggestion: 
```
final class AuthenticationServicesSessionCallback: SessionCallbackTransaction {

    init(url: URL, schemeURL: URL, ephemeralSession: Bool, callback: @escaping (Bool) -> Void) {
    .....

         if #available(iOS 13.0, *) {
            authSession.presentationContextProvider = self
            authSession.prefersEphemeralWebBrowserSession = ephemeralSession
        }
    .....
     }

}
```
### Environment

> Please provide the following:

- **Version of this library used:** 1.27.0
- **Version of the platform or framework used, if applicable:** iOS 13 or higher
- **Other relevant versions (language, server software, OS, browser):** Swift 5.1 or higher
- **Other modules/plugins/libraries that might be involved:**

**Comment by Widcket** [comment]
Hi @fiix-haewon, since `useEphemeralSession()` does not use Safari's shared cookie jar, there's no need to remove the cookie. It's like using a browser in incognito mode.

**Comment by fiix-haewon** [comment]
So, is it enough to revoke the token for logout?

**Comment by Widcket** [comment]
@fiix-haewon to perform a logout you should clear the stored credentials and revoke the refresh token.
