### ISSUE TITLE
Opening Universal Login causes issue with SwiftUI App for iOS 14b4

### ISSUE THREAD

**Issue by krames133** [auth0/Auth0.swift#405]
### Description
After updating to Xcode and iOS beta version 4 I am experiencing strangeness with the Auth0 universal login behavior.

I have a button that launches the universal login like so :
```
button(action: {
     Auth0
      .webAuth()
      .start()
})
```

The behavior I expect is for the app to display the prompt that takes you out of the app to the universal login page as it did before. (Was working fine for beta version 3).

Now it seems to cause some stuttering in the app before the launch prompt appears. Almost likes its starting a whole new instance of my login view.

I have to press the same button all over again for it to display the prompt properly. Once I login as normal my app code doesnt seem to respond to the success/failure callbacks as it normally does.

I realize this could very well be due to beta 4. I have opened up questions on other forums for that as well. I just want to see if anyone else is seeing the same behavior or has a fix. Thanks.

### Environment

- **Version of this library used:** 1.26
- **Version of the platform or framework used, if applicable:** xcode 12b4, ios14b4
- **Other relevant versions (language, server software, OS, browser):** SwiftUI

**Comment by krames133** [comment]
I seemed to have solved this issue by reworking how I am managing my apps @ObservableObjects that handled navigation state.

SwiftUI has a new object type called @StateObject that was better suited to handle this along with the app/view lifecycle.

No further action is needed. Thank you.

**Comment by dhanrajdc7** [comment]
Hey @krames133, Can you please share the code? It will be very helpful. Thank you in advance!!!
