### ISSUE TITLE
Add support for web based universal login for macOS 10.11 to 10.14 

### ISSUE THREAD

**Issue by MichaelHudgins** [auth0/Auth0.swift#406]
### Describe the problem you'd like to have solved

The support of macOS 10.11 to macOS 10.14 for web auth flow.

### Describe the ideal solution

The ability to use the already preset 10.15 auth flow for previous operating systems

## Alternatives and current work-arounds

I have added a way to achieve this in older operating systems by launching the users default browser.  PR to follow 

### Additional context
This was discussed as not something auth0 wanted to support / put the effort in for previous os support.  I ended up needing to add this support for my own projects so I decided to purpose a change to add these to the official repo. 

Is related to   #375  I will submit a PR to follow with the purposed changes

**Comment by MichaelHudgins** [comment]
See #407

**Comment by Widcket** [comment]
Closing as we won't be pursuing this now, as per https://github.com/auth0/Auth0.swift/pull/407.
