### ISSUE TITLE
Auth0.swift fails to build with Swift 5.3 compiler

### ISSUE THREAD

**Issue by SergejLogis** [auth0/Auth0.swift#415]
### Describe the problem

`Auth0.swift` fails to build with Swift 5.3 compiler.

### What was the expected behavior?

`Auth0.swift` library built successfully.

### Reproduction

- Set Command Line Tools to use Xcode 12 Beta 6.
- Add `github "auth0/Auth0.swift" ~> 1.28` to Cartfile
- Run `carthage bootstrap --platform iOS`
- Observe `JWTDecode` dependency build failure.

### Environment

- Auth0.swift 1.28
- iOS 13.5 simulator
- Catalina 10.15.6
- Xcode 12 Beta 6

**Comment by Widcket** [comment]
Hi @SergejLogis, thanks for reporting. `JWTDecode` fails to build because `Nimble` fails to compile, so we need to wait until they merge support for Xcode 12. We're tracking BigSur+Xcode 12 issues here: https://github.com/auth0/Auth0.swift/issues/397
