### ISSUE TITLE
loginSocial for Google is not working!

### ISSUE THREAD

**Issue by Z1napp** [auth0/Auth0.swift#417]
**Hello, I’m trying to implement google sign in with Auth0 and I have an unsuccessful callback.**

What is wrong with my implementation?

```
Auth0
        .authentication()
        .loginSocial(token      : token,
                     connection : "google-oauth2",
                     scope      : "openid profile")
        .start { (result) in
            switch result {
            case .success(let credentials):
                print("Obtained credentials: \(credentials)")
            case .failure(let error):
                print("Failed with \(error)")
                failure(error)
            }
    }
```
I’ve implemented successfully google sign in presentation and in the delegate method “didSignInFor”
I implemented that code. With google everything is okay. It’s responding with the token.

Seems like that I have the same problem such as on that topic.
And I have the same output “**Not Found**”. (The only difference is - Google and Facebook).

WebAuth is not the correct solution for me.

[LINK ON MY ISSUE (COMMUNITY PAGE)](https://community.auth0.com/t/loginsocial-for-google-isnt-working/49718)

Auth0 iOS SDK (version is 1.0)

--------------------------------
@ashish had couple questions for @kamlesh.jswal in that [topic](https://community.auth0.com/t/loginsocial-for-facebook-is-not-working-in-swift/35816). (ashish and kamlesh.jsway - users from the community)

So I will answer these questions too.

The questions are:

Are you seeing facebook login screen or not?
is there any error that you get?
Is the Facebook connection properly setup? Does the Try connection button work for you in Auth0 dashboard?
In my situation is Google so yep, I can see google sign form in application and after successful login, it returns token in `func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!)` delegate method. So this step is 100% successful.
I have Not Found error in the failure block. (case .failure)
Google connection is properly set and working fine. “Try connection” button working as well and webAuth also working well. The problem only with loginSocial.

**Comment by Widcket** [comment]
Hi @Z1napp, apologies for the delay. Are you still experiencing this issue?

**Comment by Z1napp** [comment]
Hello, @Widcket, I've just tested it right now and it's still reproducing (Pod version is 1.30.0).
I have the same issue with the same "Not found" error.

**Comment by Widcket** [comment]
@Z1napp can you please [enable logging](https://github.com/auth0/Auth0.swift#logging) and post the response from the `loginSocial` call? Please remove the token, Auth0 domain and other sensitive info.

**Comment by cocojoe** [comment]
Hi @Z1napp there may be a miss understanding of this functionality.

See: https://github.com/auth0/Auth0.swift/blob/master/Auth0/Authentication.swift#L578

The documentation for this method states that it is a legacy method and is no longer supported for new tenants as of 8th June 2017.  So there is no support at this time for exchanging a Google access token for an Auth0 one.

There is support for Facebook which you may have seen in our QuickStart https://auth0.com/docs/quickstart/native/ios-swift-facebook-login

It uses this method https://github.com/auth0/Auth0.swift/blob/master/Auth0/Authentication.swift#L296

**Comment by Z1napp** [comment]
Thank you a lot for replying, @cocojoe, are there any other methods to log in with google programmatically? (without webAuth)

**Comment by Z1napp** [comment]
@Widcket 
Here's log

```
POST https://somedomain.com/oauth/access_token HTTP/1.1
Content-Type: application/json
Auth0-Client: someInfo

{"scope":"openid profile","client_id”:”SomeClientID,”connection":"google-oauth2","access_token”:”GoogleAccessToken”}

HTTP/1.1 404
Server: cloudflare
Content-Length: 9
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
cf-ray: 5f0931273b143d71-KBP
Cache-Control: private, no-store, no-cache, must-revalidate, post-check=0, pre-check=0, no-transform
Vary: Accept-Encoding
x-ratelimit-limit: 300
x-ratelimit-reset: 1605110069
ot-tracer-sampled: true
x-content-type-options: nosniff
cf-cache-status: DYNAMIC
ot-tracer-traceid: 59b4ea96663d5d7d
Content-Type: text/plain; charset=utf-8
x-auth0-requestid: 75e97241c19d872d6561
Etag: W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"
Strict-Transport-Security: max-age=31536000
ot-baggage-auth0-request-id: 5f0931273b143d71
x-ratelimit-remaining: 299
ot-tracer-spanid: 6bf5716427d4ad1e
Date: Wed, 11 Nov 2020 15:54:28 GMT
cf-request-id: 06599d0c8100003d711b0f0000000001

Not Found
```

**Comment by Widcket** [comment]
@Z1napp was your tenant created after June 2017? As @cocojoe said, this method is unavailable for newer tenants, and currently there's no replacement other than using WebAuth.

**Comment by Z1napp** [comment]
@Widcket thanks for replying!
Yep, it was created in 2020 so if there is no way to make it programmatically - I'm gonna use web auth.
I think we can close that issue 👍
