### ISSUE TITLE
emailVerified parameter (Profile) isn't update after verifying.

### ISSUE THREAD

**Issue by Z1napp** [auth0/Auth0.swift#418]
Hi There, I have issue related to “`emailVerified`” parameter inside “`Profile`” object callback inside “`Auth0.authentication().userInfo`” method.

Here’s my code:

```
Auth0.authentication().userInfo(token: credentials?.accessToken ?? "").start { (result) in
                    switch result {
                    case .success(let profile):
                            completion(profile)
                    case .failure(let error):
                        print("Failed with \(error)")
                        completion(nil)
                    }
```
In the dashboard (inside the user management section) I can track the status of email verification.
Before verification we’re have “pending” email status and after clicking on the link (attached in the email) - status changes to “verified”.
If I will call this method before verification - I will get false value in profile. emailVerified parameter.
After email verification in the dashboard, I can track email status and I see that status is changed to “verified”, but **nothing changed** in the profile, which is returned in function inside my application. It’s still false such as before verification.

_I have iOS Auth0 SDK with 1.0 version_

**Comment by Widcket** [comment]
Hi @Z1napp, apologies for the delay here. Are you still having this problem?

**Comment by Z1napp** [comment]
Hello, @Widcket, issue is still on version 1.30.0.
For issue reproducing please follow these steps:
1. Form iOS Code create some user (not from webAuth), use - "Auth0.authentication().createUser...."
2. Look at user management in the dashboard, try to find a user, which you've just created, and look at the "Email" section (It will say, that email is "pending").
3. Verify email with a link (attached to email).
4. Look at the dashboard again and the email section will tell, that email is verified now (Its correct behavior).
5. Try to fetch the user with "Auth0.authentication().userInfo..." method and look at the "emailVerified" parameter - equal to false (Please look at the attached screenshot).

P.S: Also, the email parameter is nil, but that's not the same problem (Look at the screenshot).

<img width="335" alt="Screenshot 2020-11-10 at 11 43 59" src="https://user-images.githubusercontent.com/6150710/98657145-35acc800-234a-11eb-951a-02a6877daea3.png">

Here's a dashboard screenshot which tells, that the user has verified his email.
<img width="972" alt="Screenshot 2020-11-10 at 11 46 13" src="https://user-images.githubusercontent.com/6150710/98657355-7278bf00-234a-11eb-931e-036955b6c1f7.png">

**Comment by Widcket** [comment]
@Z1napp can you please [enable logging](https://github.com/auth0/Auth0.swift#logging) and post the request and response logs? Make sure to remove the Auth0 domain and other sensitive info.

**Comment by Z1napp** [comment]
Hello, @Widcket! That's my logs (Duplicate from my other issue, but it's passing for that issue as well).

Seems like that method (**userinfo**) -> returns **A0Profile** with default **false** bool value for the **emailVerified** field. Maybe it's related to the empty **email** parameter (as you can see I have not email value in response).

```
GET https://??.com/userinfo HTTP/1.1
Authorization: Bearer ?????
Auth0-Client: ??????
Content-Type: application/json

HTTP/1.1 200
cf-cache-status: DYNAMIC
Date: Wed, 11 Nov 2020 15:22:13 GMT
Access-Control-Allow-Origin: *
x-auth0-requestid: 6ca0f4d30f631189ec58
cf-request-id: 06597f866a00002d4fdbaf7000000001
Server: cloudflare
Vary: Accept-Encoding
cf-ray: 5f0901ea3ee52d4f-KBP
Strict-Transport-Security: max-age=31536000
Content-Type: application/json; charset=utf-8
ot-tracer-sampled: true
access-control-allow-credentials: false
access-control-expose-headers: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset
ot-tracer-traceid: 4d8984337cc356ce
Etag: W/"11e-K8W4t9HuBUoAcu+ZvlLt/KAKe5M"
x-ratelimit-reset: 1605108146
ot-tracer-spanid: 5d513f9004a8d5c6
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
x-content-type-options: nosniff
x-ratelimit-remaining: 9
ot-baggage-auth0-request-id: 5f0901ea3ee52d4f
Cache-Control: private, no-store, no-cache, must-revalidate, post-check=0, pre-check=0, no-transform
Content-Encoding: gzip
x-ratelimit-limit: 10

{"sub":"auth0|5fac011e16d2c60069ee7c7a","nickname":"pwlmduwymckvslxidc","name":"pwlmduwymckvslxidc@mhzayt.com","picture":"https://s.gravatar.com/avatar/2bab284a1d7befb659e58f1c4f42a46e?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fpw.png","updated_at":"2020-11-11T15:22:13.380Z"}
```

That's verification screenshots for that user.

1.
<img width="298" alt="Screenshot 2020-11-11 at 17 30 55" src="https://user-images.githubusercontent.com/6150710/98831070-c3b8a980-2443-11eb-8501-cdba8c3320b4.png">
2.
<img width="973" alt="Screenshot 2020-11-11 at 17 30 51" src="https://user-images.githubusercontent.com/6150710/98831076-c5826d00-2443-11eb-9be6-0e6dbb494486.png">

**Comment by Widcket** [comment]
@Z1napp are you adding `email` to the scope string in the original authentication call? It's necessary for the `email` and `email_verified` properties to be available in the profile.

**Comment by Z1napp** [comment]
@Widcket Yes, sure :)
I'm passing email and password and after successful login -> calling `userInfo`

**Comment by Widcket** [comment]
Sorry, I mean adding `email` to the scope string, eg: 

```swift
Auth0
     .authentication(clientId:"YOUR_CLIENT_ID", domain: "YOUR_AUTH0_DOMAIN")
     .login(
         usernameOrEmail: "email@exmaple.com",
         password: "some secret password",
         realm: "some database",
         audience: "https://example.com/api",
         scope: "openid profile email") // < this
```

**Comment by Z1napp** [comment]
@Widcket Thanks a lot and sorry for the stupid question!
My problem is solved 👍
