### ISSUE TITLE
[Feature Request] Open authentication on other browsers.

### ISSUE THREAD

**Issue by amadeu01** [auth0/Auth0.swift#422]
How can we make the web flow authentication using another browser? Such as Edge?

**Comment by Widcket** [comment]
Hi @amadeu01, we use [Apple's APIs](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) to perform web-based authentication. These use an embedded instance of Safari, and currently there is no way to choose another browser for that.

**Comment by Widcket** [comment]
No, the SDK does not expose the generated authentication URL. That said, I'd advise against it as it does not goes with the current Apple guidance, and they might even reject your app on those grounds.
