### ISSUE TITLE
Provide a synchronous way of retrieving the currently stored Credentials 

### ISSUE THREAD

**Issue by JanC** [auth0/Auth0.swift#437]
### Describe the problem you'd like to have solved

Hey,
as a SDK user, I'd like to retrieve the currently stored `Credentials` in a **synchronous** way so that I can access some metadata stored in `Credentials.idToken` regardless of the credentials validity

### Describe the ideal solution

In the same way `Auth0.CredentialsManager` provides a way to store the credentials, it could provide a sync method to retrieve them:

```swift
func credentials() -> Credentials? {
    guard let data = self.storage.data(forKey: self.storeKey),
          let credentials = NSKeyedUnarchiver.unarchiveObject(with: data) as? Credentials else {
        return nil
    }
    return credentials
}
```

## Alternatives and current work-arounds

A workaround is to use directly the `A0SimpleKeychain` without relying on the `Auth0.CredentialsManager` and use the same `storeKey` as the one passed in the init of `Auth0.CredentialsManager`:

```swift
private extension A0SimpleKeychain {
    func credentials(_ storeKey: String) -> Credentials? {
        guard let data = self.data(forKey: storeKey),
              let credentials = NSKeyedUnarchiver.unarchiveObject(with: data) as? Credentials else {
            return nil
        }
        return credentials
    }
}
```

However, this unnecessarily exposes the `A0SimpleKeychain` as well as the way the credentials are persisted using `NSKeyedUnarchiver`. So if the `Auth0.CredentialsManager` way of archiving the credentials would change, the above code would likely fail.

**Comment by Widcket** [comment]
Hi @JanC, we'll look into adding a way to retrieve the user profile separately from the credentials in the next major. This is unlikely to happen for the current 1.x. Will close this for now.

**Comment by JanC** [comment]
thanks for your answer @Widcket 

> This is unlikely to happen for the current 1.x.

Even if I make a PR ? :) 

cheers

**Comment by Widcket** [comment]
We'll discuss this internally and come back to you.

**Comment by Widcket** [comment]
@JanC thanks for the offer, we'll happily take a PR that implements this. Might probably want to return an instance of [UserInfo](https://github.com/auth0/Auth0.swift/blob/master/Auth0/UserInfo.swift). Please ping if you have any questions or want to discuss something further.

**Comment by JanC** [comment]
ok, I have a branch somewhere with pretty much the implementation I posted in my original comment. I'll clean it up + write tests and will submit a PR. I'll look at the UserInfo
