### ISSUE TITLE
Allow http for local tests 

### ISSUE THREAD

**Issue by piofusco** [auth0/Auth0.swift#438]
My application is highly coupled to Auth0 in that nothing can really be done without internet connection and successfully logging into Auth0. It would be great if there was a way to break this coupling to enable UI testing of features behind Auth0.

Here's some of what I am working with:

When the user enters their creds and taps log in, this fires:
```
Auth0
  .authentication(clientId: clientId, domain: domain)
  .login(usernameOrEmail: username, password: password, realm: realm, audience: audience, scope: scope)
    .start({result in
      switch(result) {
        case .failure(let error): // handle this
        case .success(let credentials): // store credentials in a CredentialsManager
      }
})
```

Additionally, I am using `CredentialsManager(authentication: Auth0.authentication())`.

**One assumption** I am making is that the Auth0 SDK will insert "https" in front of any and all URLs that it deals with. Whether it's the domain in the `CredentialsManager` or any of the URLs as parameters I am passing into `login()`, if I put `localhost:8080`, it ends up `https://localhost:8080`. Having poked around a bit, it looks like the following extension is the culprit `NSURL+Auth0.swift`:

```
public extension URL {
    /**
     Returns an Auth0 domain URL given a domain

     - parameter domain: name of your Auth0 account

     - returns: URL of your Auth0 account
     */
    static func a0_url(_ domain: String) -> URL {
        let urlString: String
        if !domain.hasPrefix("https") {
            urlString = "https://\(domain)"
        } else {
            urlString = domain
        }
        return URL(string: urlString)!
    }
}
```

Having control over whether or not URLs are http or https would solve my issues.

**Another assumption** I am making is that maintaining a local instance of Auth0 would add a ton of scope to what I am trying to do. I don't really want to maintain any semblance of this for the types of tests I am writing - _I just need to zip through login for a UI test._ I plan on using a mock server to respond with canned responses for everything and just focus on happy path testing.

_Making Auth0Authentication public would also solve my issues_, however, I can appreciate how this might go against some architecture concerns I am not privy to. This would allow me to do something like `Auth0Authentication(clientId: clientId, url: "http://localhost:8080", session: session)` when I build my `CredentialsManager`.

Hope my ask is clear. Happy to clarify anything. Thanks!

**Comment by JanC** [comment]
hey,
just my two cents 

> My application is highly coupled to Auth0

I believe this is your main issue and if you remove that coupling by injecting Auth0 behaviour into your app, you won't have that your problem.

I also rely heavily on Auth0 but none of my application code actually knows about Auth0 as it's hidden behind a protocol. For example, those are the authentication methods I need in my app so I created this `AuthService` protocol

```swift
public protocol AuthService {
    /// Initiates the OTP request where the OTP is delivered via email to the spedicied e-mail address
    func startPasswordless(email: String, completion: @escaping (Swift.Result<Void, AuthError>) -> Void)

    /// Login using the OTP requested in `startPasswordless`
    func login(activationCode: String, email: String, completion: @escaping (Swift.Result<AuthCredentials, Error>) -> Void)

    /// Login using a username + password method. For this the user must exist in the
    func login(usernameOrEmail: String, password: String, completion: @escaping (Swift.Result<AuthCredentials, Error>) -> Void)

    func renewToken(withRefreshToken: String, scope: String?, completion: @escaping (Swift.Result<AuthCredentials, Error>) -> Void)
}
```

Then the Auth0 implementation just calls the Auth0 sdk. Here is only one method implemented for example 

```swift

public class Auth0Service: AuthService {
    public func login(usernameOrEmail: String, password: String, completion: @escaping (Swift.Result<AuthCredentials, Error>) -> Void) {
        authentication
            .login(usernameOrEmail: usernameOrEmail,
                   password: password,
                   realm: Constants.passwordConnection,
                   scope: Constants.scope)
            .start { result in
                switch result {
                case .success(let credentials):
                    self.handleSuccessResponse(credentials, completion: completion)
                case .failure(let error):
                    completion(.failure(AuthServiceError.backendError(error)))
                }
            }
    }
}
```


Then in your app you can inject the `AuthService` 
```swift
class ViewController: UIViewController {
    init(authService: AuthService = Auth0Service()) {
     ...
    }

    func login() {
        authService.login(usernameOrEmail: ....
    }
}
```


In your UI tests, instead of creating the actual `Auth0Service`, you can inject a mock of `AuthService` and configure its behaviour (whether login succeeds or fails). You can either implement your own mocks or use [SwiftyMocky](https://github.com/MakeAWishFoundation/SwiftyMocky) to generate them.

By using the mocked protocol, you don't have to bother about https or localhost at all. You just define how your Auth service should behave in your tests instead trying to make assumptions how the internal Auth0 implementation works.



hope it helps :)

**Comment by piofusco** [comment]
@JanC - wonderful suggestion and it's definitely something that has crossed my mind - minus all the refactoring that would need to get done to be able to do this. Was definitely looking for a quick and dirty way, but now that I read my request the next day...what I am asking for isn't a good idea, haha. As such, I am gonna close this. Thanks.
