### ISSUE TITLE
Refresh Token missing from the login response.

### ISSUE THREAD

**Issue by Zanchee** [auth0/Auth0.swift#441]
### Describe the problem

I followed the example tutorial for setting up “Sign In With Apple” by creating a Native application and following that whole process. I managed to get everything working and authentication was a breeze.

However, I noticed when coming to refresh my token, that the CredentialsManager had no refresh token stored. After logging in again, I noticed that the response from the login call was ALSO missing the refresh token. I have refresh tokens enabled on my application settings and I’m using the default scopes which includes offline_access.
### What was the expected behavior?

I would expect a refresh token to not be nil after calling login with an apple authorization code.

### Reproduction

- Call `Auth0.authentication().login(appleAuthorizationCode ...)` with the default scopes
- Expect the resulting credentials to contain a refresh token instead of nil.

Domain: simplistic-development.us.auth0.com
Client ID: <redacted>

### Environment

> Please provide the following:

- **Version of `Auth0.swift` used:** 1.30.1
- **Version of iOS/macOS/tvOS/watchOS:** iOS 14
- **Version of Xcode:** 12

**Comment by Widcket** [comment]
Hi @Zanchee, which scopes are you passing to the login call?

**Comment by Zanchee** [comment]
@Widcket I'm using the default scopes which the docs for the function call include offline_access. I breakpointed the SDKs stack to confirm that the defaults mentioned in the comment were actually true, and they were.

**Comment by Widcket** [comment]
Can you please [enable logging](https://github.com/auth0/Auth0.swift#logging) and post the HTTP request and response, redacting any sensitive information?

**Comment by Zanchee** [comment]
@Widcket, hopefully this covers it.

```
POST https://simplistic-development.us.auth0.com/oauth/token HTTP/1.1
Content-Type: application/json
Auth0-Client: <private>

{"scope":"openid profile offline_access","grant_type":"urn:ietf:params:oauth:grant-type:token-exchange","client_id":"<private>","subject_token_type":"http:\/\/auth0.com\/oauth\/token-type\/apple-authz-code","subject_token":"<private>","audience":"simplistic-development-api"}

HTTP/1.1 200
x-ratelimit-reset: 1611893214
Content-Encoding: br
ot-tracer-sampled: true
Server: cloudflare
x-ratelimit-limit: 30
ot-tracer-spanid: 64c29cb92853387c
Strict-Transport-Security: max-age=31536000
Pragma: no-cache
Cache-Control: no-store
x-ratelimit-remaining: 29
cf-cache-status: DYNAMIC
ot-baggage-auth0-request-id: 619015463f2fbe87
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Alt-Svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
cf-ray: 619015463f2fbe87-RIC
ot-tracer-traceid: 493fb6e471190de6
Vary: Accept-Encoding
Content-Type: application/json
Date: Fri, 29 Jan 2021 04:06:53 GMT
cf-request-id: 07edeb9fe30000be873caf4000000001
x-content-type-options: nosniff
x-auth0-requestid: d3573b12b17e93f7aea1

{"access_token":"<private>","scope":"openid profile","expires_in":86400,"token_type":"Bearer"}
```

**Comment by Zanchee** [comment]
Looks like the returned response scopes doesn't include `offline_access` for some reason.

**Comment by Widcket** [comment]
Hi @Zanchee, please check the following:

Does your app have the **Refresh Token** grant enabled?

<img width="1024" alt="Screen Shot 2021-01-29 at 11 10 26" src="https://user-images.githubusercontent.com/5055789/106285070-c8128880-6222-11eb-8ecd-0026fee6e28a.png">

If you're requesting credentials for an API, does your API have refresh tokens enabled?

<img width="578" alt="Screen Shot 2021-01-29 at 11 11 25" src="https://user-images.githubusercontent.com/5055789/106285200-f1331900-6222-11eb-849e-f494b9907dd2.png">

**Comment by Zanchee** [comment]
That appears to be the problem. While following both the iOS and API guides, I was told to enable and configure refresh tokens on the application, but I didn't see it mentioned anywhere about enabling it on the API too. 

I had the grants enabled correctly on the application, but did not have offline access enabled for the API.

Sorry for the confusion, but thank you to you for being responsive and helpful through the whole thing, especially given it wasn't even an issue with the AUTH0 SDK

**Comment by Widcket** [comment]
Glad that solved the problem.
