### ISSUE TITLE
[iOS] Issue with the Apple Sign In

### ISSUE THREAD

**Issue by kaushikpaperboat** [auth0/Auth0.swift#445]
### Describe the problem

We are calling following method to initiate the apple login flow (Swift):

```
Auth0
    .webAuth(clientId: {clientId}, domain: {domain})
    .scope("openid email profile")
    .parameters(["prompt":"select_account"])
    .connection("apple")
    .useEphemeralSession()
    .logging(enabled: true)
    .start {}
```
Note that we are passing the **connection** parameter explicitly so we are essentially not using Universal Login provided by Auth0. Above method first launches the web view followed by Apple login view. On the Apple login view if user cancels the flow, the view dismisses but the very first webview still remain with white screen which then can be dismissed by tapping the cancel button again. 

### What was the expected behavior?

Tapping the cancel button on Apple view should also dismiss the main webview.

### Reproduction

It can be reproduced in the sample app also, you just have to add `.connection("apple")` call.

**Can the behavior be reproduced using the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample)?**

Yes

### Environment

> Please provide the following:

- 1.30.1
- 14.3
- 12.4

Is this the expected behaviour or is it a bug?

**Comment by Widcket** [comment]
Hi @kaushikpaperboat, thanks for raising this. This seems to be a bug on Apple's side - I was able to reproduce this without the SDK, using just `ASWebAuthenticationSession`.

```swift
import UIKit
import AuthenticationServices

class ViewController: UIViewController {
    var webAuthSession: ASWebAuthenticationSession?

    let authURL = URL(string: "https://YOUR_AUTH0_DOMAIN.auth0.com/authorize?nonce=1234&client_id=YOUR_AUTH0_CLIENT_ID&response_type=id_token&connection=apple&prompt=login&scope=openid%20profile&redirect_uri=https://jwt.io")!
    let callbackUrlScheme = "https://jwt.io"

    @IBAction func login() {
        self.webAuthSession = ASWebAuthenticationSession(url: authURL,
                                                         callbackURLScheme: callbackUrlScheme,
                                                         completionHandler: { (callback: URL?, error: Error?) in
            guard error == nil, let callback = callback else {
                return print("Error: \(String(describing: error))")
            }

            print("Success: \(callback.absoluteString)")
        })

        self.webAuthSession?.presentationContextProvider = self
        self.webAuthSession?.start()
    }
}

extension ViewController: ASWebAuthenticationPresentationContextProviding {
    func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
        return UIApplication.shared.windows.first!
    }
}

extension UIAlertController {
    static func show(message: String) {
        let alert = UIAlertController(title: nil, message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))

        UIApplication.shared.windows.first?.rootViewController?.present(alert, animated: true)
    }
}
```

https://user-images.githubusercontent.com/5055789/107439948-9f876a00-6b11-11eb-9949-11a8861ed5bb.mp4

We'll file a bug report with Apple.
