### ISSUE TITLE
Getting error: "The UIWindowScene for the returned window was not in the foreground active state."

### ISSUE THREAD

**Issue by arturjaworski** [auth0/Auth0.swift#446]
### Describe the problem

I'm getting failure result when login flow is initiated during control center dismiss animation. Login flow is initiated by:

```
Auth0
            .webAuth(clientId: clientID, domain: domain)
            .redirectURL(redirectURL)
            .scope(scope)
            .audience(audience)
            .parameters(parameters)
            .useEphemeralSession()
            .start { result in
                // getting failure
            }
```

Returned error is:
```
Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=3 "The UIWindowScene for the returned window was not in the foreground active state." UserInfo={NSDebugDescription=The UIWindowScene for the returned window was not in the foreground active state.}
```

Possible reason is wrong object returned as ASPresentationAnchor in ASAuthorizationControllerPresentationContextProviding implementation.

### What was the expected behavior?

Login web view screen should be shown.

### Reproduction

1. Open the app
2. Open control center
3. Close control center
4. Tap login button which calls login flow initiation code. It have to be tapped fast – when control center is closing.
5. Getting failure on result.

**Can the behavior be reproduced using the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample)?**

Yes

### Environment

- **Version of `Auth0.swift` used:** 1.28
- **Version of iOS:** 14.4
- **Version of Xcode:** 12.4

**Comment by Widcket** [comment]
Hi @arturjaworski, in this case the app window is not active yet, as Control Center is in the process of closing. Since the SDK needs an active window that belongs to the app, I'm afraid there is nothing we can do here.
