### ISSUE TITLE
New authentication session does not appear when replacing old authentication session

### ISSUE THREAD

**Issue by danlshields** [auth0/Auth0.swift#447]
### Describe the problem

When calling `WebAuthn.start()` multiple times, the previous authentication session is dismissed but a new authentication session does not appear.

The documentation for `WebAuthn.start()` suggests this is suppose to be a supported use case. 

> Any on going WebAuth Auth session will be automatically cancelled when starting a new one,
> and it's corresponding callback with be called with a failure result of `Authentication.Error.Cancelled`

The console output shows that Apple's authentication session is trying to present an `SFAuthenticationViewController` over the top of the existing `SFAuthenticationViewController`, which has just been removed from the view hierarchy.

```
[Presentation] Attempt to present <SFAuthenticationViewController: 0x10d81f800> on <SFAuthenticationViewController: 0x109844e00> (from <SFAuthenticationViewController: 0x109844e00>) whose view is not in the window hierarchy.
```

So perhaps Auth0 needs to wait for the old authentication to dismiss before presenting the new one.

### What was the expected behavior?

`WebAuthn.start()` should show a new authentication session. Instead, the old authentication session is dismissed and a new one is _not_ presented.

### Reproduction

- Start a `WebAuthn`
- Start another `WebAuthn`

Like so:
```swift
Auth0.webAuth().start { _ in }
DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
    Auth0.webAuth().start { _ in }
}
```

### Environment

- **Version of `Auth0.swift` used:** 1.30.1
- **Version of iOS/macOS/tvOS/watchOS:** 14.3
- **Version of Xcode:** 12.2

**Comment by danlshields** [comment]
Replacing the `authSession.start()` in `AuthenticationServicesSession.init` (in AuthenticationServicesSession.swift:64) with this:

```
if TransactionStore.shared.current != nil {
    DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
        authSession.start()
    }
} else {
    authSession.start()
}
```
fixes the problem but it's so hacky that I wasn't sure it was worth it to open a PR. I'd love to hear other ideas.

**Comment by Widcket** [comment]
Hi @danlshields, `SFAuthenticationViewController` will need a little bit of time to be dismissed before another VC can be presented. I'm afraid that's the way UIKit works.
Do you get the same behavior if you use `ASWebAuthenticationSession instead` of `SFAuthenticationViewController` (which is a deprecated Apple API)?

**Comment by danlshields** [comment]
I am using `ASWebAuthenticationSession` (Or rather, Auth0.swift is), the log message is coming from internally after `ASWebAuthenticationSession.start` is called.

As an Auth0.swift user, when the old session is dismissed and when the new one appears is entirely out of my control, afaict. Is there API to cancel the old session from outside Auth0.swift? Otherwise maybe I will make the PR after all.

**Comment by danlshields** [comment]
The issue is Auth0 is suppose to handle replacing the current login session, but it is not due to the timing issue.

**Comment by Widcket** [comment]
@danlshields `ASWebAuthenticationSession` does have a `cancel` [method](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/2990951-cancel), but the SDK does not expose it.

**Comment by Widcket** [comment]
Can you try adding `TransactionStore.shared.current?.cancel()` before `authSession.start()`?

**Comment by Widcket** [comment]
Closing this one for now - please ping if you'd like to discuss it further.
