### ISSUE TITLE
Unit tests fail when opening as a Swift package & targeting an iOS device or simulator

### ISSUE THREAD

**Issue by seanmcneil** [auth0/Auth0.swift#448]
### Unit tests fail & a crash occurs, when opening as a Swift package & targeting iOS

The following tests fail:
![Screen Shot 2021-02-08 at 8 48 17 AM](https://user-images.githubusercontent.com/6424532/107252689-715b3a80-69ea-11eb-85f6-e07d2cfef468.png)

The following is the crash log from one of them:
```
/.../Auth0.swift/Auth0Tests/CredentialsManagerSpec.swift:171: error: -[Auth0Tests.CredentialsManagerSpec multi_instances_of_credentials_manager__should_store_credentials_into_distinct_locations] : failed - expected to be nil, got <noCredentials>

Fatal error: Unexpectedly found nil while unwrapping an Optional value: file Auth0Tests/CredentialsManagerSpec.swift, line 172
2021-02-08 08:41:39.145554-0800 xctest[5436:3746809] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file Auth0Tests/CredentialsManagerSpec.swift, line 172
```

* Note - When targeting macOS, all unit tests pass successfully. Part of this is due to the `#if os(iOS)` check in the `ControllerModalPresenterSpec.swift` test.

### What was the expected behavior?

All unit tests pass & no crash occurs

### Reproduction

- Open Package.swift in Xcode 12.x
- Verify that the package is targeting an iOS device (macOS targets will succeed)
- Run all unit tests

### Environment

- 1.30.1 (commit f1059fe1e8421558eb9570968706e9da850ba6cd)
- 14.4
- 12.4

**Comment by Widcket** [comment]
Hi @seanmcneil, the SDK uses Carthage as its package manager, not SPM. What is your use case for trying to use SPM on the SDK project?

**Comment by seanmcneil** [comment]
Hello @Widcket 

Currently we actually use cocoapods, but we are planning to have full support with SPM. Since we embed your SDK into an internal one (long story, but is required for our business use case), we cannot mix & match dependency managers.

The test failure is not a deal breaker, but it does raise questions now about whether or not the functionality is working.

**Comment by Widcket** [comment]
The tests run normally with Carthage, which is our supported package manager for development. Please try them out. If anything comes up, ping me and I'll reopen the issue.
