### ISSUE TITLE
Auth0 Swift 3 support

### ISSUE THREAD

**Issue by aqeelb** [auth0/Auth0.swift#45]
Hi,

We're in a process of migrating our codebase to **Swift 3** to support **iOS 10**.  We're are using _Auth0 SDK_ for our iOS, Android & Web-based products. Our codebase migration has hit a deadlock since Auth0 **1.0.1-rc.2** for iOS does not support **Swift 3**. Please update us as soon as possible.

Thanks,
Team Pixerf

**Comment by lethianqt94** [comment]
I have the same problem... :(

**Comment by aqeelb** [comment]
@hzalaz Thanks very much 👍 @lethianqt94 You should smile now 💃

**Comment by lethianqt94** [comment]
👍 . Thanks so much.
