### ISSUE TITLE
Authentication via OneLogin on macOS Detects Incorrect macOS Version

### ISSUE THREAD

**Issue by JUSTINMKAUFMAN** [auth0/Auth0.swift#450]
### Describe the problem

I am using this framework in a Swift-based macOS app with a minimum deployment target of **macOS 11.0**. 

When calling the following code:

```
Auth0
    .webAuth()
    .scope(...)
    .audience("https://.../userinfo")
    .start { ... }
```

...and proceeding with the OneLogin authentication method (as opposed to using the sign in with Google option, for example), the web flow incorrectly identifies the macOS version as 10.15.6 - an impossible version given that the app will only run on macOS v11.0+.

![Auth0OneLoginBug](https://user-images.githubusercontent.com/5123191/107675154-a070e680-6c4c-11eb-9350-5bc0298dae30.png)

As it stands, this blocks users from authenticating via OneLogin (our preferred method) altogether.

### What was the expected behavior?

I would expect the flow to correctly identify the macOS version of the host machine, and for this warning not to appear at all (unless the user was running macOS 11.0 and our minimum macOS version was 11.1+, which is not the case here).

### Reproduction

- Add the Auth0.swift framework to a Swift macOS project via SPM in Xcode 12.4 (following the instructions provided in the README).
- Call the following code after app launch:
```
Auth0
    .webAuth()
    .scope(...)
    .audience("https://.../userinfo")
    .start { ... }
```
- Attempt to login via OneLogin

**Can the behavior be reproduced using the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample)?**

Yes. In fact, I believe you are aware of this bug since there seems to be a branch on this repo from a few months ago targeting the problem (though I have not personally tested the code in that branch).

### Environment

> Please provide the following:

- **Version of `Auth0.swift` used:** 1.30.1
- **Version of iOS/macOS/tvOS/watchOS:** macOS 11.2
- **Version of Xcode:** 12.4

**Comment by Widcket** [comment]
Hi @JUSTINMKAUFMAN, this is not an SDK issue as we do not perform any checks on the macOS version. I've pinged internally the right team though.
