### ISSUE TITLE
Queue token refreshes 

### ISSUE THREAD

**Issue by aj-bartocci** [auth0/Auth0.swift#457]
### Describe the problem you'd like to have solved
When making multiple requests to **credentialsManager.credentials**, while having an outdated access token, will result in multiple token refresh requests going out which is not expected. I would like only one refresh request to be made at any given time, and any other requests made while a token is refreshing be queued and return the result of the single token refresh request.

### Describe the ideal solution
When making multiple requests to get to **credentialsManager.credentials** serially from the same thread, it can lead to multiple token refresh requests which is not expected. In the documentation it is mentioned "This method is not thread-safe, so if you're using Refresh Token Rotation you should avoid calling this method concurrently (might result in more than one renew request being fired, and only the first one will succeed).", however this is not completely true. Calling this method serially in a thread safe way (from the main thread) can still lead to the same situation. To fix this, requests should be queued. 

## Alternatives and current work-arounds
Currently I queue requests before calling **credentialsManager.credentials**, and if multiple requests come in before the the async **credentialsManager.credentials** call returns then I queue them. When **credentialsManager.credentials** request finishes I then pass the result to all requests in the queue and empty the queue. I can create a pull request with my implementation if this is a wanted feature. If this is out of scope for the framework then ideally please update the documentation to make users aware that they will run into this issue, even if not calling **credentialsManager.credentials** concurrently. I.e. making two calls to **credentialsManager.credentials** in immediate succession can lead to requestOne being in the process of refreshing while requestTwo attempts to refresh with the same credentials, which results in requestOne succeeding and requestTwo failing.

**Comment by Widcket** [comment]
Hi @aj-bartocci, thanks for raising this. I've opened a PR to update the documentation around this, as queuing the requests is out of scope for this library, at least for the current major.

**Comment by Widcket** [comment]
Hi @aj-bartocci, Auth0.swift [2.0.0-beta.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0-beta.0) is out now. It does thread-safe token renewals. See https://github.com/auth0/Auth0.swift/issues/637 for more information.

**Comment by Widcket** [comment]
The [2.0.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0) release is out now. Please check the [Migration Guide](https://github.com/auth0/Auth0.swift/blob/master/V2_MIGRATION_GUIDE.md) for more information on how to update your apps.
