### ISSUE TITLE
[Universal Login] Error code gets swallowed, web view just dismisses instead

### ISSUE THREAD

**Issue by iwasrobbed** [auth0/Auth0.swift#461]
### Describe the problem

When an authentication error happens via `ASWebAuthenticationSession`, such as during a misconfiguration or Auth0 being buggy, the error is not populated in the result and instead only given in the callback URL.

The callback URL ends up not surfacing the error and instead just dismisses the web view with nothing shown in either the UI or the web view.

This is because of the conditional check `guard $1 == nil, let callbackURL = $0 else {` which just falls through to `_ = TransactionStore.shared.resume(callbackURL)` which does nothing with it

### What was the expected behavior?

An error should be surfaced within the app.

### Reproduction

1. Configure the audience to use `userInfo` (camelCase) instead of the expected `userinfo`
2. Perform a passwordless web auth like:

```swift
Auth0.webAuth(clientId: clientId, domain: domain).scope("openid profile").audience(audience).start {
    switch $0 {
    case .failure(let error):
        print("Error was: \(error)")
    case .success(let credentials):
        print("Success")
    }
}

...
private let clientId = "blah"
private let domain = "custom-auth.us.auth0.com"
private lazy var audience = "https://\(domain)/userinfo"
```

3. Set a breakpoint on the follow

<img width="1176" alt="Screen Shot 2021-03-09 at 3 04 46 PM" src="https://user-images.githubusercontent.com/317671/110533465-06397c80-80ec-11eb-89dd-b40f34349d12.png">

4. Print out the `$0` variable

> co.domain.app://custom-auth.us.auth0.com/ios/co.domain.app/callback?error=invalid_request&error_description=no%20connections%20enabled%20for%20the%20client&state=CVAZWFZ2_Vsn70viao2HTiV3xLGTzIbq9ctCeMpfEKs
		
> co.domain.app://custom-auth.us.auth0.com/ios/co.domain.app/callback?error=access_denied&error_description=Service%20not%20found%3A%20https%3A%2F%2Fcustom-auth.us.auth0.com%2FuserInfo&state=3lqD-v8A3i02QTrq0csJZD2zWP7_uPzto4wd3T5MLiM

5. Notice that the `$1` (error) variable is `nil`, so the `self?.callback(.failure(error: authError))` is never called and it instead just silently swallows the error.

**Can the behavior be reproduced using the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample)?**

Yes. Configure the audience to use `userInfo` (camelCase) instead of the expected `userinfo`, then run it.

At one point, the error was saying the connection wasn't enabled on the app, even though it was. So I toggled it off and then back on and then it worked. It just never reported the error to me (without setting a breakpoint)

^ This looks like a [known issue](https://community.auth0.com/t/passwordless-no-connections-enabled-for-client/37577/2?u=iwasrobbed) for a year now.

### Environment

> Please provide the following:

- **Version of `Auth0.swift` used:** 1.30.1 (but looks the same on latest release as well)
- **Version of iOS/macOS/tvOS/watchOS:** 14.4
- **Version of Xcode:** 12.4

**Comment by Widcket** [comment]
Hi @iwasrobbed, thanks for raising this.
In the case of failure, the SDK should call the completion handler with an error. That is what happens in my testing if I use `/userInfo` as the audience value; the callback URL is called with an error, that [gets extracted](https://github.com/auth0/Auth0.swift/blob/master/Auth0/BaseAuthTransaction.swift#L62) and passed to the completion handler:

<img width="1494" alt="Screen Shot 2021-03-11 at 15 20 33" src="https://user-images.githubusercontent.com/5055789/110836134-7841cb00-827e-11eb-8cd4-d3e39d369b29.png">

Given that the SDK indeed concludes the operation with an error, I'm not sure what the expected behavior here is -could you please provide more information?

**Comment by iwasrobbed** [comment]
Hi @Widcket 👋 The app delegate's URL callback was not being called in my case (on either the same app or our app) so I believe that's where the disconnect lies and why it just dismissed the universal login without any reporting. I'll have to look into that issue separately

Still feels like there's room here for more robustness, but feel free to close the ticket

**Comment by Widcket** [comment]
Glad you found out the cause.
