### ISSUE TITLE
Incorrect calculation of `expiresIn` date

### ISSUE THREAD

**Issue by nab0y4enko** [auth0/Auth0.swift#462]
### Describe the problem

`Credentials.expiresIn` field is always nil

### What was the expected behavior?

`Credentials.expiresIn` field should be valid

### Reproduction

- Create WebAuth instance and use start() method to present Login Web View(Code Attachement 1)
- Login to account using Any available methods
- Check Network logs - Response contains `expiresIn` number field
- Check `Credentials` model mapped by Auth0.Swift - `expiresIn` field is nil

**Code Attachement 1**
```
let webAuthentication = Auth0.webAuth(clientId: auth0ClientId, domain: auth0Domain)
                .scope(defaultScope)
                .useLegacyAuthentication()
     
webAuthentication.start { [weak self] (result) in
                guard let self = self else {
                    return
                }
                
                switch result {
                case .success(let credentials):
                    self.loadUserInfo(credentials: Auth0Credentials(credentials: credentials), handler: handler)
                case .failure(let error):
                    if let auth0Error = error as? Auth0.WebAuthError, case .userCancelled = auth0Error {
                        handler(.failure(AuthorizationProviderError.userCancelled))
                    } else {
                        handler(.failure(error))
                    }
                }
            }
```

**Code Attachement 2**
The issue is the wrong calculation of the date in the following code:

```
if let value = json["expires_in"] {
    let string = String(describing: value)
        if let double = NumberFormatter().number(from: string)?.doubleValue {
           expiresIn = Date(timeIntervalSinceNow: double)
        }
    }
 }
```
<img width="1434" alt="Screen Shot 2021-03-15 at 6 05 30 PM" src="https://user-images.githubusercontent.com/1070269/111229710-c62b3b80-85bc-11eb-97f4-60e228ae89da.png">

<img width="1208" alt="Screen Shot 2021-03-15 at 6 27 53 PM" src="https://user-images.githubusercontent.com/1070269/111229722-cb888600-85bc-11eb-8e78-5f41448b357b.png">

### Environment

- Version of `Auth0.swift` used: 1.31.1
- Version of iOS: 14.4
- Version of Xcode: 12.4

**Comment by Widcket** [comment]
Hi @nab0y4enko, thanks for raising this.

I just tried logging in and dumping the Credentials object, and it contained an `expiresIn` date:

<img width="472" alt="Screen Shot 2021-03-16 at 01 10 15" src="https://user-images.githubusercontent.com/5055789/111254834-a3b51480-85f4-11eb-8aa3-5c0898f7adf7.png">

Can you please share a minimal app that reproduces the issue?

**Comment by Widcket** [comment]
@nab0y4enko I'll close this one for now - let me know if you are still experiencing this issue.
