### ISSUE TITLE
Refreshing token in extension app

### ISSUE THREAD

**Issue by TarekSalama** [auth0/Auth0.swift#464]
Hello,

First, I am not sure where to ask this since it's really not a bug as far as I know but I don't see it mentioned any where in the documentation. So sorry if I have missed the answer else where.

Basically, I am trying to use Auth0 in my app's Share Extension. I was able to get Auth0 to be recognized by the extension however I am having hard time refreshing the token. 
So I know that the token (or the credentials object) gets saved in the main app's keychain container however this container - to my knowledge - is not accessible by extensions. I am only able to access the token via a different shared container (UserDefaults or Keychain) but this process has to happen in the container app rather than the extension.

So my question is, is there a way for me to refresh the token (in my app it seems that this has to happen every 24 hours) in the extension app without going back to the container app?

Thanks!

**Comment by Widcket** [comment]
Hi @TarekSalama, you could use [Keychain Sharing](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps) for that. It requires turning on the App Groups capability.

**Comment by TarekSalama** [comment]
Thanks for replying!

I know that I can use a shared Keychain but would that make the Auth0's container shareable? I believe it wouldn't. I already share the access token however I am not sure how I can get the app extension to renew the token via the refresh token.

Thanks again

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Widcket** [comment]
@TarekSalama just replied to the support ticket. Let me know if this issue can be closed.

**Comment by TarekSalama** [comment]
@Widcket Yes I got the email. Thanks for putting all the effort to make it clear!

**Comment by hsandhu** [comment]
@Widcket is it possible for you to provide the details of the support ticket reply here? I'm running in to a similar issue with iOS app extensions.
