### ISSUE TITLE
Auth0's Result Extensions Available Publicly

### ISSUE THREAD

**Issue by jshier** [auth0/Auth0.swift#469]
### Describe the problem

In 1.33.0, extensions to Swift's `Result` were added with public visibility. These conflict with `Result`'s enum cases directly when used as a method reference.

### What was the expected behavior?

Auth0 shouldn't cause failures in existing code.

### Reproduction

Pre 1.33.0, code like this worked fine in my app:

```swift
let optional: String? = "string"
let result = option.map(Result.success)
```

It now fails with an ambiguity error due to Auth0's extensions, which will conflict when not full defining the method reference.

This can be worked around:

```swift
let optional: String? = "string"
let result = option.map(Result.success(_:))
```

But it's generally bad practice for frameworks to offer unqualified extensions of system types.

### Environment

- **Version of `Auth0.swift` used:** 1.33.0
- **Version of iOS/macOS/tvOS/watchOS:** Any
- **Version of Xcode:** 12.4 / 12.5

**Comment by Widcket** [comment]
Hi @jshier, thanks for raising this. The library had its own Result enum that predated the Swift 5 one, and conflicted with it. That has been raised in the past: #317 #433. Given that we are preparing a new major version of this library that will, among other things, only use Swift's Result type, we accepted a recent PR that deprecated the existing API and shimmed it when using Swift >= 5.0. We apologize for any inconveniences this has caused.

**Comment by valerianb** [comment]
This shim is causing me issues too. I have Result instances where I specialise the Error type and Auth0's shim breaks this ...

Had to overwrite the shim:
`typealias Result<Success, Failure> = Swift.Result<Success, Failure> where Failure: Error`

**Comment by Widcket** [comment]
Hi @jshier @valerianb, Auth0.swift [2.0.0-beta.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0-beta.0) is out now. It removes the custom `Result` type and its shims, using the Swift 5 `Result` type instead. See https://github.com/auth0/Auth0.swift/issues/637 for more information.

**Comment by Widcket** [comment]
The [2.0.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0) release is out now. It only uses the Swift 5 result type.
Please check the [Migration Guide](https://github.com/auth0/Auth0.swift/blob/master/V2_MIGRATION_GUIDE.md) for more information on how to update your apps.
