### ISSUE TITLE
Can't find a logout / clearSession method on Auth0 without using WebAuth

### ISSUE THREAD

**Issue by brett-eugenelabs** [auth0/Auth0.swift#470]
### Describe the problem

I can't find a way to log the user out using just the APIs (Not WebAuth) in Auth0.swift
I am logging in using password less flow in a Native SwiftUI View and it works well:

        Auth0
           .authentication(clientId: "XXXXXXXXXXXXXXXXXXXXX", domain: auth0Domain)
           .startPasswordless(email: "brett@gmail.com", type: .iOSLink)
           .start { result in
                completion?(result)
           }

        Auth0
            .authentication(clientId: "XXXXXXXXXXXXXXXXXXXXX", domain: auth0Domain)
            .login(email: emailAddress,
                      code: code,
                      audience: "https://secretapi.com",
                      scope: "openid profile offline_access")
            .start { result in
                completion?(result)
            }

But there is no corresponding logout that I can find in the code unless I use WebAuth()

       Auth0
            .webAuth(clientId: "XXXXXXXXXXXXXXXXXXXXX", domain: auth0Domain)
            .useLegacyAuthentication(withStyle: .fullScreen)
            .clearSession(federated:false){ result in
               completion?(result)
            }

### What was the expected behavior?

To find a logout or clearSession method on Auth0 or Auth0.authentication() without having to use .webAuth()

### Environment

- Auth0.swift 1.330
- iOS 14.4
- Xcode 12.4

**Comment by JanC** [comment]
Hi,
Do you store the Credentials somewhere? 

```swift
   Auth0
        .authentication( ...)
        .login( ... )
        .start { result in
            completion?(result)
        }
```
The `result` is `Auth0.Result<Auth0.Credentials>` and the credentials are usually stored using the `credentialsManager.store(credentials: credentials)`

Then you can use `credentialsManager.clear()` to clear them.

**Comment by brett-eugenelabs** [comment]
Hi Janc,

Thanks for quick reply.

Yes I do, I do my own logout using the Keychain in the completion block, I will post it below. However in WebAuth it makes an API call so I assumed there is something extra I need to do here. But maybe not, considering there is no call for it.

Full snippet using WebAuth:
         Auth0
            .webAuth(clientId: "XXXXXXXXXXXXXXXXXXXXX", domain: auth0Domain)
            .useLegacyAuthentication(withStyle: .fullScreen)
            .clearSession(federated:false){
                switch $0{
                case true:
                    DispatchQueue.main.async {
                        withAnimation() { self.logout() }
                        completion?(.success(true))
                    }
                case false:
                    DispatchQueue.main.async {
                        withAnimation() { self.logout() }
                         completion?(.failure(StringError(message: "Not logged out on Auth0 server")))
                    }
                }
            }

    fileprivate func logout() {
        assert(Thread.current == .main)
        
        self.encryptedStore.reset() 
        username = nil
        jwtToken = nil
        idToken = nil
        refreshToken = nil
        scope = nil
        isLoggedIn = false
    }

**Comment by JanC** [comment]
I'm not so familiar with the web auth but I also use the OTP login and to logout the user, I simply clean the credentials on the device without any calls to the Auth0 api.

The OTP tokens have a limited lifetime so there are invalidated if not renewed.

So basically to login:

```swift
        authentication
            .login( ... )
            .start { result in
                switch result {
                case .success(let credentials):
                    // store the token here
                    credentialsManager.store(credentials: credentials)
                case .failure(let error):
                    
                }
            }
```

and to logout:

```swift
credentialsManager.clear()
```

**Comment by Widcket** [comment]
That is correct. If you're not using WebAuth, performing logout involves just removing the credentials from the device, because there are no cookies to clear.

**Comment by brett-eugenelabs** [comment]
Thank you Wicket, appreciate the clarification.
