### ISSUE TITLE
Import project on swift package manager library

### ISSUE THREAD

**Issue by amadeu01** [auth0/Auth0.swift#471]
### Describe the problem

Can not build the library 

```
Undefined symbols for architecture x86_64:
  "_SecKeyRawVerify", referenced from:
      -[A0RSA verify:signature:] in A0RSA.o
  "_SecKeyGetBlockSize", referenced from:
      -[A0RSA sign:] in A0RSA.o
  "_kSecRandomDefault", referenced from:
      -[A0SHA256ChallengeGenerator init] in A0ChallengeGenerator.o
  "_SecKeyRawSign", referenced from:
      -[A0RSA sign:] in A0RSA.o
  "_SecRandomCopyBytes", referenced from:
      -[A0SHA256ChallengeGenerator init] in A0ChallengeGenerator.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### What was the expected behavior?

Be able to build the project

### Reproduction
- Create a new SPM project as a library for iOS
- Add the following 

```
.package(
            name: "Auth0",
            url: "https://github.com/auth0/Auth0.swift.git",
            .exact("1.33.0")
        )

.target(
            name: "Common",
            dependencies: [
               // ...
                "Auth0"
            ],
            resources: [.process("Resources")]
        ),
```

- 

**Can the behavior be reproduced using the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample)?**

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log information and HTTP request traces (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots/GIFs

### Environment

> Please provide the following:

- **Version of `Auth0.swift` used:** `.exact("1.33.0")`
- **Version of iOS/macOS/tvOS/watchOS:** `iOS`
- **Version of Xcode:** 12.4

**Comment by Widcket** [comment]
Hi @amadeu01, apologies for the delayed response. I just tried creating a framework project, using SPM to add Auth0.swift and the framework compiles successfully:

<img width="676" alt="Screen Shot 2021-06-24 at 08 22 19" src="https://user-images.githubusercontent.com/5055789/123254830-83cf9f80-d4c5-11eb-9fb0-f650e0eec109.png">

Are you still having this issue?

**Comment by Widcket** [comment]
@amadeu01 seems you no longer are having this issue. I'll close this one, please ping me if you'd like to reopen it.
