### ISSUE TITLE
Placement of explanation for .parameters() in Readme is confusing

### ISSUE THREAD

**Issue by drewhsu86** [auth0/Auth0.swift#472]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/responsible-disclosure-policy) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

I was trying to look up how to pass parameters to the authorize call. 

I wasn't able to find it in the Configuration section (https://github.com/auth0/Auth0.swift#configuration). Turns out it is mentioned in the Bot Detection section (https://github.com/auth0/Auth0.swift#bot-detection).

Relevant snippet: 
```
.parameters(["login_hint": email, "screen_hint": "signup"]) 
```

This can be very confusing since I was helping a customer who was using Auth0.swift and it wasn't obvious to them how to do this.

### What was the expected behavior?

I expected to find all the options that can be passed to the Auth0 instance in or near the Configuration section of the Readme.

### Reproduction

N/A 

### Environment

This Github Repo's Readme.md

**Comment by Widcket** [comment]
Hi @drewhsu86, apologies for the delay.
The `screen_hint`: `signup` parameter is relatively new and specific to New Universal Login. AFAIK, achieving the same with Classic Lock is more involved. It was never really featured on the README, and ended up being mentioned in the Bot Protection section, though that is not meant to be the actual documentation of the signup feature itself.
Now that New Universal Login is the default for new tenants, we can revisit this and properly document in on the README.
