### ISSUE TITLE
Transactional guarantees for CredentialsManager

### ISSUE THREAD

**Issue by groue** [auth0/Auth0.swift#473]
Hello,

### Describe the problem you'd like to have solved

[CredentialsManager](https://auth0.com/docs/libraries/auth0-swift/save-and-refresh-jwt-tokens) is a very handy ready-made tool. However, it makes it difficult to make sure both credentials AND another piece of data are persisted or read from disk with transactional guarantees.

In particular, I would like to store credentials with a stable ID that identifies the user. No token found in `Credentials` is able to fulfill this need.

The purpose of this user ID is to help my application strictly isolate users' data, and particularly manage my local cache. In no way a network request authenticated with Alice's access token should be optimized by looking in Bob's cache. In no way the result of this network request should be stored in Bob's cache.

If credentials and user ID are not persisted or read together, with transactional guarantees, it is possible that both pieces of information end up out of sync. And then the above bugs can happen.

`CredentialsManager` already performs transactional accesses to credentials, by using NSKeyedArchiver and NSKeyedUnarchiver in order to store and read credentials as a whole. This is very good. We just need one more step:

### Describe the ideal solution

Please allow CredentialsManager users to provide a userInfo dictionary that would be stored and read *at the same time* as the credentials:

```diff
 public func store(credentials: Credentials) -> Bool
+public func store(credentials: Credentials, userInfo: [String: Any]) -> Bool

 public func credentials(
     withScope scope: String? = nil, 
     minTTL: Int = 0, 
     callback: @escaping (CredentialsManagerError?, Credentials?) -> Void)
+public func extendedCredentials(
+    withScope scope: String? = nil, 
+    minTTL: Int = 0, 
+    callback: @escaping (CredentialsManagerError?, Credentials?, [String: Any]?) -> Void)
```

## Alternatives and current work-arounds

Current work-around involves duplicating CredentialsManager in application code, and modify it in order to provide the needed extra transactional guarantees.

The problem with this duplication of code is that when Auth0 is upgraded and CredentialsManager is improved, application code is not.

Thanks for reading!

**Comment by groue** [comment]
This feature request may be related to #437, but I'm not quite sure.

**Comment by groue** [comment]
> If you have not received a response for our team (apologies for the delay) and this is still a blocker, please reply with additional information or just a ping.

Ping!

**Comment by Widcket** [comment]
Hi @groue, apologies for the delay.

This is not a feature request we want to proceed with.

We already provide a stable user ID (the `sub` claim from the ID Token) that you can map to your own. We recently added a `user` [property](https://github.com/auth0/Auth0.swift/blob/master/Auth0/CredentialsManager.swift#L58) to the CredentialsManager, that parses the ID Token and returns a `UserInfo` instance, which has a `sub` [property](https://github.com/auth0/Auth0.swift/blob/master/Auth0/UserInfo.swift#L32).

Alternatively, you can also add your own ID via a Rule as a custom claim.

**Comment by groue** [comment]
Thank you very much @Widcket. TIL about the `sub` stable user ID, and that's all I needed 👍
