### ISSUE TITLE
Renew the User's Credentials never failed.. when access token already expired 

### ISSUE THREAD

**Issue by PraveenCodeSwift** [auth0/Auth0.swift#477]
self.credentialsManager.credentials { error, credentials in
    guard error == nil, let credentials = credentials else {
        // Handle Error
        // Route user back to Login Screen
    }
    // There is no need to store the credentials as you did in Login. The Credentials Manager will do this for you internally
    // Continue routing the user as authentication was a success
}

Link :https://auth0.com/docs/quickstart/native/ios-swift/08-touch-id-authentication#renew-the-user-s-credentials

I need get error when access token expired.. When i send same token our server will sending error message token expiry.. But  from Auth0 I am not getting expiry token error message.. please let me know it's bug or something i am doing wrong.. android code is working fine Auth0 Framework but in iOS only i am getting...

Please Help

**Comment by PraveenCodeSwift** [comment]
I am not able find where is error.. why i am not able get token expiry.. i have changed 3600 access token and refreesh token 120 sec.. still i am not able get error message from Auth0

**Comment by Widcket** [comment]
Hi @PraveenCodeSwift. 
Are you passing the `offline_access` scope to get a refresh token?
Are you using an audience value? If so, did you enable refresh tokens for that API in the Auth0 Dashboard? 

<img width="533" alt="Screen Shot 2021-06-23 at 18 00 25" src="https://user-images.githubusercontent.com/5055789/123167446-eb95d400-d44c-11eb-9b9e-d0ca6ba0ce05.png">

**Comment by Widcket** [comment]
@PraveenCodeSwift looks like your issue is solved, I'll close this one. Please ping me if you'd like to reopen.
