### ISSUE TITLE
[Memory Issues] 2 instances of NSCFString leaked

### ISSUE THREAD

**Issue by mdb1** [auth0/Auth0.swift#479]
### Describe the problem
While debugging the memory graph of my application I found that the Auth0 repository has 2 instances of _NSCFString leaks
![Screen Shot 2021-06-16 at 14 03 13](https://user-images.githubusercontent.com/5333984/122262685-0a73f380-ceac-11eb-89b1-a2c3b407834b.png)

## The first one is in the `Auth0#plistValues` method

| Backtrace | Method |
| - | - |
|![Screen Shot 2021-06-16 at 14 03 27](https://user-images.githubusercontent.com/5333984/122263075-6a6a9a00-ceac-11eb-810f-aebd5fac559a.png)|![Screen Shot 2021-06-16 at 14 03 44](https://user-images.githubusercontent.com/5333984/122263086-6b9bc700-ceac-11eb-9133-ce63e80fadfb.png)|

## The second one can be found on the `NSData+URLSafe#a0_encodeBase64URLSafe()` method

| Backtrace | Method |
| - | - |
|![Screen Shot 2021-06-16 at 14 04 03](https://user-images.githubusercontent.com/5333984/122263198-8bcb8600-ceac-11eb-9c0d-bbe688f1bb41.png)|![Screen Shot 2021-06-16 at 14 04 14](https://user-images.githubusercontent.com/5333984/122263204-8cfcb300-ceac-11eb-9e75-dbd3443ecb8f.png)|

### What was the expected behavior?
The expected behavior is to avoid having memory leaks

### Reproduction

1. Open an app that uses the Auth0 pod with an authenticated user
2. Open Xcode's `Debug memory graph` feature (Follow instructions [here](https://medium.com/@xcadaverx/locating-the-source-of-a-memory-leak-712667bf8cd5))
3. See the memory leaks in the 2 methods mentioned above

### Environment

- **Version of `Auth0.swift` used:** `1.32.0`
- **Version of iOS/macOS/tvOS/watchOS:** `iOS 14.5 (18E182)`
- **Version of Xcode:** `Version 12.5 (12E262)`

Let me know if I can help in any way to find the solution to these leaks 😄

**Comment by Widcket** [comment]
Hi @mdb1, I've taken a look at these in the past, and the allocations ended up being released later. 

<img width="813" alt="Screen Shot 2021-06-30 at 22 36 45" src="https://user-images.githubusercontent.com/5055789/124051954-da703880-d9f3-11eb-8d5c-c3bf85255d72.png">

Note that the `Telemetry` instance holds to the string returned by `a0_encodeBase64URLSafe `.
I will close this one, please ping me if you'd like to reopen.
