### ISSUE TITLE
Improve documentation about refreshtokens when using MFA

### ISSUE THREAD

**Issue by Appelg** [auth0/Auth0.swift#480]
### Describe the problem you'd like to have solved
Improve documentation

### Describe the ideal solution
It would be appreciated if you could inform users about how to deal with MFA when trying to use refresh tokens. 

I finally found this thread: 
https://community.auth0.com/t/how-to-bypass-mfa-for-refresh-token-requests/26008

I would like to say it wasn't obvious that this had to be done.

**Comment by Widcket** [comment]
Hi @Appelg, thanks for the suggestion. However it is not something specific to this SDK, so I'm afraid that documentation does not belong in this repo's README.
