### ISSUE TITLE
Support various LAPolicy to enable fallback to pin-code when validating Biometric

### ISSUE THREAD

**Issue by krodak** [auth0/Auth0.swift#485]
### Describe the problem you'd like to have solved

Currently, if Face Id / Touch Id fails and iOS displays "Enter passcode" UI, tapping on **`Enter password`** triggers instant biometrics failure with `CredentialsManagerError.touchFailed(Error)`

<img src="https://user-images.githubusercontent.com/1955364/125054000-051e5900-e0a6-11eb-86f2-9eba704bfda6.jpg" width="320">

This happens because Auth0 favours `LAPolicy.deviceOwnerAuthenticationWithBiometrics`  evaluation policy within `BioAuthentication`. 

### Describe the ideal solution

We should be able to customise `BioAuthentication` with either `LAPolicy.deviceOwnerAuthenticationWithBiometrics` or `LAPolicy.deviceOwnerAuthentication` as an evaluation policy

As per Apple's documentation **`LAPolicy.deviceOwnerAuthentication`**
> /// Device owner is going to be authenticated by biometry or device passcode.
    ///
    /// @discussion Biometric or passcode authentication is required. If the biometry is available, enrolled and
    ///             not locked out, users are asked for it first. Otherwise they are asked to enter device
    ///             passcode. If passcode is not enabled, policy evaluation will fail with LAErrorPasscodeNotSet.
    ///
    ///             Biometric authentication dialog behaves similarly as the one used by
    ///             LAPolicyDeviceOwnerAuthenticationWithBiometrics. However, instead of "Enter Password"
    ///             button there is "Enter Passcode" button which, when tapped, switches the authentication
    ///             method and allows users to enter device passcode.
    ///
    ///             Passcode authentication will get locked after 6 unsuccessful attempts with progressively
    ///             increased backoff delay.

Diving into code, this would mean that we are able to have `validateBiometric` as follow:

```swift
 @available(iOS 9.0, macOS 10.15, *)
    func validateBiometric(callback: @escaping (Error?) -> Void) {
        self.authContext.evaluatePolicy(LAPolicy.deviceOwnerAuthentication, localizedReason: self.title) {
            guard $1 == nil else { return callback($1) }
            callback($0 ? nil : LAError(LAError.authenticationFailed))
        }
    }
```

Visualisation of expected flow:

https://user-images.githubusercontent.com/1955364/125054187-39921500-e0a6-11eb-97f9-d9cb40b478d7.MOV

### Alternate solution

I couldn't find one as there is no possibility to use constructor / method injection to customise `enableBiometrics` in `CredentialsManager` or override `credentials(withScope` that calls to `BioAuthentication.validateBiometric`. 

If there is any workaround that would use some other approach, that would be great 🙏 

### Additional context

Let's go through example solution (happy to provide PR for that) that would enable to customise evaluationPolicy.

Updated `BioAuthentication`:

```swift
#if WEB_AUTH_PLATFORM
import Foundation
import LocalAuthentication

struct BioAuthentication {

    private let authContext: LAContext
    private let evaluationPolicy: LAPolicy

    let title: String
    var fallbackTitle: String? {
        get { return self.authContext.localizedFallbackTitle }
        set { self.authContext.localizedFallbackTitle = newValue }
    }

    @available(iOS 10.0, macOS 10.15, *)
    var cancelTitle: String? {
        get { return self.authContext.localizedCancelTitle }
        set { self.authContext.localizedCancelTitle = newValue }
    }

    @available(iOS 9.0, macOS 10.15, *)
    var available: Bool {
        return self.authContext.canEvaluatePolicy(evaluationPolicy, error: nil)
    }

    init(authContext: LAContext, evaluationPolicy: LAPolicy, title: String, cancelTitle: String? = nil, fallbackTitle: String? = nil) {
        self.authContext = authContext
        self.evaluationPolicy = evaluationPolicy
        self.title = title
        if #available(iOS 10.0, macOS 10.15, *) { self.cancelTitle = cancelTitle }
        self.fallbackTitle = fallbackTitle
    }

    @available(iOS 9.0, macOS 10.15, *)
    func validateBiometric(callback: @escaping (Error?) -> Void) {
        self.authContext.evaluatePolicy(evaluationPolicy, localizedReason: self.title) {
            guard $1 == nil else { return callback($1) }
            callback($0 ? nil : LAError(LAError.authenticationFailed))
        }
    }

}
#endif
```

Changes required in `CredentialsManager`:

```swift
#if WEB_AUTH_PLATFORM
    public mutating func enableBiometrics(withTitle title: String, cancelTitle: String? = nil, fallbackTitle: String? = nil, evaluationPolicy: LAPolicy = LAPolicy.deviceOwnerAuthenticationWithBiometrics) {
        self.bioAuth = BioAuthentication(authContext: LAContext(), evaluationPolicy: evaluationPolicy, title: title, cancelTitle: cancelTitle, fallbackTitle: fallbackTitle)
    }
    #endif
```

I'd be happy to provide PR / Draft for that 🙏

**Comment by Widcket** [comment]
Hi @krodak, thanks for raising this in such a detailed and clear way. We'd happily take a PR, the approach you suggested is fine.

**Comment by krodak** [comment]
Thanks @Widcket, I've added a PR #486 , so I'll close that one 🙏
