### ISSUE TITLE
Deprecations in latest release

### ISSUE THREAD

**Issue by vaibhav-athon** [auth0/Auth0.swift#488]
The latest pods (1.34.0) contains deprecations. Would love to see those deprecations gone and new methods in place of them

Please find attached screenshots

![Screenshot 2021-07-17 at 10 36 11 AM](https://user-images.githubusercontent.com/84004318/126026460-2d9da690-2aef-423d-9dd8-50bd1997bb68.png)

![Screenshot 2021-07-17 at 10 36 32 AM](https://user-images.githubusercontent.com/84004318/126026463-73c0d431-ead6-492b-ad2d-12f3bfab9bcc.png)

**Comment by Widcket** [comment]
Hi @vaibhav-athon, these methods have been deprecated a long time ago.
We can't remove them yet, as doing so would be a breaking change; we'll remove them in the next major of the library.

**Comment by Widcket** [comment]
@vaibhav-athon Auth0.swift [2.0.0-beta.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0-beta.0) is out now, with all the deprecated methods removed (and no warnings!). See https://github.com/auth0/Auth0.swift/issues/637 for more information.

**Comment by Widcket** [comment]
The [2.0.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0) release is out now. Please check the [Migration Guide](https://github.com/auth0/Auth0.swift/blob/master/V2_MIGRATION_GUIDE.md) for more information on how to update your apps.
