### ISSUE TITLE
Application killed while renewing token results in 'Failed exchange - reused refresh token ' error

### ISSUE THREAD

**Issue by Abhijit-Kayande** [auth0/Auth0.swift#490]
### Problem description
I am renewing the access token using the following method 
```
Auth0
    .authentication()
    .renew(withRefreshToken: refreshToken)
    .start { result in
        switch result {
        case .success(let credentials):
            print("Obtained new credentials: \(credentials)")
        case .failure(let error):
            print("Failed with \(error)")
        }
    }
```

When this method is initiated and if the user kills the application before getting the response the next time user launches the application this method gives error "Failed Exchange - Unsuccessful Refresh Token exchange, reused refresh token detected".
I have enabled the Refresh token rotation in the auth0 application settings.

The renewal of the token happens in the background without user's knowledge. So in this case if a user kills the application when the renewal is happening then in the next launch user may need to login again which is not a good user experience.

Is this behaviour handled in the auth0 swift library? Do we need to implement some additional functionality to support the renewing of the token in background?

### Environment

- **Version of `Auth0.swift` used: 1.33.0**
- **Version of iOS/macOS/tvOS/watchOS: 13 and above**
- **Version of Xcode: 12.4**

**Comment by Widcket** [comment]
Hi @Abhijit-Kayande, when exchanging the current refresh token for new credentials, the new refresh token will be delivered in the response along with the new credentials. Therefore if the app is killed before receiving and processing the response, that new refresh token will be lost. This is not unlike the user killing the app while logging in, before the final response (containing the credentials) reaches the app. In both cases, the user will have to login again.

**Comment by Abhijit-Kayande** [comment]
Hello @Widcket Thanks for the reply.
In my auth0 settings the value for access token expiration is 300 seconds and for refresh token absolute lifetime is about 1 year. So does this mean that if my access token expires after every 300 seconds I will get a new refresh token as well?

Also for my case can you please suggest what are the best practices to renew the token so that user is not forced to log back in. How we can handle these scenarios where app may get killed while renewing the token.

**Comment by Widcket** [comment]
If you have your access token to expire in 300 seconds *and* you have Refresh Token Rotation enabled, yes you'll get a new refresh token with every credential renewal. However, 300 seconds is too low a value for the access token duration (by default it's 86400 seconds -> 1 day). The lowest this value, the more frequently it's going to have to be renewed, thus the more likely this scenario you mention might become a problem.
If you set a higher value while making sure to renew the token whenever the user is in the middle of an operation (and thus less likely to suddenly kill the app), then this might not be much of a problem. But that depends on your app's usage patterns.

**Comment by Widcket** [comment]
Also, instead of calling `renew` manually, you can use the CredentialsManager class.
It allows to securely store the tokens in the Keychain and will automatically renew them when fetching them, if they're expired or close to expiring (check out the minTTL parameter).
See https://github.com/auth0/Auth0.swift#credentials-management-utility

**Comment by Abhijit-Kayande** [comment]
@Widcket Thank you for this information. I tried using the CredentialsManager class but with this approach while calling any API we need to fetch the credentials from .credentials method. And if there are multiple API calls within short amount of time and the .credentials method is called simultaneously then there is still a risk of getting 'Failed exchange - reused refresh token' method.

**Comment by Widcket** [comment]
@Abhijit-Kayande neither the Credentials Manager's `credentials` method nor `renew` are thread-safe, so in both cases, you'd need to use a serial queue to avoid a race condition with the token exchange.

**Comment by Widcket** [comment]
@Abhijit-Kayande seems like your question has been answered. I'll close this issue, please let me know if you have any further questions.

**Comment by Widcket** [comment]
Hi @Abhijit-Kayande, Auth0.swift [2.0.0-beta.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0-beta.0) is out now. It does thread-safe token renewals from the CredentialsManager's `credentials` method. See https://github.com/auth0/Auth0.swift/issues/637 for more information.
