### ISSUE TITLE
NSKeyedUnarchiveFromData should be removed.

### ISSUE THREAD

**Issue by alexrrouse** [auth0/Auth0.swift#491]
### Describe the problem

Move away from NSKeyedUnarchiver for unarchiving data.
`'NSKeyedUnarchiveFromData' should not be used to for un-archiving and will be removed in a future release` 
is a log message that gets output from the CredentialsManager in various places while getting the data out of the storage.

### What was the expected behavior?

The underlying store of the data should be updated to a different method to avoid deprecations and to avoid a future problem in the SDK

### Reproduction

Use the CredentialsManager to store/read credentials
Adding a Symbolic Breakpoint on `[NSKeyedUnarchiver unarchiveObjectWithData:]` will help locate instances where it is used.
### Environment

- **Version of `Auth0.swift` used: 1.35.0
- **Version of iOS:14
- **Version of Xcode:12.5.1

**Comment by Widcket** [comment]
Hi @alexrrouse, I just tried to reproduce this, storing the credentials and then retrieving them with `.credentials()` but was unsuccessful. 

<img width="275" alt="Screen Shot 2021-08-02 at 21 39 51" src="https://user-images.githubusercontent.com/5055789/127940253-976be877-030e-4a8e-9e1e-a46bf6ab0216.png">

Are you able to reproduce this in an isolated context, e.g. our [Quickstart sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/00-Login)?

**Comment by Widcket** [comment]
Also, I was not able to find `NSKeyedUnarchiveFromData` among the logs:

<img width="1238" alt="Screen Shot 2021-08-02 at 21 43 11" src="https://user-images.githubusercontent.com/5055789/127940478-5dee0f84-2034-499a-acb0-a168fd9e0509.png">

**Comment by Widcket** [comment]
Hi @alexrrouse, I'll close this one for now. Please ping if you'd like to reopen.
