### ISSUE TITLE
Extend `renew()` and `credentials()` by parameters to pass in custom key-value pairs

### ISSUE THREAD

**Issue by konDeichmann** [auth0/Auth0.swift#493]
Hi there,

I have an issue related to renewing Credentials via the SDK.
While it is possible to set custom parameters on login/authentification - it is not while receiving credentials via `credentials(...)` nor by calling `renew(...)`.

In our use case, the App is required to renew Tokens on special events (user changes an internal state) and inform the authentification provider about changes the user made (via Parameters).

I would like to provide a PR where I extend `Request` with a similar approach we already have on `WebAuth`. That takes the object and adds parameters (in the case of `Request`: `payload`).

Also, it would be possible to directly pass those via `credentials(...)`

### Alternatives and current workarounds

Currently, I don't see a workaround nor an alternative solution.

### Context

Passing parameter using `renew(...)` is already implemented on Android.

**Comment by Widcket** [comment]
Hi @konDeichmann, thanks for raising this. Adding a method to `Request` sounds reasonable, similar to the one used by the Android SDK. I'd try to keep the terminology used across the SDK uniform and just call it `parameters`, like the param name used by some API client methods (e.g. `login(phoneNumber:code:audience:scope:parameters:`). You can add a similar param to `credentials`, with an empty dict as the default value.
Please make sure to add tests.
