### ISSUE TITLE
iTunesConnect Transporter errors on "rc" version string

### ISSUE THREAD

**Issue by larsacus** [auth0/Auth0.swift#50]
The iTunes transporter currently errors when processing an application using any of the RC versions (currently `1.0.0-rc4`). Currently using carthage to build the framework.

```
ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '1.0.0-rc.4' in the Info.plist file must be a period-separated list of at most three non-negative integers.
```

Manually (or using `plistbuddy`) changing the version of the framework's plist to 1.0.0 and rebuilding removes the error. I know this is "RC", but this was found when submitting our builds to TestFlight for internal testing.

**Comment by hzalaz** [comment]
Thanks for the warning will release stable soon and this will go away
