### ISSUE TITLE
Incomplete Logout event logged when calling `webAuth.useLegacyAuthentication().clearSession(federated: true)` 

### ISSUE THREAD

**Issue by drhaynes-wigglecrc** [auth0/Auth0.swift#504]
### Describe the problem

When logging out using `webAuth.useLegacyAuthentication().clearSession(federated: true)`, the logout request completes without error, but the corresponding logout event is logged without all relevant details in the Auth0 backend management panel.

See screenshots of logs:

<img width="1425" alt="Screenshot 2021-09-20 at 13 50 22" src="https://user-images.githubusercontent.com/82872681/134008975-25f42e30-80c0-465e-979b-cbaebbb135ba.png">

Notice how the 'application' column is empty for the 'Success Logout' events.

Looking at a log item in detail shows partial correct details, but not full:

<img width="1425" alt="Screenshot 2021-09-20 at 13 50 31" src="https://user-images.githubusercontent.com/82872681/134009327-08f0295d-8c06-4385-b34e-501f749e4794.png">

Raw log text is as follows:

```
{
  "date": "2021-09-20T12:50:12.340Z",
  "type": "slo",
  "connection_id": "",
  "ip": "[redacted]",
  "user_agent": "Mobile Safari 14.1.0 / iOS 14.5.0",
  "details": {
    "allowed_logout_url": []
  },
  "hostname": "whitelabel-tst.eu.auth0.com",
  "user_id": "",
  "user_name": "",
  "log_id": "90020210920125017324309773532945136812677110201745145906",
  "_id": "90020210920125017324309773532945136812677110201745145906",
  "isMobile": true,
  "description": "User successfully logged out"
}
```

Notice how there is no `user_id` or `user_name` logged.

On inspecting the `Auth0.swift` source, I notice that the logger only appears to log on a webAuth logout call here: [https://github.com/auth0/Auth0.swift/blob/master/Auth0/MobileWebAuth.swift#L169](https://github.com/auth0/Auth0.swift/blob/master/Auth0/MobileWebAuth.swift#L169) which seems like it may not be triggered in all codepaths for all iOS versions, base on the availability checks. I'm not familiar with the logging setup, but perhaps this is related?

> Tell us about the behavior you expected to see

Expected to see the logout event with full information.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducible steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1: Configure Auth0.swift in an iOS app
- Step 2: Login using Universal Login
- Step 3: `Logout using webAuth.useLegacyAuthentication().clearSession(federated: true)`
- Step 4: Inspect Auth0 tenant logs

> Where applicable, please include:

> - `clientId` and `domain` (these are publicly available)

clientId: `obRJ2TOk4A0fmsaJgzP8syiLk1qZKvPX`
Domain: `whitelabel-tst.eu.auth0.com`

> - Screenshots/GIFs

See above.

### Environment

> Please provide the following:

- **Version of `Auth0.swift` used:** `1.35.0`
- **Version of iOS:** 14.5 (Simulator)
- **Version of Xcode:** 12.5.1

**Comment by Widcket** [comment]
Hi @drhaynes-wigglecrc, thanks for raising this.
The Auth0.swift logger is unrelated to the tenant logs. It merely prints to the console: https://github.com/auth0/Auth0.swift/blob/main/Auth0/Logger.swift#L36
I'd suggest to raise a support ticket about the tenant logs. I'll close this issue, as it is not related to the SDK.
