### ISSUE TITLE
Logout SSO issue in iOS 12 when using Universal Login

### ISSUE THREAD

**Issue by mirkojustiniano** [auth0/Auth0.swift#506]
### Describe the problem

Hi, we're using Universal Login with `useEphemeralSession` to disable SSO in iOS 13+. 

However we also need to support iOS 12 and the issue we are experiencing is that when the access token expires our app forces the user to logout (since we need a valid access token to keep using the app and keep making API requests), and because SSO is enabled Apple shows the SSO alert that the user can cancel. When the user cancels apple's SSO alert, `clearSession` fails, but because of our force logout flow the user is back at the login screen, and then if the user taps login, `webAuth.useEphemeralSession.start` is called, but since the user's session is alive according to auth0, then the user doesn't have to enter credentials again and is logged in automatically. We also have this issue when the user manually taps logout which triggers our logout flow, if then the user taps cancel in apple's SSO alert, the logout happens locally but not in auth0's session.

### What was the expected behavior?

We need to be able to force the user to logout without being able to have the user cancel `clearSession`, so that when the user tries to login again, then has to enter credentials + get MFA challenged again on iOS 12, but because SSO is enabled we are unable to do so.

### Environment

- **Version of `Auth0.swift` used:** 1.35.0
- **Version of iOS/macOS/tvOS/watchOS:** iOS 12
- **Version of Xcode:** Xcode 13

**Comment by Widcket** [comment]
Hi @mirkojustiniano, thanks for raising this.
To force the login screen on iOS 12, you can use `.parameters(["prompt": "login"])`. This will make the login screen show up even if `clearSession` was not called and the cookie is still present. So in this case it will be enough to simply clear the credentials from the app.

**Comment by mirkojustiniano** [comment]
Thank you @Widcket for your response! This worked out well. One last question regarding this issue... is there a way, maybe another method in the SDK that I haven't think about, to end or clear the session - maybe without web auth - so that it doesn't trigger the web view or apple's SSO warning? The reason I ask is that by using `.parameters(["prompt": "login"])` I am seeing the credentials being required as desired, but we also have MFA rules enabled and when the user cancels the Apple SSO warning, gets logged out and then enters credentials, he does not get MFA challenged. I'm guessing because the session is technically still "alive". Thanks again!

**Comment by Widcket** [comment]
@mirkojustiniano on a second thought, if the user cancels the prompt, the SDK will fail with `userCancelled`, so you should be able to handle the error and not log out the user.

**Comment by Widcket** [comment]
Regarding your question, there's no way to clear the session (remove the cookie) without web auth. You might want to check your rules code and MFA config, to ensure it always gets triggered.

**Comment by mirkojustiniano** [comment]
Thank you @Widcket 👍
