### ISSUE TITLE
Failed to update to 1.37.0 with Carthage

### ISSUE THREAD

**Issue by lihao6485** [auth0/Auth0.swift#516]
Hi,

I have failed to update Auth0 SDK from 1.36.0 to 1.37.0 on Carthage. I have attached the xcodebuild log.

### What was the expected behavior?

Expected to update to 1.37.0 on Carthage.

### Reproduction

run:
sh carthage-xcode13.sh update --platform ios --cache-builds --new-resolver

carthage-xcode13.sh is the workaround script for Carthage to support M1 Macbook.

- **Version of Xcode: 13**

[carthage-xcodebuild.log](https://github.com/auth0/Auth0.swift/files/7335210/carthage-xcodebuild.log)

**Comment by Widcket** [comment]
The workaround script is not necessary anymore with the latest version of Carthage.
