### ISSUE TITLE
Unable to Build 1.37.0 Using Carthage 0.38

### ISSUE THREAD

**Issue by steve-wiggle** [auth0/Auth0.swift#519]
### Describe the problem

Attempting to build the Auth0.swift library using Carthage 0.38 results in a build failure.

### What was the expected behavior?

Building Auth0.swift should complete successfully.

### Reproduction

- Step 1 - Create a Cartfile containing `github "auth0/Auth0.swift"`
- Step 2 - Run `carthage bootstrap --use-xcframeworks`

<img width="682" alt="Screenshot 2021-10-14 at 10 45 00" src="https://user-images.githubusercontent.com/83215017/137293439-55fe2ee5-831f-4ea1-90be-41ef67e5bcad.png">

The build fails with the following error:
```
/Users/stephenanthony/Desktop/auth0/Carthage/Checkouts/Auth0.swift/Auth0/CredentialsManager.swift:24:8: error: no such module 'SimpleKeychain'
import SimpleKeychain
       ^
```

Opening the checked out Auth0 project appears to show that the Auth0 framework targets do not link SimpleKeychain or JWTDecode:
<img width="866" alt="Screenshot 2021-10-14 at 10 28 13" src="https://user-images.githubusercontent.com/83215017/137292877-be26cf34-2619-412d-a3ec-5640e0dec737.png">

This could explain why the build fails to link.

### Environment

- **Version of `Auth0.swift` used: 1.37.0**
- **Version of macOS: 11.6**
- **Version of Xcode: 13.0 (13A233)**

**Comment by Widcket** [comment]
The fix is now out in [v1.37.1](https://github.com/auth0/Auth0.swift/releases/tag/1.37.1).
