### ISSUE TITLE
Problem using the library with Carthage and Swift 3

### ISSUE THREAD

**Issue by jacobarvidsson** [auth0/Auth0.swift#54]
I have two problems:
1. Using: github "auth0/Auth0.swift" 1.0.0, pulls an older version of the repository, with the swift 2.3 support, which doesn't work with Swift 3.0. When I try an upload to iTunes Connect I get an error saying the framework does not support my version of Swift. Changing to github "auth0/Auth0.swift" "master" seems to work, which brings me to problem 2.
2. I get the following error message:
<img width="578" alt="screen shot 2016-09-29 at 11 24 56" src="https://cloud.githubusercontent.com/assets/3352203/18948658/409da742-8638-11e6-8227-50b3c4470117.png">

In the plist of the project the bundle version is set to 1.0.0-rc.4 which is unsupported:
<key>CFBundleShortVersionString</key><string>1.0.0-rc.4</string>

Is this a bug or am I suppose to use another string in my Cartfile to install the framework with support for Swift 3?

**Comment by hzalaz** [comment]
Not sure what `1.0.0` is since we haven't released it yet. The iTunes connect issues can be solved by changing the info.plist of the framework since it has the version of the library and apple won't allow non numeric version numbers. This will get sorted when we release the 1.0.0 version

**Comment by jacobarvidsson** [comment]
So what version is the latest version that supports Swift 3? In your readme it says:
github "auth0/Auth0.swift" "1.0.0"

**Comment by hzalaz** [comment]
https://github.com/auth0/Auth0.swift/releases

**Comment by jacobarvidsson** [comment]
I missed that the 1.0.0 hasn't been released yet (it wasn't really clear from the readme). The last issue(#50) in the issuetracker could also have been left open until 1.0.0 is released , since it was actually the solution to this problem.
