### ISSUE TITLE
NSKeyedUnarchiver.unarchivedObject crash

### ISSUE THREAD

**Issue by gitMartynas** [auth0/Auth0.swift#541]
Recently I changed deployment target of a project to 12.0.

After building a project, noticed a new warning: 'unarchiveObject(with:)' was deprecated in iOS 12.0: Use +unarchivedObjectOfClass:fromData:error: instead. 

Also see image attached below
<img width="1169" alt="Screenshot 2021-11-09 at 18 48 35" src="https://user-images.githubusercontent.com/9766094/140974847-f2736f76-1196-40d2-836f-cf2090471bf4.png">

I changed deprecated code into new one, but it crashes. Error message:

Thread 27: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=4864 "value for key 'expiresIn' was of unexpected class 'NSDate' (0x7fff862db798) [/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework].
Allowed classes are:
 {(
    "'A0Credentials' (0x105afe8b0)

Also see image attached below
<img width="1155" alt="Screenshot 2021-11-09 at 18 49 17" src="https://user-images.githubusercontent.com/9766094/140975467-373b9b49-f1b4-4ed4-9256-a271df271231.png">

Note: I'am aware that it crashes due to "try!", but I'am sure that there is a credentials object stored in keychain. If I use previous implementation, then it works good.

So I was wondering if this can be fixed on your end?

**Comment by Widcket** [comment]
Hi @gitMartynas, thanks for raising this.

We are currently working on a new major version of the SDK, and we'll be addressing that deprecation there. I'll close this issue, as that warning is already on our backlog. Please ping if you'd prefer to reopen, or have further questions.
