### ISSUE TITLE
Allow prefixed paths

### ISSUE THREAD

**Issue by todd-toast** [auth0/Auth0.swift#545]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/responsible-disclosure-policy) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We need our auth0 requests to hit an url that is prefixed by a specific path. For example: https://samples.auth0.com/authentication/

Any requests made by the auth0 would need to append to this path. For example: https://samples.auth0.com/authentication/oauth/token

Currently any base/prefixed path would get ignored when making a request. We have confirmed that the Android SDK already handles this properly.

I wasn't sure whether to file this as a bug or a feature request. In a way it could be both.

### Describe the ideal solution

The ideal solution would be to drop the leading `/` in URL(string, relativeTo)
For example on line 121:
```swift
let url = URL(string: "/oauth/token", relativeTo: self.url)!
```
The string part has a leading slash. Changing this to:
```swift
let url = URL(string: "oauth/token", relativeTo: self.url)!
```
Would fix this issue. However, I know that change would have the potential of breaking someone's current implementation of the library so another solution could be providing an additional option to allow a prefixed path.

## Alternatives and current work-arounds

I have made a proposal here #544. Another option could be passing in in a `URLConstructor` protocol. Then you could have a default one but you could also pass in a custom one. Another option could be providing the path explicitly as another parameter in the constructor.

### Additional context
From what I've found so far, there is no way around this at the moment. We are unable to provide a prefixed path until this is fixed or added.

**Comment by Widcket** [comment]
Hi @todd-toast, thanks for reporting this.
I was able to reproduce the issue. As we're working on a new major version of Auth0.swift right now, we'll be tackling this issue there. So I'll be closing this issue (and the PR) as this was just added to our backlog for the new major.

**Comment by Widcket** [comment]
@todd-toast Auth0.swift [2.0.0-beta.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0-beta.0) is out now, with support for prefixed paths. See https://github.com/auth0/Auth0.swift/issues/637 for more information.

**Comment by todd-toast** [comment]
> @todd-toast Auth0.swift [2.0.0-beta.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0-beta.0) is out now, with support for prefixed paths. See #637 for more information.

@Widcket Sorry for the late response. We tried this out recently in a staging/preproduction environment and it seems to be working great. It solves the issue with prefixed path. I don't have any other feedback at the moment, but will comment in #637 if anything comes up! Thanks for this change.

**Comment by Widcket** [comment]
The [2.0.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0) release is out now, with support for prefixed paths. Please check the [Migration Guide](https://github.com/auth0/Auth0.swift/blob/master/V2_MIGRATION_GUIDE.md) for more information on how to update your apps.
