### ISSUE TITLE
Delegation for Firebase

### ISSUE THREAD

**Issue by cflorion** [auth0/Auth0.swift#55]
Hi 🙂

I am using this library in an iOS App that needs authentication to Firebase with the id_token got by calling `FIRAuth.auth()?.signIn(withCustomToken:...)`

From what I understood I need to do the following steps in order to get this custom token:
- login to Auth0 with email and password to get the credentials via the `Auth0.authentication()        .login(...)` method
- with the credentials I get the profile via the `Auth0.authentication().tokenInfo(...) method`
- get the delegation token from the id_token in the profile

But I this library I cannot find any method to get a delegation token. Is this missing or I have misunderstood the logic ?

Thanks a lot 😉

**Comment by huguesbr** [comment]
Do you have any docs that explain this delegation on iOS?
Can't find any.

Trying to do firebase auth using auth0 but keep having "INVALID_CUSTOM_TOKEN" error from firebase...

**Comment by cocojoe** [comment]
Hi @huguesbr 

Please open a new issue if you wish to continue this.  However have you looked at:

https://auth0.com/docs/libraries/lock-ios/delegation-api

Thanks

**Comment by huguesbr** [comment]
@cocojoe thx!
