### ISSUE TITLE
Generic error message when using api.access.deny in action

### ISSUE THREAD

**Issue by mmuelder** [auth0/Auth0.swift#550]
### Describe the problem

Greetings!

When returning an error message via a Login-Action, we get a generic error message, instead of the one returned in the action.
![0d1266cd39cb46018c43622d2b8c3c5c3a2836c4](https://user-images.githubusercontent.com/5302657/142410561-f315c8fa-8f9b-44ff-8ab4-c7ac22f9dc8f.jpeg)

### What was the expected behavior?
Display of the custom error message returned in the action.

### Reproduction
We previously had a Rule that checks if a user is verified. If not, we returned
`return callback(new UnauthorizedError('our custom error message'));`
This worked just fine. We got ‘our custom error message’.

Now we wanted to switch to Actions. Inside the action we return the error like this:
`api.access.deny('our custom error message');`

But instead of our error message, the login shows the generic error, as seen in the screenshot.
We also have a web app and an Android app where the correct custom error message is shown and everything works fine. The problem only occurs with this iOS SDK.

What can we do, to display the error passed by api.access.deny() to the user?
In the logs everything looks fine, the error description is ‘our custom error message’. 

**Log entry with rule** (custom error message is shown in the ui)

```
{
  "date": "2021-11-18T11:40:48.539Z",
  "type": "fepft",
  "description": "our custom error message",
  "connection": "our-app",
  "connection_id": "con_cFDGZAaA7Lb0AGb8",
  "client_id": "j5jT3gWIopJDGQJvSK00Rbwg1KmBYpbD",
  "client_name": "Our App Name",
  "ip": "my ip",
  "client_ip": "my ip",
  "user_agent": "Our App Name 1.0.0 / Other 0.0.0",
  "hostname": "auth.our.domain",
  "user_id": "",
  "user_name": "my-email@adress.com",
  "audience": "https://our.domain/Service/",
  "scope": "openid email offline_access",
  "auth0_client": {
    "env": {
      "core": "1.37.1",
      "swift": "5.x",
      "iOS": "12.5"
    },
    "name": "Lock.swift",
    "version": "2.24.0"
  },
  "log_id": "90020211118114053634098613202136367420228063293318627410",
  "_id": "90020211118114053634098613202136367420228063293318627410",
  "isMobile": false
}
```

**Log entry with action** (wrong, generic error message is shown in the ui)
```
{
  "date": "2021-11-18T11:34:00.745Z",
  "type": "fepft",
  "description": "our custom error message",
  "connection": "our-app",
  "connection_id": "con_cFDGZAaA7Lb0AGb8",
  "client_id": "j5jT3gWIopJDGQJvSK00Rbwg1KmBYpbD",
  "client_name": "Our App Name",
  "ip": "my ip",
  "client_ip": "my ip",
  "user_agent": Our App Name 1.0.0 / Other 0.0.0",
  "details": {
    "actions": {
      "executions": [
        "BkPFW1H6RQGuJH1McFq3RzIwMjExMTE4"
      ]
    }
  },
  "hostname": "auth.our.domain",
  "user_id": "",
  "user_name": "my-email@adress.com",
  "audience": "https://our.domain/Service/",
  "scope": "openid email offline_access",
  "auth0_client": {
    "env": {
      "core": "1.37.1",
      "swift": "5.x",
      "iOS": "12.5"
    },
    "name": "Lock.swift",
    "version": "2.24.0"
  },
  "log_id": "90020211118113403184353413272563954882875995236864098354",
  "_id": "90020211118113403184353413272563954882875995236864098354",
  "isMobile": false
}
```

In both cases the custom error message is set in the description. Why do we see our custom message in the first case and the generic error in the second in the acutal ui? The only visible difference in the logs is the added "details" attribute when using the action

Thanks
Marius

### Environment
- **Version of `Auth0.swift` used: 1.37.1
- **Version of iOS/macOS/tvOS/watchOS: any we tried

**Comment by Widcket** [comment]
Hi @mmuelder, thanks for raising this. That seems like a Lock.swift issue, not an Auth0.swift one (Auth0.swift has no native UI). Could you please raise it in the Lock.swift repo?

**Comment by mmuelder** [comment]
oops, sorry. sure.
