### ISSUE TITLE
Biometrics outside of webAuth

### ISSUE THREAD

**Issue by zgordon02** [auth0/Auth0.swift#561]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/responsible-disclosure-policy) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

According to the [docs](https://auth0.com/docs/quickstart/native/ios-swift/08-touch-id-authentication), biometric authentication is only available via webAuth or the credentials method which seems to be doing a token refresh. I'm wondering if this is the case, and if so, are there plans to support biometric login outside of webAuth?

**Comment by zgordon02** [comment]
I haven't looked at the Android SDK yet, but I am wondering about similar functionality on Android as well, if anyone here would know

**Comment by Widcket** [comment]
Hi @zgordon02, thanks for raising this. You could use native Sign In with Apple (which lets you log in with Face ID) and then exchange the Apple authorization code for Auth0 credentials. Check out this quickstart: https://auth0.com/docs/quickstart/native/ios-swift-siwa/00-login-siwa
