### ISSUE TITLE
Cocoapods fail to install

### ISSUE THREAD

**Issue by DanMorganiOS** [auth0/Auth0.swift#57]
I added the following to my pod file `pod "Auth0", '1.0.0-rc.4@swift-2.3'` and it fails saying `[!] Oh no, an error occurred.` 

I can install the swift 3.0 pod perfectly fine using `pod "Auth0", '1.0.0-rc.4'` without the `@swift-2.3` suffix.

**Comment by hzalaz** [comment]
try specifying it as a branch not a version in your Podfile.

**Comment by DanMorganiOS** [comment]
Yes that worked 👍 thanks!
