### ISSUE TITLE
Swift Package Manager on Playgrounds 4 for iPad—ClangTarget issue

### ISSUE THREAD

**Issue by thefaj** [auth0/Auth0.swift#593]
Auth0 has an issue when added via Swift Package Manager to the newly released Playgrounds 4 for iPad.
The error message is: The target type, “ClangTarget”, is not supported.

Steps to reproduce:
• Create a new app on Playgrounds 4 for iPad
• Add a new Swift Package to the app using the Auth0 url: https://github.com/auth0/Auth0.swift
• Observe the error message in the navigation bar

I’ve attached a screenshot of the error and a copy of the app described above in the steps to reproduce.
I realize this is pretty new (just released today), so please let me know if I can help debug in any way.

Thank you!
[MyApp.zip](https://github.com/auth0/Auth0.swift/files/7722595/MyApp.zip)
![F9D14AEC-B6B0-4CCA-A5E0-A15EDFEB09CF](https://user-images.githubusercontent.com/60493/146263474-61da1912-8aed-4a3b-b072-7354e53054e8.png)

**Comment by Widcket** [comment]
Hi @thefaj, thanks for raising this. Could you please check if this happens with the `beta` branch?

**Comment by thefaj** [comment]
Thanks for the quick response @Widcket!

It looks like Playgrounds 4 on iPad doesn’t support branches yet, so I switched over to Xcode 13.2 on the Mac to add the `beta` branch. The sample app ran fine on the Mac as a Playground package with the Auth0 library. However, the iPad version couldn’t find the `beta` branch.

I don’t think this confirms that the `beta` branch works on Playgrounds 4. I can wait to retry when that branch is merged back into `main` at some point in the future. (I’ll also file feedback with Apple for Swift Package Management branch support on the iPad app.)

Thanks!

**Comment by Widcket** [comment]
@thefaj thanks for trying it out on the Mac.

> I can wait to retry when that branch is merged back into main at some point in the future.
 
That'd be great! In the meantime, I'll be closing this issue, as it cannot be actioned in the short term.

**Comment by thefaj** [comment]
Thanks again--just adding a note for the future. Looks like the issue might be Playgrounds 4 doesn't support Objective-C. Here's another developer who received the same error: https://twitter.com/stroughtonsmith/status/1471258469391114243?s=20

**Comment by Widcket** [comment]
> Looks like the issue might be Playgrounds 4 doesn't support Objective-C.

Then it might work with the beta, since it's all pure Swift.

**Comment by thefaj** [comment]
Awesome! I'll keep an eye on the branch and give it a try when it's ready. Thank you!

**Comment by Widcket** [comment]
Hi @thefaj, Auth0.swift [2.0.0-beta.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0-beta.0) is out now. See #637 for more information.

**Comment by thefaj** [comment]
Awesome! Thanks for the update--I'll give it a try and report back!
