### ISSUE TITLE
Add Max Age is incorrect

### ISSUE THREAD

**Issue by JZDesign** [auth0/Auth0.swift#609]
### Describe the problem

When authenticating through `Auth0.webAuth` and providing a `maxAge` we were consistently getting `pastLastAuth` errors. We can work around it by providing a significant negative number like `.maxAge(-20_000)` or using `.parameters(["max_age": "\(Int.max)"])`

### What was the expected behavior?

`.maxAge(20_000)` should succeed
`.maxAge(.max)` should succeed
`.maxAge(-1_000)` should fail
`.maxAge(0)` should fail

### Reproduction

- Step 1. Call the Auth0 WebAuth with a `maxAge`.

```swift
 Auth0
    .webAuth(clientId: settings.clientId, domain: settings.domain)
    .parameters(authFlow.auth0Parameters)
    .audience("https://\(your.domain)/userinfo")
    .scope("openid email profile")
    .maxAge(.max) // use this function
    .start {
        switch $0 {
        case .failure(let error): print(error) // you'll make it here
        case .success(let creds): print(creds)
    }
```
- Step 2. Sign in.

**Can the behavior be reproduced using the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample)?** I'm sure, though I haven't tested it myself. I abandoned Cocoapods a while ago and now my ruby environment doesn't want to comply. It's a one-line addition to test it yourself.

### Environment

- **Version of `Auth0.swift` used:** 1.36.0
- **Version of iOS/macOS/tvOS/watchOS:** iOS 15
- **Version of Xcode:** Xcode 13.1

**Comment by adamjmcgrath** [comment]
Hi @JZDesign - thanks for raising this and the PR.

We'll take a look at it when we can - in the meantime, can you continue to use the workarounds you've described

**Comment by JZDesign** [comment]
@adamjmcgrath We are using the `parameters()` workaround for now. I did open a PR, #610, to address this issue. The PR summary contains a bit more info and links to the Android implementation to show how the iOS and Android SDKs differ.

**Comment by Widcket** [comment]
This is now fixed on the `beta` branch.
