### ISSUE TITLE
Not building when authenticating as example...

### ISSUE THREAD

**Issue by jyaunches** [auth0/Auth0.swift#63]
Heyo,

So, when I authenticate as per the example in the README:

---
Auth0
   .authentication()
   .login(
       emailOrUsername: "support@auth0.com", 
       password: "a secret password", 
       connection: "Username-Password-Authentication"
       )
   .start { result in
       switch result {
       case .success(let credentials):
           print("access_token: \(credentials.accessToken)")
       case .failure(let error):
           print(error)
       }
   }
-----

I get a build error that I'm required to send other stuff. Notable these things are: 
* multifactorCode
* scope
* parameters

(See attached screenshot.)
![screen shot 2016-11-30 at 4 19 14 pm](https://cloud.githubusercontent.com/assets/372490/20771874/4da92d32-b719-11e6-9ee7-947659908973.png)

It's totally fine if these are, in fact, required.. but seems like the example should reflect that.

**Comment by cocojoe** [comment]
Apologies, there is a slight mix up in language between docheaders and readme.  Try the following:

```
Auth0
            .authentication()
            .login(
                usernameOrEmail: "support@auth0.com",
                password: "a secret password",
                connection: "Username-Password-Authentication"
            )
            .start { result in
                switch result {
                case .success(let credentials):
                    print("access_token: \(credentials.accessToken)")
                case .failure(let error):
                    print(error)
                }
        }
```

**Comment by jyaunches** [comment]
This worked.. oddly. It also resolved this issue: https://github.com/auth0/Auth0.swift/issues/64
