### ISSUE TITLE
"Remember this device" feature not working in iOS 13+ with SSO disabled and using "revoke" to logout

### ISSUE THREAD

**Issue by mirkojustiniano** [auth0/Auth0.swift#639]
### Describe the problem

Hi,

We've enabled "remember this device" for both Android and iOS and noticed that this feature works for Android and iOS 12, but not for iOS 13+.

### What was the expected behavior?

We use Universal Login with MFA rules and in iOS 13+ when we click the box to "remember this device" during login, and then after being logged in we do a logout and try to login again, we still have to enter MFA every single time.

### Reproduction

- In the Auth0 tenant enable MFA and Remember This Device features.
- Use Universal Login to login to the tenant.
- Enter credentials and check the box "remember this device".
- Enter MFA code.
- Once logged in do a logout.
- Try login again, enter credentials and check the box to "remember this device."
- In iOS 12 user is not prompted for MFA, but in iOS 13+ user has to enter MFA again.

One thing to note is that for iOS 12 we are using `webAuth.clearSession` to logout, but for iOS 13+ we are using `useEphemeralSession` to disable SSO, and we're using `credentialsManager.revoke` to logout.

We also use `"prompt": "login"` as parameters to login for all iOS versions with `webAuth.start`.

### Environment

- **Version of `Auth0.swift` used: *1.38.0*
- **Version of iOS/macOS/tvOS/watchOS: *iOS 13+*
- **Version of Xcode: *13.1*

**Comment by Widcket** [comment]
Hi @mirkojustiniano, thanks for raising this.
"Remember this device" works using cookies, and using `useEphemeralSession()` means that any cookies generated when logging in will not be kept. Therefore that setting will not be remembered.

**Comment by mirkojustiniano** [comment]
Thank you for the quick response @Widcket . That makes sense!

**Comment by mirkojustiniano** [comment]
Hey @Widcket sorry I got another question regarding this issue. So by removing the `useEphemeralSession` I am now able to "remember this device" and not have to enter MFA code as expected, but I was wondering if using `credentialsManager.revoke` still makes sense for logout? 

My understanding is that by using ephemeral sessions the session cookie is cleared as soon as the login flow completes and so for logout `credentialsManager.revoke` clears the user's tokens stored on the device and revokes the refresh token and there is nothing else to worry about. But now if we remove the ephemeral session do I need to worry about clearing the session cookie as well? Or does the fact that we are also using `"prompt": "login"` parameters take care of that by ignoring the cookie?

**Comment by Widcket** [comment]
@mirkojustiniano logging out of Web Auth usually means: (1) removing the session cookie by calling `clearSession()` + (2) removing the credentials from the device.

1) In your case, you're no longer using `useEphemeralSession()`, so there will be a cookie stored that can be cleared by calling `clearSession()`. However, you can skip calling `clearSession()` if you use `"prompt": "login"`. Note that the cookie will still be there, you will just be ignoring it. See https://github.com/auth0/Auth0.swift/blob/beta/FAQ.md#2-how-can-i-disable-the-logout-alert-box for more information.
2) You still need to remove the credentials from the device, e.g. by calling `credentialsManager.clear()`.
