### ISSUE TITLE
idToken nil after successful account creation & login

### ISSUE THREAD

**Issue by jyaunches** [auth0/Auth0.swift#64]
Heyo!!
So, maybe this is related to the confusion around API usage in my previous issue. Could be.

I'm able to successfully create a user using this code:
https://gist.github.com/jyaunches/6ddd423a09b1afa3ad2c0b7d3401d8a2

When I try to then log the user in, the credentials returned don't have an idToken value.
![screen shot 2016-11-30 at 4 30 57 pm](https://cloud.githubusercontent.com/assets/372490/20772250/c25eada4-b71a-11e6-8d36-92ab489e2fd5.png)

**Comment by cocojoe** [comment]
Is this a problem or an observation ? :)

**Comment by hzalaz** [comment]
@jyaunches try sending also `openid` in the scope

**Comment by jyaunches** [comment]
So, using the fix in this: https://github.com/auth0/Auth0.swift/issues/63 addressed this issue. Think maybe old api options should be removed if they're no longer functional?

**Comment by hzalaz** [comment]
They are not old api just a typo in the docs that @cocojoe already fixed. Thanks for reporting
