### ISSUE TITLE
"Block All Cookies" for Safari breaks the Auth0 Web Login page

### ISSUE THREAD

**Issue by mirkojustiniano** [auth0/Auth0.swift#640]
### Describe the problem

Hello,

We had an issue in production where a user was unable to login and what we found out is that when both in Android and iOS you "block all cookies" for the default browser and then go to use the app's Auth0 Universal Login, the page that loads up is the wrong page. In our case it routes to our home page. 

### What was the expected behavior?

We expect Auth0 Login web view to route to the correct callback url.

### Reproduction

The steps to reproduce in android are straightforward, but in iOS it's different:

- Go to Settings > Safari > Block All Cookies.
- Then we use Safari to navigate to our Login page that uses Auth0, so Home page > Login page. We don't need to attempt to login with the browser.
- Then we open up the app and tap login > Auth0 Login web view pops up with our Home Page instead of the Login page.
- At this point the only way to fix it is to disable "Block All Cookies", clear cookies and attempt to login again to bring up the correct login page.

In Android you just need to block all cookies and then attempt to Login with the app to reproduce this issue, no need to attempt to login with the browser.

- Our production app for iOS uses ephemeral sessions and "prompt: login" as login parameter.
- Our production app for Android uses "prompt: login" as login parameter.

So we are wondering:

- Can users authenticate with Auth0 if cookies are blocked?
- Is there a feature built into the SDK that would allow us to check for allowing cookies and pop up messaging to educate the user?
- What should the correct behavior/best practice be in this situation?

### Environment

- **Version of `Auth0.swift` used: 1.38.0**
- **Version of iOS/macOS/tvOS/watchOS: iOS 13+**
- **Version of Xcode: 13.1**

**Comment by Widcket** [comment]
Hi @mirkojustiniano, thanks for raising this.

Cookies are most definitely needed for any context-enabled app/service (like an auth service) to work. The Universal Login page doesn’t work when the cookies from the browser are disabled. That’s not something we can fix or even detect from the SDK side, as the SDK does not have access to the embedded Safari used by `ASWebAuthenticationSession`. It is external to the scope of our SDK.

**Comment by mirkojustiniano** [comment]
Makes sense, thank you @Widcket !
