### ISSUE TITLE
Running Auth0 SPM in fastlane pipeline error

### ISSUE THREAD

**Issue by BajwaRevelAmeer** [auth0/Auth0.swift#658]
### Describe the problem

Does anyone have an issue with running `fastlane run spm` for their own Swift Package when they've added Auth0 as a package dependency? I'm running it through a circleCI pipeline and trying to install the swift package dependencies (Auth0, JWTDecode) before code compiles and runs unit tests, but receive fatal  #error.

Using Xcode version: 13.1
Using Auth0 version: 1.38.1
Using iOS version: v14

![Screen Shot 2022-02-17 at 10 51 13 AM](https://user-images.githubusercontent.com/90710345/154550711-20f2cbf5-18d9-4050-8006-a0e9f6a885ff.png)

### What was the expected behavior?

> Tell us about the behavior you expected to see

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducible steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1..
- Step 2..
- ...

**Can the behavior be reproduced using the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample)?**

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log information and HTTP request traces (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots/GIFs

### Environment

> Please provide the following:

- **Version of `Auth0.swift` used:**
- **Version of iOS/macOS/tvOS/watchOS:**
- **Version of Xcode:**

**Comment by Widcket** [comment]
Hi @BajwaRevelAmeer, are you still experiencing this issue?

**Comment by BajwaRevelAmeer** [comment]
No, this has been fixed
