### ISSUE TITLE
Retain Login session in iOS Web view

### ISSUE THREAD

**Issue by satishrajpurohit** [auth0/Auth0.swift#674]
Hi,

I have implemented auth0 login in my app with Auth0 iOS SDK . When i try to open profile page in app web view, it is taking me to login again. How to maintain the session to open the profile page without login again.

I have check the SFSafariViewController and WKWebView but it didn't work.

**Comment by Widcket** [comment]
Hi @satishrajpurohit, thank you for the report but we're missing some important information. Please re-open a new issue with a completed Issue template. Delete sections that are not relevant, ask for help for sections that are not clear, and check all required checkboxes.

For general usage questions please refer to the [Auth0 Community forums](https://community.auth0.com/tags/c/sdks/5/swift), or raise a support ticker.

**Comment by satishrajpurohit** [comment]
@Widcket Can you please mention what are the information do you want. Please refer below link for which android has the same thing
https://github.com/auth0/Auth0.Android/issues/550

**Comment by Widcket** [comment]
@satishrajpurohit the information is in the issue template, which shows up in the *Write* tab when you create a new issue:

<img width="973" alt="Screen Shot 2022-04-05 at 11 37 03" src="https://user-images.githubusercontent.com/5055789/161778779-41dce26a-1829-4961-8f1c-d5cf4ee420c0.png">
