### ISSUE TITLE
Retain Login session in iOS Web view

### ISSUE THREAD

**Issue by satishrajpurohit** [auth0/Auth0.swift#676]
### ✏️ Description

I have implemented auth0 login in my app using Auth0 iOS SDK which will launch web page for login. When i try to open profile page in app web view, it is taking me to login again. How to maintain the session to open the profile page without login again.

I have check the SFSafariViewController and WKWebView but it didn’t work.

Android do have same issue they do have solution for that please refer below link for android:
https://github.com/auth0/Auth0.Android/issues/550

### 📋 Reproduction

1. login using Auth0 framework

            Auth0
                .webAuth()
                .scope("openid profile email")
                .parameters(["prompt": inPasswordPromptMode ? "none" : "login"])
                .logging(enabled: true)
                .start { [weak self] result in
                    guard let self = self else { return}
                    switch result {
                    case .failure(let error):
                    case .success(let credentials):
                   }
       }

2. As we have already login in when we try to open profile page (custom domain) using SFSafariViewController or WKWebView  it is not maintain the session to open the profile page

### 📱 Environment

- **Auth0.swift version**:
- **iOS**:
- **Platform version 14.4**:
- **Xcode version 12.4**:
- ** SPM**:

### ✅ Checklist

- [x] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample) 
- [x] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme) and have not found a suitable solution or answer
- [x] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/) and have not found a suitable solution or answer
- [x] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer
- [x] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer

**Comment by Widcket** [comment]
Hi @satishrajpurohit, thanks for raising this.

What you are describing is SSO between the app and `SFSafariViewController` (`WKWebView` cannot be used for this). It is possible in Auth0.swift 1.x, using the `useLegacyAuthentication()` method.
It was removed in 2.0, but we'll be replacing it with a more flexible solution in an upcoming minor.

I don't have an ETA for that ATM unfortunately.

**Comment by Widcket** [comment]
Seems like that answered your question, so I'll close this issue. Please let me know if you'd prefer to reopen.

**Comment by Widcket** [comment]
Hi @satishrajpurohit support for `SFSafariViewcontroller` is now out in [2.1.0](https://github.com/auth0/Auth0.swift/releases/tag/2.1.0).
See https://github.com/auth0/Auth0.swift/blob/master/FAQ.md#1-how-can-i-disable-the-login-alert-box
