### ISSUE TITLE
Have `CredentialsManager` check for expiring ID Token (along with Access Token)

### ISSUE THREAD

**Issue by av-pinzur** [auth0/Auth0.swift#681]
### ✏️ Describe the problem you'd like to have solved

Our team was delighted to discover that the `CredentialsManager` provides seamless refresh for expiring credentials! However, we then discovered that while it checks for an expiring Access Token, it doesn't check the ID Token. This means that if the Access Token expires first, everything works fine, but if the ID Token expires first, the Manager keeps returning it until the Access Token also expires. (The problem is exacerbated by the fact that while Auth0's OAuth provider allows us to configure a shorter [ID Token lifetime](https://auth0.com/docs/secure/tokens/id-tokens/update-id-token-lifetime), the `/userinfo` Access Token is [hard-coded at 24 hours](https://auth0.com/docs/secure/tokens/access-tokens#-userinfo-endpoint-token-lifetime).)

The absence of this feature reduces the SDK's practical value to us and represents a feature gap relative to [Auth0's Android SDK](https://github.com/auth0/Auth0.Android), which we're also using. (The Android SDK has provided this feature since 2019).

### ✏️ Describe the ideal solution

Enhance the `CredentialsManager` to renew the stored credentials when _either_ token is expiring, similar to the Android SDK behavior here:
https://github.com/auth0/Auth0.Android/blob/5b277300f0f613a1630aa7cb67c22f97db524147/auth0/src/main/java/com/auth0/android/authentication/storage/BaseCredentialsManager.kt#L101-L111

### 🩹 Alternatives and current workarounds

Our current workaround is to replace each new `Credentials` instance with a copy that has the Access Token's `expiresIn` set to match the ID Token's `expiresAt` (or whichever is earlier).

### 📌 Additional context

For reference, here is the history of the equivalent feature on the Android SDK:

* https://github.com/auth0/Auth0.Android/issues/253
* https://github.com/auth0/Auth0.Android/issues/254

### ✅ Checklist

- [x] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme) and have not found a suitable solution or answer
- [x] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/) and have not found a suitable solution or answer
- [x] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer
- [x] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer

**Comment by Widcket** [comment]
Hi @av-pinzur, thanks for raising this.

This is an intentional change in v2 (v1 checks for both ID Token and Access Token expirations): https://github.com/auth0/Auth0.swift/blob/master/V2_MIGRATION_GUIDE.md#role-of-id-token-expiration-in-credentials-validity
The `exp` of the ID Token is just for ID Token validation, it has no other use.

**Comment by Widcket** [comment]
cc @poovamraj for Android vNext ^

**Comment by jonathan-beebe** [comment]
@Widcket Thanks for the quick reply and the link. I saw the note at the link that "The ID Token expiration is no longer used to determine if the credentials are still valid. Only the Access Token expiration is used now." Can you explain the why behind this?

**Comment by Widcket** [comment]
An ID token is an artifact that proves that the user has been authenticated. When the ID Token is obtained at the end of the auth flow, it has to be validated (check that the signature is valid, that the claims are valid -> including that it has not expired). Once it has been validated (and ID Tokens obtained via Web Auth are automatically validated by Auth0.swift) the `exp` claim serves no other purpose and your app can safely consume its contents (e.g. to personalize the user interface).

Contrast this with the Access Token, which is meant to be used to make authenticated requests to a service (e.g. a backend), not to be consumed by your app in any way.

**Comment by Widcket** [comment]
I'll close this issue then. Please feel free to ping me if you'd prefer to reopen, or have further questions.
