### ISSUE TITLE
 (Xcode): Could not find module 'Auth0' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by victoralfonso920** [auth0/Auth0.swift#684]
### ✏️ Description

Swift Compiler Error (Xcode): Could not find module 'Auth0' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, 

### 📋 Reproduction
 install Auth0 from Swift package manager and run in emulator IOS in MAA M1

### 📱 Environment

- **Auth0.swift version**: 2.0.0
- **Platform (iOS/macOS/tvOS/watchOS)**: IOS Emulator 
- **Platform version**: 15.4
- **Xcode version**:13.3.1
- **Package manager (SPM/Cocoapods/Carthage/other)**:SPM

### ✅ Checklist
![matrix](https://user-images.githubusercontent.com/7407933/168342557-4625aab1-3f30-470d-a171-cea07964180d.gif)

**Comment by Widcket** [comment]
Hi @victoralfonso920 , thank you for the report but we're missing some important information. Please re-open a new issue with a completed **issue template**. Delete sections that are not relevant, ask for help for sections that are not clear, and check all required checkboxes.
