### ISSUE TITLE
Equivalent of getAccessTokenSiltently in JavaScript lib

### ISSUE THREAD

**Issue by abouroubi** [auth0/Auth0.swift#696]
- [x] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme) and have not found a suitable solution or answer
- [x] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/) and have not found a suitable solution or answer
- [x] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer
- [x] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer

### 💥 Describe the problem you'd like to have solved

I have an iOS App that needs to access two different APIs, and each API has it's own audience. I want to be able to to ask for an access token with different audience without asking user for his password a second time.

### ✨ Describe the ideal solution

Have the equivalent of `getAccessTokenSilentrly` of the Auth0 React SDK.

### 🩹 Alternatives and current workarounds

The only workaround I found is by calling the login() function twice, with the same email, password but different audience.
The issue with that is I can't use Auht0 Credentials manager anymore, I need to manage the login state and access tokens.

**Comment by Widcket** [comment]
Hi @abouroubi, thanks for raising this.

Auth0 does not support more than one custom audience in an access token. See https://community.auth0.com/t/how-do-i-specify-multiple-audiences/10830

**Comment by Widcket** [comment]
This works in a SPA because it can simply use [silent authentication](https://auth0.com/docs/authenticate/login/configure-silent-authentication). You'd need to open the `ASWebAuthenticationSession` browser again, even when passing `.parameters(["prompt": "none"])`.
