### ISSUE TITLE
`CredentialsManager.credentials()` should notify when the access token has been renewed

### ISSUE THREAD

**Issue by s-hocking** [auth0/Auth0.swift#709]
- [X] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme) and have not found a suitable solution or answer
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/) and have not found a suitable solution or answer
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer

### 💥 Describe the problem you'd like to have solved

When retrieving credentials using the `CredentialsManager.credentials()` API, Auth0 may renew the access token in the background. This is a great feature! However, it would be handy if Auth0 could let me know when this access token renewal occurs.

### ✨ Describe the ideal solution

I think the most straight forward solution is to add an additional `wasRenewed: Bool` parameter to the `CredentialsManager.credentials()` callback. For the async/await function, perhaps it could return a tuple of `(Credentials, Bool)`.

### 🩹 Alternatives and current workarounds

There are two workarounds I can think of but neither are very nice:

- I store the current access token in my own code, and each time I call `CredentialsManager.credentials()` I compare it to my current token to see if it's new. Defeats the purpose of using the `CredentialsManager` though
- I stop using `CredentialsManager` and manage token storage myself.

### 📌 Additional context

My use case is I am using a 3rd party SDK that I supply with an access token so it can make web requests to my backend. If the token is renewed by `CredentialsManager` midway through a session, I need to manually give the new token to the 3rd party SDK. Currently, I have no easy way to tell if Auth0 has given me a new token, because the renewal process is silent.

**Comment by Widcket** [comment]
Hi @s-hocking, thanks for raising this.
You can call the method from the third-party SDK to set the access token every time you retrieve credentials through the `CredentialsManager.credentials()` method. If the access token was not renewed, the access token used by the third-party SDK will not change. Otherwise, it will be updated.

**Comment by s-hocking** [comment]
Unfortunately, updating the access token for the third-party SDK in question is an expensive operation. It's not something I can do every time I retrieve credentials.

**Comment by Widcket** [comment]
Which third-party SDK is the one you're using?

**Comment by s-hocking** [comment]
[Couchbase Lite.](https://github.com/couchbase/couchbase-lite-ios/) Updating the authentication config for a `Replicator` requires tearing down the old one and creating a new one, which is disruptive to the data sync process.

**Comment by Widcket** [comment]
Thanks for the context. I'd suggest hashing the access token every time you retrieve it, and comparing it with the last hash (stored somewhere). If it's different, you can create a new `Replicator`.
I'd also suggest reaching out to the Couchbase Lite maintainers and requesting a way to change this value without recreating the `Replicator`.

**Comment by Widcket** [comment]
Closing, as the suggestion above seems to solve the issue at hand. Please feel free to ping me if you'd prefer to reopen.
