### ISSUE TITLE
After adding WebAuthentication.safariProvider() the app does nothing

### ISSUE THREAD

**Issue by YevhenVovk** [auth0/Auth0.swift#738]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I migrated my application from `1.38.1` to` 2.3.1`. I removed `.useLegacyAuthentication()` and added `.provider(WebAuthentication.safariProvider())`, the application just does nothing after entering data. My result callback never fires and the app just doesn't do anything.

```
let webAuthentication = Auth0
.webAuth(clientId: "Some Client", domain: "Some Domain")
.scope("openid offline_access email update:current_user_metadata")
.useEphemeralSession()
.provider(WebAuthentication.safariProvider())
```

### Reproduction

https://user-images.githubusercontent.com/37621354/188437203-6034749d-6fb0-41d7-bfa3-d17bb9d507ea.mp4

### Auth0.swift version

2.3.1

### Platform

iOS

### Platform version(s)

iOS 15.5

### Xcode version

Version 13.4.1 (13F100)

### Package manager

CocoaPods

**Comment by Widcket** [comment]
Hi @YevhenVovk, thanks for raising this.

Are you calling `WebAuthentication.resume(with:)` to resume the WebAuth operation?

<img width="1046" alt="Screen Shot 2022-09-05 at 08 27 14" src="https://user-images.githubusercontent.com/5055789/188438548-5e04ae25-bf26-4383-a673-d47ae25eade3.png">

**Comment by Widcket** [comment]
BTW, you don't need to use `useEphemeralSession()` if you're using `provider(WebAuthentication.safariProvider())`.  `useEphemeralSession()` only works with `ASWebAuthenticationSession`.

**Comment by Widcket** [comment]
@YevhenVovk seems like the above solves your issue. I'll close this one, please feel free to comment if you'd prefer to reopen.
