### ISSUE TITLE
Universal login page if goes behind another app, there is no way to get it forward and the user gets confused.

### ISSUE THREAD

**Issue by manishjain999** [auth0/Auth0.swift#739]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am using the auth0 SDK in a macOS app (swift).
I am using the Universal Login.
The login page shows up in Safari or Chrome whatever the default browser is.
The user clicks on another app and the Login window goes back. 
If several other apps are open, It is lost beneath other apps.

Now from the main app that invoked this universal login page there is no way to make it topmost or bring it to front.
A new session cannot be started until that opened page is closed.

There should be a way to handle this.

### Describe the ideal solution

There should be a way to programmatically end the current session and close the opened Universal Login page so that a new session can be started.

**Comment by manishjain999** [comment]
Another issue is that the universal Login Page does not open up on Catalina. I have read some older issues and it was suggested that the issue was related to ASWebAuthenticationSession  and it was fixed by Apple in macOS 12.4
So, does that mean the auth0 SDK for macOs wont work on Catalina?

**Comment by Widcket** [comment]
Hi @manishjain999, thanks for raising this and apologies for the delay.

I'm afraid that the behavior you mention is outside of the control of the SDK –it's up to `ASWebAuthenticationSession`, and therefore macOS.

> does that mean the auth0 SDK for macOs wont work on Catalina?
It should work with [this change ](https://github.com/auth0/Auth0.swift/pull/735), but it's still unreleased. I'm a bit busy at the moment, but I'll try to put out a new release as soon as I can.

**Comment by Widcket** [comment]
> It should work with https://github.com/auth0/Auth0.swift/pull/735, but it's still unreleased. I'm a bit busy at the moment, but I'll try to put out a new release as soon as I can.

The new release is out now: https://github.com/auth0/Auth0.swift/releases/tag/2.3.2
