### ISSUE TITLE
Allow iOS SDK to pass a returnTo parameter to Logout

### ISSUE THREAD

**Issue by DannyPat44** [auth0/Auth0.swift#741]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We have a case where we want the redirect URL on a Logout call to differ from the redirect URL that is used on login. 

### Describe the ideal solution

Support passing the`ReturnTo` parameter when logging a member out of the application. The Android and SPA SDK allow us to do this out of the box.  https://github.com/auth0/Auth0.Android/blob/a0e5d7464fb3f64d65def18585335de6087e5f4c/auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt#L132

### Alternatives and current workarounds

We have an option to update the redirect URL only when we look to make the call to `clearSession`.
```
webAuthentication = webAuthentication.redirectURL(URL(staticString: "log_out_url"))
webAuthentication.clearSession(federated: true) { result in }
```

### Additional context

We are using a custom social connection to integrate with one of our partners. Even when we sign out the user of our application (and the Auth0 session) the partner idp SSO session was still present in the browser and was not killed during sign-out. Meaning that the authentication request that went out to the Partner connection would see the session already existing and autologin with the existing user. This does allow a different user to have the ability to login into the app without waiting for the existing session to expire.

Our partner does not have a full set of OIDC capabilities; ideally don't want to even have to worry about managing the partner identity providers session.  This means to have a different user login using a browser where a session may already exist we either have to prevent SSO cookies from being persisted or have to trigger ending the Partner session ourselves.
Making sure the session isn't persisted does not seem possible (based on partner capabilities). 

Normally we would do this through federated logout where logging out of Auth0 forces a logout of the upstream IDP. Unfortunately, Auth0 does not support federated logout for [custom connections](https://auth0.com/docs/authenticate/login/logout/log-users-out-of-idps).
That being the case we have to try and do federated signout ourselves; by using logout redirects to chain the necessary logout calls together. So using the Auth0 SDK we would call the Auth0 logout first, redirecting to the Partner endpoint before directing to the main application.

**Comment by Widcket** [comment]
Hi @DannyPat44, thanks for raising this.

Passing a returnTo URL is already supported: use `redirectURL()`. See https://github.com/auth0/Auth0.swift/blob/master/Auth0/Auth0WebAuth.swift#L186

Example:

```swift
Auth0
    .webAuth()
    .redirectURL(logoutURL)
    // ...
```
