### ISSUE TITLE
Github Slack integration

### ISSUE THREAD

**Issue by alrocha** [auth0/Auth0.swift#749]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hello, when trying to add the slack notifications for github repo using
/github auth0/Auth0 releases I get the following error saying that the app is not installed in the repo.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/8307263/200579240-88e1bd38-fc11-4803-b2a8-3764b314eaab.png">

Could be possible to install it? I think just using this link as I could see in the docs: https://github.com/apps/slack/installations/new

It would be really useful, since we use it to get notifications for new releases.  

Thanks in advance! :) 

### Describe the ideal solution

Install slack notification bot into the repo.

**Comment by Widcket** [comment]
Hi @alrocha, thanks for raising this.

You can get an atom feed of the releases here: https://github.com/auth0/Auth0.swift/releases.atom
Additionally, you can get GH notifications of releases by watching 'Releases':

<img width="313" alt="Screen Shot 2022-11-08 at 10 45 11" src="https://user-images.githubusercontent.com/5055789/200581400-a79ec8b3-8760-4289-b323-4854f6bf787d.png">

Then you can use the GH API to get the notifications: https://docs.github.com/en/rest/activity/notifications#list-notifications-for-the-authenticated-user

I'll go ahead and close this issue, let me know if you have any further questions.

**Comment by Widcket** [comment]
You can still use the atom feed with Slack: https://slack.com/help/articles/218688467-Add-RSS-feeds-to-Slack
