### ISSUE TITLE
Screen hint and Prompt Parameters don't seem to have an effect

### ISSUE THREAD

**Issue by wrightak** [auth0/Auth0.swift#751]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Including `.parameters(["screen_hint": "signup"])` or `.parameters(["prompt": "login"])` doesn't seem to have any effect.

I am using the Universal Login. In my app, I have a "Login" button. I don't want the signup options to appear if the user taps this. Similarly, I have a "Signup" button where I would like the opposite.

The above parameters may not give me exactly what I want, but at the moment they don't seem to do anything.

### Reproduction

Add the screen_hint or prompt parameters described above.

### Auth0.swift version

2.3.2

### Platform

iOS

### Platform version(s)

16.0

### Xcode version

14.0.1

### Package manager

Cocoapods

**Comment by wrightak** [comment]
@Widcket Thank you for replying. Unfortunately this isn't working for me. I assume this means that there's something different about my Universal Login setup rather than a problem with Auth0.swift. Can you give me guidance on this? Here's the video.

https://user-images.githubusercontent.com/1816940/204689473-a314d196-3e37-467c-800a-ada0da2f7697.mov

**Comment by wrightak** [comment]
I think I've solved this. I'm not using the Classic Universal Login. I'm using the New Universal Login but in _Auth0 Dashboard > Branding > Universal Login > Login_ I had the `Customize Login Page` switch set to ON. You need to turn this off for it to work. 

Seems like something worth adding to the part of the readme that you quoted. Would you like me to make a PR?

**Comment by wrightak** [comment]
Incidentally, I have no idea why that switch was on. I don't remember writing any of the HTML that's there or switching it on deliberately.

**Comment by Widcket** [comment]
> I'm using the New Universal Login but in Auth0 Dashboard > Branding > Universal Login > Login I had the Customize Login Page switch set to ON. You need to turn this off for it to work.

Turning that switch ON makes it use Classic Universal Login, which relies in [Lock.js](https://github.com/auth0/lock):

<img width="1035" alt="Screen Shot 2022-11-29 at 23 28 48" src="https://user-images.githubusercontent.com/5055789/204693336-0247c282-c348-4428-a215-2ea3f9af0cff.png">

This is indeed Classic Universal Login:

<img width="393" alt="Screen Shot 2022-11-29 at 23 30 18" src="https://user-images.githubusercontent.com/5055789/204693358-524b24d9-77e5-4de4-ba77-99221f1b1d49.png">

**Comment by wrightak** [comment]
@Widcket I see. When looking at this page, it looks like I'm using the New Universal Login. 

![Screen Shot 2022-11-30 at 11 39 53](https://user-images.githubusercontent.com/1816940/204694576-5a6015e2-9ebe-48e0-8a9e-7e58be34b6d3.png)

Even though the warning says "One or more pages are using custom HTML to override the Universal Login experience" that doesn't make it clear that I'm using classic, because "New" is still clearly selected. I assumed that some settings were being overridden, but I was still using "New". I'm guessing that this switch was on because I started using Auth0 before the New Universal Login experience was completed?

I understand that this UI may not have anything to do with you, but I hope that some feedback on it can be passed on and that other users of Auth0.swift with the same problem find this issue helpful.
