### ISSUE TITLE
Passwordless Email doesnt open application

### ISSUE THREAD

**Issue by oezguercelebi** [auth0/Auth0.swift#756]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,
we are trying to implement Passwordless login natively on iOS and Android and encountered an issue.
The emails we get from setting up Passwordless and sending ourselves a test email are visually different than the email we expect would like to get from the SDK method request. Also, the email from the SDK method request does not open the app because the universal link piece is missing in front of the link when we select iOS or Android type.

We want to get an Email with a redirect link with the OTP in the URL and an OTP code should be shown in the email. To make sure that customers that have email client not on the phone can enter their OTP code.

This is what we used on both platforms
```
Auth0
           .authentication()
           .startPasswordless(email: "test@gmail.com", type: .iOSLink)
           .start { result in
               switch result {
               case .success:
                   print("Auth0 Sent OTP to test@gmail.com!")
               case .failure(let error):
                   print("Auth0: \(error)")
               }
           }
```

### Reproduction

1. Add SDK
2. Enable Passwordless
3. Request auth on native mobile application

### Auth0.swift version

2.3.2

### Platform

iOS

### Platform version(s)

16.2

### Xcode version

14.2

### Package manager

SPM

**Comment by Widcket** [comment]
Hi @oezguercelebi, thanks for raising this. 

> the email from the SDK method request does not open the app because the universal link piece is missing in front of the link

Testing this I get a link like `https://ritazerrizuela.auth0.com/ios/com.example.test/email?code=111111`. For this link to open your iOS app, you need to set up Universal Links. See https://github.com/auth0/Lock.swift/issues/665

> an OTP code should be shown in the email. To make sure that customers that have email client not on the phone can enter their OTP code.

I'm afraid this is out of the scope of the SDK, please contact [support](https://support.auth0.com/) to file a feature request.

**Comment by Widcket** [comment]
Closing as the above seems to solve your issue. Please feel free to ping if you'd prefer to reopen.
