### ISSUE TITLE
The credentials renewal failed. CAUSE: Unknown or invalid refresh token.

### ISSUE THREAD

**Issue by sergiobleague** [auth0/Auth0.swift#763]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are randomly getting this error when using `credentialsManager.credentials(minTTL: 60) `
On our logging system, it says that the error is coming from 
`CredentialsManager.retrieveCredentials(CredentialsManager.swift:355)`

### Reproduction

1. Background the app for a long period
2. App goes to the foreground
3. We ask for biometrics
4. If successful, call `credentialsManager.credentials(minTTL: 60)`
5. we get the error, but it happens randomly 

### Auth0.swift version

2.3.2

### Platform

iOS

### Platform version(s)

16.3.1

### Xcode version

14.2

### Package manager

SPM

**Comment by victorBaro** [comment]
We are facing the same issue (although we are not using `credentialsManager`). We are storing credentials in the keychain and manually retrieving them.
Auth0 renew request is randomly returning `Error: Unknown or invalid refresh token., code: invalid_grant`

**Comment by Widcket** [comment]
Hi @sergiobleague @victorBaro thanks for raising this and apologies for the delay.

The Credentials Manager should not use old refresh tokens, as it only saves a single set of credentials, which get replaced with the renewed ones. `Error: Unknown or invalid refresh token., code: invalid_grant` sounds like concurrency issues. On Auth0.swift v2 the `credentials()` method should not make more than one request at any given time, so I'd suggest making sure that:

- You're not storing the renewed credentials manually, by calling `store()` after `credentials()`. The renewed credentials are automatically stored by the Credentials Manager, and calling `store()` anyway could cause concurrency issues.
- You're only using a single instance of the Credentials Manager.

Both these items are mentioned in the documentation of the `credentials()` method: https://auth0.github.io/Auth0.swift/documentation/auth0/credentialsmanager/credentials(withscope:minttl:parameters:headers:callback:)

If you're not using the Credentials Manager, make sure to appropriately synchronize the renewal calls.

**Comment by sergiobleague** [comment]
Hi @Widcket! 
Thanks for your reply! 
In our case we are only using one instance of the `credentialsManager` and we are not calling `store()` anywhere. 
Also, we implemented a flag and listeners to ensure we are not calling credentials() at the same time like this:
<img width="622" alt="Screenshot 2023-04-18 at 2 13 33 PM" src="https://user-images.githubusercontent.com/109972857/232882318-8c135235-d046-4ae7-9c38-1f468dcb6b72.png">

**Comment by Widcket** [comment]
@sergiobleague the Credentials Manager in Auth0.swift v2 already takes care of synchronization to ensure only one renewal request is in flight at any given time: https://github.com/auth0/Auth0.swift/blob/master/Auth0/CredentialsManager.swift#L308 (see https://github.com/auth0/Auth0.swift/issues/734#issuecomment-1233506160 for more information).

So as long as you keep a single instance of the Credentials Manager, you do not need additional precautions to call `credentials()`. I would not recommend adding additional synchronization on top, as that can also cause concurrency issues.

**Comment by sergiobleague** [comment]
@Widcket I have reviewed our code to check what you mentioned and:

- We are using Auth0.swift v2  
- We are creating the instance like lazy stored property. Like this: 
```
 private lazy var auth0Authenticator: Auth0Authenticator = {
        // create instance
        return authenticator
    }()
```
So not sure what is happening. What else should I check to confirm that we are using it correctly?

FYI: this error is also present on Android.

**Comment by Widcket** [comment]
@sergiobleague I'd suggest checking that you're not using the [Authentication API client](https://github.com/auth0/Auth0.swift/blob/master/Auth0/Authentication.swift#L690) to call `renew()` somewhere (outside of the Credentials Manager).

**Comment by sergiobleague** [comment]
@Widcket we are not using that either. 
At this point not sure what is happening. Do you have any suggestions on how we can track why this issue is happening?

**Comment by Widcket** [comment]
You can use something like https://github.com/auth0/Auth0.swift/compare/debug-logger#diff-32cd1807ed1b4849472f72a2735e8f287ab45daf78ae0e5a8045093d6abb75a0R76 in a debug build to programmatically ensure there is only one Credentials Manager instance being used across the app.

If everything looks good in your app, you can use the [sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) to put together a reproducible we can take a look at.

**Comment by Aaqibali279** [comment]
@Widcket i am facing the same issue, any update ?

**Comment by Widcket** [comment]
Hi all, apologies for the delay.

In order to further troubleshoot this issue, please check the following:

1. Is your Auth0 application a "Native" application?
2. Do you have Refresh Token Rotation enabled?
3. What does show up in the Auth0 logs when this error happens? Please share in detail, redacting any sensitive information.
4. Could you please share the **Refresh Token Expiration** config of your Auth0 application? You can find this section in the settings tab of your Auth0 application.

**Comment by sergiobleague** [comment]
@Widcket wondering if this renew() method in release [2.4.0 ](https://github.com/auth0/Auth0.swift/releases/tag/2.4.0) will help to address this ?

**Comment by Widcket** [comment]
Hi @abrandt38-mm, thanks for providing detailed information.

A `fertft` error indicates that Auth0 does not recognize the token (an empty or garbage/truncated/padded token was sent), or the token is not valid anymore (expired, or was revoked).

Since the errors you're experiencing seem to be related to the Absolute Lifetime value, it's likely a case of the token simply expiring due to a small Absolute Lifetime value. This value should not be shorter than the access token lifetime. If the access token lifetime is longer, `credentials()` will renew the credentials before the refresh token expires.

Once a refresh token is expired, it can no longer be exchanged for new credentials, resulting in a `fertft` error.

**Comment by sergiobleague** [comment]
1. iOS Native App
2. token rotation is enabled
3. 
![Screenshot 2023-06-15 at 12 03 03 PM](https://github.com/auth0/Auth0.swift/assets/109972857/daf90976-c710-4e96-83c7-b11827f4381d)
4. 
![Screenshot 2023-06-15 at 12 09 56 PM](https://github.com/auth0/Auth0.swift/assets/109972857/a13aa56c-6ec8-4170-b1c2-247f796f7de5)

**Comment by abrandt38-mm** [comment]
Hi @Widcket thanks for the quick response.  Allow me to expand a bit on what I was trying to test when I encountered this.  I was testing for a rolling expiration on the refresh token by performing multiple exchanges relatively close together, hypothetically extending the lifetime of the refresh token.  What I was observing was with the new, exchanged token was expiring faster than I expected.  One of my logs looks like this:

`Login 12:57, enroll biometric 12:58, biometric login 12:59, biometric login 1:01, biometric login failed 1:03`

A biometric login would perform the token exchange and renew access token, refresh token, etc. What I expect to happen is that I can refresh essentially in perpetuity as long as I am within the lifetime, but that is not happening.  My refreshed tokens become invalid much faster the final attempt.  Any thoughts?

**Comment by Widcket** [comment]
> A biometric login would perform the token exchange and renew access token, refresh token, etc. 

@abrandt38-mm `credentials()` will renew only if the access token is expired, independently of the usage of biometrics.

**Comment by Widcket** [comment]
@sergiobleague In your case I suspect it's because of the **Inactivity Lifetime**, that would explain why it happens after the app was backgrounded for some time. This value should not be shorter than the access token lifetime either.

**Comment by abrandt38-mm** [comment]
> A biometric login would perform the token exchange and renew access token, refresh token, etc

I was mostly informing what `biometric login` meant in the context of my logs what was going on in our app.  Our workflow checks for expired access token before trying to renew.

**Comment by Widcket** [comment]
@abrandt38-mm I'm afraid that exceeds the scope of this issue and the SDK itself. I'd suggest contacting Auth0 support about it.

**Comment by Widcket** [comment]
@sergiobleague @abrandt38-mm are you still getting these errors after adjusting the values in the Dashboard?

**Comment by sergiobleague** [comment]
@Widcket Ok so I checked this and for us, now it makes sense that the refresh token is invalid after the absolute expiration time and also we disabled inactivity expiration. 
Closing this issue
