### ISSUE TITLE
SFSafariViewController (SwiftUI)

### ISSUE THREAD

**Issue by vorisarik** [auth0/Auth0.swift#768]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi, Widcket, guys,
unfortunately, Auth0 forum could not help me with explanation of SFSafariViewController usage in SwiftUI and suggested I ask here for the answer.
There is one totally clear thing in the FAQ:

```
Auth0
    .webAuth()
    .provider(WebAuthentication.safariProvider()) // Use SFSafariViewController
    .start { result in
        // ...
    }
```

and one unclear:

```
SomeView()
    .onOpenURL { url in
        WebAuthentication.resume(with: url)
    }
```

Would you please provide a little bit more information or a code example?
I couldn't figure out where in my code to do resume() und what URL should I pass on? Allowed callback URL from the application page? An example would be great!
Thanks in advance.

### Describe the ideal solution

Explanation or code example.

**Comment by vorisarik** [comment]
Ok, resolved.
Custom URL scheme must be configured.
"In Xcode, go to the Info tab of your app target settings. In the URL Types section, click the ＋ button to add a new entry. There, enter auth0 into the Identifier field and $(PRODUCT_BUNDLE_IDENTIFIER) into the URL Schemes field."

**Comment by Widcket** [comment]
Hi @vorisarik, apologies for the delay. I'm glad you could solve this one.
