### ISSUE TITLE
Swift Cannot read properties of undefined (reading ‘passwordless_method’)

### ISSUE THREAD

**Issue by WorkspacePrateek** [auth0/Auth0.swift#770]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Swift Cannot read properties of undefined (reading ‘passwordless_method’) while trying to login using email and password 

### Describe the ideal solution

Hello everyone,

I have been facing an issue while implementing Auth0 with a username and password authentication method. Every time I try to log in, the login fails, and I receive the following error message: “Cannot read properties of undefined (reading ‘**passwordless_method**’)”. Additionally, the status code returned is 500.

Here is the code snippet I am using for the login process:

`      Auth0`
`                .authentication()`
 `               .login(`
 `                   usernameOrEmail: "xxx@engrossinfotech.com",`
`                    password: "xxx@12345",`
`                    realmOrConnection: "Username-Password-XXXXXXXX",`
`                    audience: "https://company.com/api/v2/",`
`                    scope: "openid profile email offline_access"`
`                )`
`                .start { result in`
`                    switch result {`
`                    case .failure(let error):`
`                        print(error.localizedDescription)`
`                    case .success(let credentials):`
`                        print(credentials)`
`                    }`
`                }`

### Additional context

**Note:**
- Version: [Release 2.3.2](https://github.com/auth0/Auth0.swift/releases/tag/2.3.2)
- Mac M2 and M1
- I have also tested the login functionality using WebAuth, and it worked without any issues.
- I have also allowed the Password in the Grant Types.
![image](https://github.com/auth0/Auth0.swift/assets/22356914/30c36da4-e361-4469-8c18-91fe5c180b1e)

**Comment by pratik-eit** [comment]
Hello everyone,

I have identified the issue, and it is not related to the library. I am sharing the details here so that it can help anyone who may encounter a similar problem.

The web developers have implemented a rule that applies to all applications. Within that rule, there is a condition that checks if the passwordless_method parameter in the request has a value of 'SMS'. However, in the request I was sending from the mobile device, the parameter was not passwordless_method. As a result, the rule encountered an error, leading to the issues mentioned earlier.

![image](https://github.com/auth0/Auth0.swift/assets/132246051/5d04fa07-823f-4ad0-a7fe-c1029c2155f8)

**Comment by WorkspacePrateek** [comment]
Hello everyone,

I have identified the issue, and it is not related to the library. I am sharing the details here so that it can help anyone who may encounter a similar problem.

The web developers have implemented a rule that applies to all applications. Within that rule, there is a condition that checks if the passwordless_method parameter in the request has a value of 'SMS'. However, in the request I was sending from the mobile device, the parameter was not passwordless_method. As a result, the rule encountered an error, leading to the issues mentioned earlier.
![image](https://github.com/auth0/Auth0.swift/assets/22356914/d5a6b591-9c27-49b0-a262-eb59cc5893d4)
