### ISSUE TITLE
Crash with numeric bundle indentifier

### ISSUE THREAD

**Issue by peppelisanti** [auth0/Auth0.swift#785]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have an application with a bundle identifier that starts with numbers, like 8NF89NA5EL.xx.xxxxxxxx.xxx
When I call the web authentication I have a crash on Auth0WebAuth.swift at the row         
components?.scheme = bundleIdentifier
The crash is  +[NSURLComponents setScheme:]: invalid characters in scheme

### Reproduction

Try web authentication with a bundle identifier that start with numbers

### Auth0.swift version

2.4.0

### Platform

iOS

### Platform version(s)

16.4

### Xcode version

14.3.1

### Package manager

Cocoapods

**Comment by Widcket** [comment]
Hi @peppelisanti, thanks for raising this.

I was able to reproduce this:
<img width="1250" alt="Screenshot 2023-08-01 at 5 23 01 PM" src="https://github.com/auth0/Auth0.swift/assets/5055789/07678ffb-e5c9-4d80-851b-7c742fb78558">

In the meantime, you can use the `redirectURL()` [builder method](https://auth0.github.io/Auth0.swift/documentation/auth0/webauth/redirecturl(_:)/) to specify an URL with a different scheme.
