### ISSUE TITLE
The .start method callback is sometimes not called

### ISSUE THREAD

**Issue by kafejo** [auth0/Auth0.swift#787]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I noticed that sometimes the start callback is not called at all.

```
 Auth0
                .authentication()
                .renew(withRefreshToken: refreshToken, scope: SessionManager.defaultScopes)
                .start { result in
                    Logger.log.info("Got result from renew session \(result)")
                }
```

### Reproduction

```
 Auth0
                .authentication()
                .renew(withRefreshToken: refreshToken, scope: SessionManager.defaultScopes)
                .start { result in
                    Logger.log.info("Got result from renew session \(result)")
                }
```

I cannot consistently reproduce it but I call this on every app launch and 1 out of 5 launches don't receive the start callback. The only thing I could observe is that it happens usually after launching this method after 5-10 minutes.

### Auth0.swift version

2.5.0

### Platform

iOS

### Platform version(s)

iOS 16

### Xcode version

14.3.1

### Package manager

Cocoapods

**Comment by Widcket** [comment]
Hi @kafejo, thanks for raising this.

> I cannot consistently reproduce it but I call this on every app launch and 1 out of 5 launches don't receive the start callback. The only thing I could observe is that it happens usually after launching this method after 5-10 minutes.

Sorry, I'm afraid I don't follow. You mention that you're calling this this method on every app launch, but also that you're only observing this after 5-10 minutes. Could you please expand on this? Are you observing this on app launch, or after?

**Comment by kafejo** [comment]
Hi @Widcket, apologies for not being more clearer in my description. What I meant is that it seemed to happen only when I launched the app in a space of 5-10 minutes. It does happen on a launch. Upon further investigation it seems like the underlying data task completion handler is not being called under certain conditions.

```swift
public func start(_ callback: @escaping Callback) {
      let handler = self.handle
      let request = self.request
      let logger = self.logger

      logger?.trace(request: request, session: self.session)


      let task = session.dataTask(with: request, completionHandler: { data, response, error in
          if error == nil, let response = response {
              logger?.trace(response: response, data: data)
          }
          handler(Response(data: data, response: response as? HTTPURLResponse, error: error), callback)
      })
      task.resume()
}
```

**Comment by kafejo** [comment]
Yeah I can see that. It's not that the you never call the handler. It's more that the completionHandler of the data task seems not to be called in certain conditions. I noticed you are using a shared URLSession so I'm wondering is that can have anything to do with it.

**Comment by Widcket** [comment]
Yes, the session [defaults to](https://auth0.github.io/Auth0.swift/documentation/auth0/authentication(clientid:domain:session:)/) `URLSession.shared`. I'll go ahead and close this issue for now, as it's not an SDK bug. Please feel free to ping if you'd prefer to reopen.
