### ISSUE TITLE
Auth0 not working in iOS 17. Not able to login

### ISSUE THREAD

**Issue by isaacraja15** [auth0/Auth0.swift#796]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi,

We are using Auth0(1.39.1) in this version. It's not supporting iOS 17. Without updating Auth0 possible to resolve this?

Thanks 

### Reproduction

Just Update iOS 17

### Auth0.swift version

1.39.1

### Platform

iOS

### Platform version(s)

17

### Xcode version

15 7th beta

### Package manager

Cocoapods

**Comment by isaacraja15** [comment]
Do you have any migration documents for 1. x to 2. x

**Comment by Widcket** [comment]
Yes, please check out https://github.com/auth0/Auth0.swift/blob/master/V2_MIGRATION_GUIDE.md.

**Comment by isaacraja15** [comment]
Thank you for your help.
I did the migration 1. X to 2. X successfully. But I have one problem if the System date and time are set automatically means it's working fine.

if set automatically is turned off. then I tried to log in, but we were not able to log in. It shows the error below

Error: The ID token validation performed after authentication failed. CAUSE: Expiration time (exp) claim error in the ID token; current time (1693563166.529696) is after expiration time (1693540382.0)

In the screenshot highlighted place I'm getting Error.

<img width="603" alt="image" src="https://github.com/auth0/Auth0.swift/assets/44321070/b9813191-3a28-4cdf-9716-22439533dcbb">

**Comment by Widcket** [comment]
If the system date is incorrect, the ID token validation might fail. You can adjust the leeway value using `leeway(:_)`: https://auth0.github.io/Auth0.swift/documentation/auth0/webauth/leeway(_:)

**Comment by isaacraja15** [comment]
Thank you for your help.
Can you confirm I did it correctly?

<img width="979" alt="image" src="https://github.com/auth0/Auth0.swift/assets/44321070/ec9055ad-94df-4bd4-a03f-dd70981b6c59">

**Comment by Widcket** [comment]
As per the documentation shared, the value is in milliseconds. Also, kindly note that we do not provide code-level support; we use GitHub issues for feature requests and bug reports only, and this is neither. Please open a [support ticket](https://support.auth0.com/) or refer to the [Auth0 Community forums](https://community.auth0.com/) instead.

<img width="552" alt="Screenshot 2023-08-31 at 1 48 11 PM" src="https://github.com/auth0/Auth0.swift/assets/5055789/58fb73f1-2fc1-47d4-86a4-97f8b734d1c9">

**Comment by isaacraja15** [comment]
Ok thanks for your help.
