### ISSUE TITLE
Renewal error

### ISSUE THREAD

**Issue by ericreid** [auth0/Auth0.swift#80]
I'm trying to implement renewal via refresh tokens, but I'm getting an error of `Unsupported grant type: refresh_token`.

I seem to get a valid refresh token back from the login call. But when I try to use it, I get the error above.

Is there another scope I need? Or something I need to adjust in my settings somewhere?

Here is my login code:
```
authentication.login(usernameOrEmail: username, password: password, multifactorCode: nil, connection: "Username-Password-Authentication", scope: "openid email offline_access", parameters: ["device": UIDevice.current.name]).start { result in
    switch result {
    case .success(let credentials):
        if let idToken = credentials.idToken, let refreshToken = credentials.refreshToken {
            let keychain = KeychainSwift()
            keychain.set(idToken, forKey: "auth0_idToken")
            keychain.set(refreshToken, forKey: "auth0_refreshToken")
        }
    case .failure(let error):
        print("Error: \(error)")
    }
}
```

And here is my renew code:
```
guard let refreshToken = keychain.get("auth0_refreshToken") else {
    return
}
authentication.renew(withRefreshToken: refreshToken).start { result in
    switch result {
    case .success(_):
        break
    case .failure(_):
        break
    }
}
```

**Comment by hzalaz** [comment]
As the doc comment of the methods, this is only for accounts with the OAuth 2.0 feature enabled and is only to refresh the access_token. If you need please use thttps://github.com/auth0/Auth0.swift/blob/master/Auth0/Authentication.swift#L394 to get a new token

**Comment by hzalaz** [comment]
A bit more info on delegation endpoint can be found here https://auth0.com/docs/api/authentication#delegation

**Comment by jacobarvidsson** [comment]
If you are using the jwt token (id token), is there anyway of refreshing it? What is the best strategy if you can't use the refresh token to refresh the id token? @hzalaz
