### ISSUE TITLE
In v2 we can no longer build out our own token request

### ISSUE THREAD

**Issue by ellneal** [auth0/Auth0.swift#800]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

In v1 of the library we could call `tokenExchange(withParameters:)` on the `Authentication` object to build a custom token request (e.g. using the client credentials grant). In v2 this call was replaced with `codeExchange(withCode:codeVerifier:redirectURI:)`, which explicitly deals with the authorisation code exchange and sets the `grant_type` to "authorization_code".

### Describe the ideal solution

The `token()` function on `Auth0Authentication` should be exposed publicly in the `Authentication` protocol.

### Alternatives and current workarounds

The initialiser on `Request` that the `Auth0Authentication.token()` function uses is also not public, so it's not possible to build a `Request` with no fixed parameters already applied.

I've worked around this by calling `codeExchange(withCode:codeVerifier:redirectURI:)` and then removing the keys that are added (using `.parameters()` and passing nil values for "code", "code_verifier" etc. to remove them). This is not ideal since any change to add a new fixed parameter in `codeExchange()` would break my workaround.

```swift
codeExchange(withCode: "", codeVerifier: "", redirectURI: "")
    .parameters([
        "code": nil,
        "code_verifier": nil,
        "redirect_uri": nil,
        "grant_type": nil
    ] as [String: Any?] as [String: Any])
```

**Comment by Widcket** [comment]
Hi @ellneal, thanks for raising this.

The code credentials grant is already supported through dedicated methods for logging in with username/password (e.g. [this one](https://auth0.github.io/Auth0.swift/documentation/auth0/authentication/login(usernameoremail:password:realmorconnection:audience:scope:)-5yc0w)). Do these methods address your use case? If not, could you please provide more information about your use case?

**Comment by ellneal** [comment]
I'm using the `client_credentials` grant (with an `audience` and a `client_secret`). I can't find any explicit method that supports this unless I'm mistaken?

**Comment by Widcket** [comment]
Mobile apps are considered public clients, so there is no need to provide a `client_secret` (it can be easily retrieved from the app binary).

**Comment by ellneal** [comment]
Our use case here is complicated, but rest assured that we are not storing a secret in the app binary. _However_, we do still need to use the `client_credentials` grant, and I would argue that since it's a function supported by the Auth0 API, it should be possible to call it from the Auth0 Swift SDK without resorting to hacks.

This is how I built the request using the v1 SDK.

```swift
let authentication = Auth0.authentication(clientId: theClientId, domain: theDomain)
let request = authentication.tokenExchange(withParameters: [
    "grant_type": "client_credentials",
    "audience": theAudience,
    "client_secret": theClientSecretThatIsNotHardcodedIntoTheBinarySoYouNeedNotWorry
])
```

And this is how I currently have to achieve the same result with the v2 SDK:

```swift
extension Auth0.Authentication {
    func clientCredentials(audience: String, secret: String) -> Request<Credentials, AuthenticationError> {
        codeExchange(withCode: "", codeVerifier: "", redirectURI: "")
            .parameters([
                "code": nil,
                "code_verifier": nil,
                "redirect_uri": nil,
                "grant_type": "client_credentials",
                "audience": audience,
                "client_secret": secret
            ] as [String: Any?] as [String: Any])
    }
}
```

**Comment by Widcket** [comment]
>However, we do still need to use the client_credentials grant, and I would argue that since it's a function supported by the Auth0 API, it should be possible to call it from the Auth0 Swift SDK without resorting to hacks.

Not all grants are supported for all application types. The client credentials grant is not supported for public applications. Mobile applications are public clients, so it is not supported by our mobile SDKs: https://auth0.com/docs/get-started/applications/application-grant-types#public-applications

<img width="814" alt="Screenshot 2023-09-25 at 4 59 33 PM" src="https://github.com/auth0/Auth0.swift/assets/5055789/2fa9bdb9-1233-495d-a674-8794a94ece06">

**Comment by ellneal** [comment]
Our use case also isn't a public application, but thanks for your assistance anyway.

**Comment by Widcket** [comment]
Could you please expand on more detail why you need the client credentials grant in particular?

**Comment by ellneal** [comment]
We're using it as an interim solution for device authentation because the Auth0 device flow does not yet support multiple organisations.

I'm not advocating for the client credentials grant to have an explicit method added as I understand that your goal is to discourage use of that where it's a potential security risk. Hence my feature request is for the `token()` function (or even just the `Request` initialisers) to be made public so that we can build our own parameter sets when calling `/oauth/token`.
