### ISSUE TITLE
Login with OTP with custom realm

### ISSUE THREAD

**Issue by MarvinNazari** [auth0/Auth0.swift#805]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We have a scenario in our app that needs to login with email and code to verify the email with a custom realm, in `Authentication` right now realm is hardcoded to always be `email`, we need to specify our own realm in this case `email-verify`.

### Describe the ideal solution

We should be able to specify our own realm in this case `email-verify` for when login when using `Authentication`. there is already a internal function that could be exposed.

```swift
func login(username: String, otp: String, realm: String, audience: String?, scope: String) -> Request<Credentials, AuthenticationError>
```

### Alternatives and current workarounds

For workaround we are now just calling the endpoints ourselves.

**Comment by Widcket** [comment]
Hi @MarvinNazari, apologies for the delay.

All the methods of the Authentication API client return a `Request` value, and this type has a `parameters()` [method](https://auth0.github.io/Auth0.swift/documentation/auth0/request/parameters(_:)) that can be used to add new values to the request payload, or to modify the existing ones.

You can use it to pass your own realm value, e.g.

```swift
Auth0
    .authentication()
    .login(email: "...", code: "...", audience: "...", scope: "...")
    .parameters(["realm": "email-verify"])
    .start { print($0) }
```
