### ISSUE TITLE
Auth0 does not support Social Logins for visionOS

### ISSUE THREAD

**Issue by maail** [auth0/Auth0.swift#821]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'd like to have social login capabilities on our visionOS app. We are already using Auth0 for social logins on our iOS and Android apps. The issue is webAuth functionality is not enabled for visionOS. 

visionOS supports directly interacting with Safari so this should be possible. 

### Describe the ideal solution

User should be able to do social logins through Google and Facebook with the webAuth flow.

### Alternatives and current workarounds

I've looked at the direct API documentation but that means having to manage all the callback functionality inside the app instead of Auth0 taking care of it for us. I'm not sure whether it's the ideal solution.

**Comment by Widcket** [comment]
Hi @maail, thanks for raising this.

The SDK does not yet support VisionOS. Unfortunately, I don't have any news to share ATM regarding future plans around this.

I'll close this issue and leave https://github.com/auth0/Auth0.swift/issues/823 open to track support for visionOS.
