### ISSUE TITLE
isNetworkError does not report case where Wifi + Mobile Data is off

### ISSUE THREAD

**Issue by lordzsolt** [auth0/Auth0.swift#822]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When I turn off Wifi + Mobile Data, and I call `oauth/token` through Auth0.swift, I receive the following error:

```
Unhandled error happened: The credentials renewal failed. CAUSE: Unable to complete the operation. CAUSE: Error Domain=NSURLErrorDomain Code=-1020 "A data connection is not currently allowed."
```

`AuthenticationError.isNetworkError` will report this as `false`, because:

Error code `-1020` is equivalent to `.dataNotAllowed` which is not in the list of `networkErrorCodes`.

-----

Interestingly, if I put the phone into airplane mode, I receive `.notConnectedToInternet` and this **is** reported as network error... 🤯 

-----

What is the intended purpose of `isNetworkError`?
- I was intending to use it to distinguish between unknown errors and network errors.

### Reproduction

1. Log in with a user on a physical device
2. Turn off Mobile Data + Wifi
3. Call `CredentialsManager.credentials(minTTL:)` with a token that triggers the `oauth/token` endpoint
4. Notice the returned error, and `isNetworkError` being `false`

### Auth0.swift version

2.5.0

### Platform

iOS

### Platform version(s)

16.1.1

### Xcode version

15.0

### Package manager

Cocoapods

**Comment by Widcket** [comment]
Hi @lordzsolt, thanks for raising this.

`.dataNotAllowed` should indeed be on the list of `networkErrorCodes`. If you raise a PR adding it I'll happily review it.
