### ISSUE TITLE
Privacy manifest

### ISSUE THREAD

**Issue by VigneshkumarMani97** [auth0/Auth0.swift#837]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Apple required App Privacy manifests for the third party SDK's used in apps, Starting in spring 2024. So Auth0 SDK contains an app privacy manifest.
As we are using Auth0 in our Apps binary, I would like to know whether the Auth0 SDK requires Privacy manifests.
Reference Link:
https://developer.apple.com/support/third-party-SDK-requirements/

### Describe the ideal solution

As we are using Auth0 in our Apps binary, I would like to know whether the Auth0 SDK requires Privacy manifests.

**Comment by iOSNinja** [comment]
Yes, we too are using Auth0 SDK in our apps, can we know whether the Auth0 SDK requires Privacy manifest/SDK signature/Tracking Domain listing?

**Comment by RoblesJ** [comment]
Hello,

I hope this message finds you well. I wanted to inquire if there have been any recent updates regarding this matter.

Additionally, I noticed that the issue referenced in our GitHub repository ([link to the issue](https://github.com/auth0/Auth0.swift/issues/810)) has been closed. Could you please provide any insights or resolutions related to it?

Furthermore, considering your other product, [SimpleKeychain](https://github.com/auth0/SimpleKeychain/tree/master), I believe it may require a manifest update to ensure compatibility with keychain usage. This update becomes particularly pertinent in light of the forthcoming requirement, effective May 1st, wherein applications lacking privacy manifests specifying API usage reasons and tracking practices risk potential rejection by the app store.

Thank you for your attention to these matters. I look forward to your response and any necessary actions.

Best regards

**Comment by Widcket** [comment]
This is now out on [v2.7.0](https://github.com/auth0/Auth0.swift/releases/tag/2.7.0)!
