### ISSUE TITLE
Auth0 podspec for iOS privacy info

### ISSUE THREAD

**Issue by ChristianRonningen** [auth0/Auth0.swift#845]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Duplicate file error when building iOS when you have your own PrivacyInfo.xcprivacy already in the project

Auth0 privacy file should be included like so: https://apnspush.com/add-privacy-manifest-sdk

### Reproduction

1. Add react-native-auth0 to your expo-managed project
2. Add your own privacy manifest in app.config.js
3. Run 'npx expo prebuild -p ios --clean'
4. Build your app, this will give you and error that buildscript creates duplicates of PrivacyInfo.xcprivacy in app

### Auth0.swift version

2.7.0

### Platform

iOS

### Platform version(s)

17

### Xcode version

15.3

### Package manager

Cocoapods

**Comment by desusai7** [comment]
Hi @ChristianRonningen, 

Thank you for raising this issue and letting us know about this. We've fixed this issue as part of version `2.7.1`. Please upgrade to this version and let us know how it goes.
