### ISSUE TITLE
What is the correct way to work with CredentialsManager in Swift Concurrency?

### ISSUE THREAD

**Issue by theolampert** [auth0/Auth0.swift#864]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The only information I can find on this is a forum post from 2 years ago in which we're directed to Github, but the option to ask a question here redirects us back to the forum so I'm opening it here as a bug https://community.auth0.com/t/credentialsmanager-credentials-and-sendability/95271

Simply initialising `CredentialsManager` causes strict concurrency checking to surface a warning that this code will no longer compile in Swift 6. What's the recommended way to work with `CredentialsManager` with strict concurrency checking enabled or in Swift 6?

### Reproduction

Initialise `CredentialsManager`

### Auth0.swift version

2.8.0

### Platform

iOS

### Platform version(s)

16.0

### Xcode version

15.4

### Package manager

Swift Package Manager

**Comment by Vaidios** [comment]
I opted to defining this import as @preconcurrency, until it will fully support swift 6. It seems like concurrent safe access is also handled using GCD inside the library

**Comment by theolampert** [comment]
> I opted to defining this import as @preconcurrency, until it will fully support swift 6. It seems like concurrent safe access is also handled using GCD inside the library

Thanks, I've found using `@preconcurrency` to be somewhat buggy in the latest betas but I'll give it another look.
