### ISSUE TITLE
Unsync releases broke the stuff

### ISSUE THREAD

**Issue by pewkachu** [auth0/Auth0.swift#869]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

SPM is broken because of the async release of your libraries. I assume the release pipeline needs some improvements

![CleanShot 2024-09-17 at 12 36 46](https://github.com/user-attachments/assets/aa926ada-14a0-439e-bf92-d4ae943c752d)

Waiting for the 2.9.0 version release

### Reproduction

Just use this package as a dependency. Even your sample app is broken

![CleanShot 2024-09-17 at 12 41 22](https://github.com/user-attachments/assets/7093d772-57b8-4ad2-a5b3-49cf465d6db9)

### Auth0.swift version

2.8.0

### Platform

iOS

### Platform version(s)

iOS

### Xcode version

15.4

### Package manager

Swift Package Manager

**Comment by jfk056** [comment]
Hi @desusai7, I hope you're doing well! Would you mind taking a look at this issue when you have a moment? Our CI process is completely blocked and we would like to resolve the issue as soon as possible, due to upcoming release. Thanks so much for your time!

**Comment by desusai7** [comment]
Hi @pewkachu, @jfk056, 

Apologies for all the delay on this, we've just released 2.9.0

**Comment by desusai7** [comment]
Closing this for now, feel free to re-open it again if you run into any issues
