### ISSUE TITLE
Failed to start this transaction, as there is an active transaction at the moment.

### ISSUE THREAD

**Issue by vineal** [auth0/Auth0.swift#879]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The start() function throws an error when app goes into background, when the user has clicked on login and the System alert opens up.
Post which you need to kill the app and re-launch it in order for it to reset from the error state.

This is the method from the SDK we consume in our App.
```swift
do {
    let credentials = try await Auth0.webAuth().start()
    print("Obtained credentials: \(credentials)")
} catch {
    print("Failed with: \(error)")
}
```

### Reproduction

1. Click on login
2. When the system prompt appears to allow the website to use your information.
3. Lock your device screen
4. Unlock your screen and the alert should have now disappeared
5. When you now try to click on login, it throws the error `Failed to start this transaction, as there is an active transaction at the moment.`
6. Only terminating the instance of the running app then resolves the issue.

### Additional context

I've looked into the package and I believe this might be the issue: 
![CleanShot 2024-10-15 at 13 42 29](https://github.com/user-attachments/assets/770342e3-b42b-4951-bf21-b90085e6962b)

Is there a way you can check if a session is in progress through the userAgent rather than storing it in a variable on initiation of login/signup.

Here is a example of it happens on our App.

https://github.com/user-attachments/assets/91caf29d-5f87-40a9-9b3b-d2bc79f8c99d

### Auth0.swift version

2.10.0

### Platform

iOS

### Platform version(s)

iOS 17.4

### Xcode version

v 15.3

### Package manager

Swift Package Manager

**Comment by cgomez-rb** [comment]
@vineal We just encounter this issue in our implementation as well, but on iPad by backgrounding the app when the system prompt appears. Whenever we foreground the app again the system prompt is dismissed and by selecting sign in again causes the same error. In our case, it's happening in iOS 18, using Xcode 16.0, using Auth0 SDK version 2.9.0.
I think either the SDK handles this by calling `cancel()` on the ASWebAuthenticationSession, so the callback is called and clearing the transaction storage when the system prompt is dismissed, or the SDK needs to expose a function to clear the transaction storage so this is handled by each client.

**Comment by cgomez-rb** [comment]
@desusai7 do you have any ETA on when this could be resolved?

**Comment by pmathew92** [comment]
Hey @vineal @cgomez-rb  ,We have identified this due to a bug in the underlying Apple API used by the SDK (`ASWebAuthenticationSession `). We have raised an issue with Apple and are waiting on them . Mean while as a workaround, you can invoke the `WebAuthentication.cancel()` method when you encounter this error to cancel the existing transaction. 
If SSO is not required, you can use `ephemeral sessions` or `SFSafariViewController` also.
Please find more details in our [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md#5-how-to-resolve-the-failed-to-start-this-transaction-as-there-is-an-active-transaction-at-the-moment-error)

**Comment by pmathew92** [comment]
Closing this for now. Please feel free to reopen this if you have any more concerns
