### ISSUE TITLE
Cannot clear `transactionActiveAlready` error

### ISSUE THREAD

**Issue by patrickcapadmi** [auth0/Auth0.swift#891]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

If the user manages to hit a [transactionActiveAlready](https://auth0.github.io/Auth0.swift/documentation/auth0/webautherror/transactionactivealready) error response when attempting to initiate an authentication session, there does not appear to be any way to clear or restart the active transaction via `Auth0WebAuth` or clear from the `TransactionStore` which is internal to the SDK.

It is fairly easy for a user to get into this state if they manage to cancel the `ASWebAuthenticationSession` whilst the initial permission modal is shown which can be done by simply locking the device.

### Reproduction

- Initiate web auth session per standard steps - https://auth0.com/docs/quickstart/native/ios-swift#login
- Lock device whilst `ASWebAuthenticationSession` modal is showing on screen
- Attempt a second, third etc web auth session
- Receive `transactionActiveAlready` error in response

### Auth0.swift version

2.10.0

### Platform

iOS

### Platform version(s)

18.1

### Xcode version

16.1

### Package manager

Swift Package Manager

**Comment by pmathew92** [comment]
Hi @patrickcapadmi ,
Thank you raising this issue. We already have a workaround added in our [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md#5-how-to-resolve-the-failed-to-start-this-transaction-as-there-is-an-active-transaction-at-the-moment-error) for the above error

**Comment by patrickcapadmi** [comment]
Ahh thank you for the quick response. Might warrant some comments in the codebase about that? 

Not quite sure how I didn't find the FAQs when Googling...
