### ISSUE TITLE
When renewing a token, credential.idToken is nil

### ISSUE THREAD

**Issue by thierrybucco** [auth0/Auth0.swift#99]
Hi,

I am trying to refresh token using renew method but it does not work. Returned credentials.idToken is set to nil. Here is my code.

```
auth0.logging(enabled: LOG_NETWORK_MANAGER_AUTHENTICATION_ENABLED)
.renew(withRefreshToken: refreshToken)
.start {  [ weak self ] result in
	switch result {
		case .success(let credentials):
			if let idToken = credentials.idToken {
				saveAccessToken(idToken)
			}
		case .failure(let error):
			LOG_NETWORK_MANAGER_AUTHENTICATION("Id Token renew failed with error: \(error)")
	}
}
```

Thanks

**Comment by cocojoe** [comment]
Hi @thierrybucco 

You can make a call to the `delegation` method to return an idToken using your refreshToken.
You can find a complete example [here](https://github.com/auth0-samples/auth0-ios-swift-v2-sample/blob/master/03-User-Sessions/Auth0Sample/SessionManager.swift#L71)

Thanks

**Comment by thierrybucco** [comment]
Thanks @cocojoe but I read somewhere in Auth0 website that the best way is to use renew method.

**Comment by hzalaz** [comment]
@thierrybucco you can use `renewAuth` if you set your client flag `OIDC conferment` that can be found in your client settings -> show advanced -> OAuth. 

We will improve the docs to avoid this confusion in the future.

**Comment by hzalaz** [comment]
Or you can follow @cocojoe 's advice

**Comment by thierrybucco** [comment]
@hzalaz I need more explanation about renewAuth is it a Auth0.swift method?
My project is in swift 3.

**Comment by hzalaz** [comment]
Sorry mixed languages `renew`

**Comment by thierrybucco** [comment]
@hzalaz I set client flag as suggested and I got his error: OIDC conformant clients cannot use /oauth/ro

**Comment by hzalaz** [comment]
Sorry forgot to ask how you were doing Auth. For OIDC you need to use the [login with realm](https://github.com/auth0/Auth0.swift/blob/master/Auth0/Authentication.swift#L122) where the realm is the same as the connection name. If you want you can continue to use /ro but use /delegation to refresh the tokens, which will be the a good approach since we haven't published the new OIDC flow docs.

**Comment by thierrybucco** [comment]
It works using delegation but not using renew method.

**Comment by ankits16** [comment]
https://github.com/auth0-samples/auth0-ios-swift-v2-sample/blob/master/03-User-Sessions/Auth0Sample/SessionManager.swift#L71
this link does not work
@hzalaz I get this response in case of delegation api 

> "error_description": "Cannot set property 'undefinedorganization_uri' of undefined",

then I enabled the OIDC settings for the client yet I get a nil id token in case of '**renew**' api

**Comment by hzalaz** [comment]
@ankits16 yes its an old issue post, now in the readme we explain session management https://github.com/auth0/Auth0.swift#renew-user-credentials. Your error is probably due to a custom rule with bad code not related to the SDK so please check them or try it with them disable

**Comment by ankits16** [comment]
@hzalaz yupp you are right, thanks for the swift response
